#!/usr/bin/env python3
"""cffi 2.1.1 device test (full wheel: cffi + _cffi_backend + pycparser).

Sections:
  1. import + version + backend location
  2. FFI object surface: sizeof/alignof/new/cast/memmove/buffer/string
  3. parser path (pycparser): cdef + structs + pointers/arrays
  4. ABI mode end-to-end: dlopen(libc) + call strlen/getpid   [linux/android]
  5. closure support (libffi closures): qsort with a Python callback  [linux]
  6. dlopen versioned libc symbols                                [linux]

Sections 4-6 are SKIPped on non-linux hosts (they need a real libc dlopen).

Generated by RIMI
"""
import sys

PASS = FAIL = SKIP = 0


def chk(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print("  PASS  %s %s" % (name, detail))
    else:
        FAIL += 1
        print("  FAIL  %s %s" % (name, detail))


def skip(name, reason):
    global SKIP
    SKIP += 1
    print("  SKIP  %s (%s)" % (name, reason))


def section(title):
    print("\n=== %s ===" % title)


IS_LINUX = sys.platform.startswith("linux")

section("1. import + version + backend location")
import cffi  # noqa: E402
import _cffi_backend  # noqa: E402

chk("cffi version", cffi.__version__ == "2.1.1", cffi.__version__)
chk("backend exports FFI", hasattr(_cffi_backend, "FFI"))
chk("backend FFI_DEFAULT_ABI", hasattr(_cffi_backend, "FFI_DEFAULT_ABI"))
chk("backend primitives", hasattr(_cffi_backend, "new_primitive_type")
    and hasattr(_cffi_backend, "new_pointer_type")
    and hasattr(_cffi_backend, "newp") and hasattr(_cffi_backend, "sizeof"))
chk("backend module file", "_cffi_backend" in _cffi_backend.__file__,
    _cffi_backend.__file__)
chk("FFI class available", hasattr(cffi, "FFI") and callable(cffi.FFI))

section("2. FFI object surface")
ffi = cffi.FFI()
chk("sizeof int==4", ffi.sizeof("int") == 4)
chk("sizeof double==8", ffi.sizeof("double") == 8)
chk("sizeof void*==8", ffi.sizeof("void *") == 8)
chk("alignof int==4", ffi.alignof("int") == 4)
chk("new int*", isinstance(ffi.new("int *", 42), ffi.CData))
chk("new array", ffi.sizeof(ffi.new("int[5]")) == 20)
chk("cast", int(ffi.cast("long", 12345)) == 12345)
p = ffi.new("int[]", [1, 2, 3])
buf = ffi.buffer(p, 12)
chk("buffer bytes", bytes(buf) == b"\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00")
s = ffi.new("char[]", b"hello")
chk("string from char[]", ffi.string(s) == b"hello")
dst = ffi.new("char[]", 16)
ffi.memmove(dst, b"abc123", 6)
chk("memmove copies bytes", ffi.string(dst) == b"abc123")
chk("NULL is cdata", isinstance(ffi.NULL, ffi.CData))

section("3. parser path (pycparser)")
ffi.cdef("""
typedef struct Point { int x; int y; } Point;
int point_sum(Point p);
void *malloc(size_t size);
void free(void *ptr);
""")
pt = ffi.new("Point *")
pt.x = 3
pt.y = 4
chk("struct field set/get", pt.x == 3 and pt.y == 4)
chk("sizeof struct >= 8", ffi.sizeof("Point") >= 8)
m = ffi.new("void *[1]")
chk("pointer array", isinstance(m, ffi.CData) and ffi.sizeof(m) == ffi.sizeof("void *"))
chk("cdef'd types present", ffi.typeof("Point").kind == "struct")
chk("enum via parser", ffi.new("int[1]") is not None)

if not IS_LINUX:
    skip("dlopen libc call", "non-linux host (no libc dlopen)")
    skip("qsort closure", "non-linux host")
    skip("versioned libc symbols", "non-linux host")
else:
    section("4. ABI mode end-to-end: dlopen(libc)")
    ffi.cdef("""
    size_t strlen(const char *s);
    int getpid(void);
    int abs(int j);
    int tolower(int c);
    void *memchr(const void *s, int c, size_t n);
    """)
    libc = ffi.dlopen("libc.so")
    chk("dlopen libc OK", libc is not None)
    strlen = libc.strlen
    chk("strlen('hello')==5", int(strlen(b"hello")) == 5)
    getpid = libc.getpid
    pid = int(getpid())
    chk("getpid > 0", pid > 0, "pid=%d" % pid)
    abs_v = libc.abs
    chk("abs(-7)==7", int(abs_v(-7)) == 7)
    chk("tolower('A')=='a'", chr(int(libc.tolower(ord("A")))) == "a")

    section("5. closure support (ffi.callback + qsort)")
    ffi.cdef("""
    void qsort(void *base, size_t nmemb, size_t size,
               int (*compar)(const void *, const void *));
    """)
    cmp_int = ffi.callback("int(const void *, const void *)",
                           lambda a, b: (ffi.cast("const int *", a)[0] >
                                         ffi.cast("const int *", b)[0]) -
                                        (ffi.cast("const int *", a)[0] <
                                         ffi.cast("const int *", b)[0]))
    chk("callback created", cmp_int is not None)
    qsort = libc.qsort
    arr = ffi.new("int[]", [5, 2, 8, 1, 9, 3, 7, 4, 6, 0])
    qsort(arr, 10, ffi.sizeof("int"), cmp_int)
    chk("qsort sorted array", list(arr) == list(range(10)), repr(list(arr)))
    arr2 = ffi.new("int[]", [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
    qsort(arr2, 11, ffi.sizeof("int"), cmp_int)
    chk("qsort closure reusable", list(arr2) == list(range(11)), repr(list(arr2)))
    chk("callback cdata alive", str(cmp_int).startswith("<cdata"))

    section("6. versioned/extra libc symbols")
    getpid2 = libc.getpid
    chk("versioned symbol call", int(getpid2()) == int(getpid2()))
    memchr = libc.memchr
    hay = b"abcdefg"
    res = memchr(hay, ord("d"), len(hay))
    chk("memchr finds byte", ffi.string(ffi.cast("char *", res)) == b"defg")

print("\n===== RESULT: PASS=%d FAIL=%d SKIP=%d =====" % (PASS, FAIL, SKIP))
sys.exit(1 if FAIL else 0)
