"""
Test_Telethon.py - Telethon Test Suite for PythonSTB (Android)
Generated by RIMI
"""
import sys

PASS = 0
FAIL = 0
SKIP = 0
RESULTS = []

def test(name, func):
    global PASS, FAIL, SKIP
    try:
        result = func()
        if result is not False:
            PASS += 1
            RESULTS.append(("PASS", name))
        elif result == "SKIP":
            SKIP += 1
            RESULTS.append(("SKIP", name))
        else:
            FAIL += 1
            RESULTS.append(("FAIL", name))
    except Exception as e:
        FAIL += 1
        RESULTS.append(("FAIL", f"{name} -> {type(e).__name__}: {e}"))

print("=" * 60)
print(" TELETHON TEST SUITE")
print(" PythonSTB - Android ARM64/x86_64")
print("=" * 60)
print()

# --- Core Imports ---
test("telethon import", lambda: __import__("telethon"))
test("telethon.version", lambda: __import__("telethon").version)
test("telethon TelegramClient", lambda: __import__("telethon").TelegramClient)
test("telethon functions", lambda: __import__("telethon").functions)
test("telethon types", lambda: __import__("telethon").types)
test("telethon events", lambda: __import__("telethon").events)
test("telethon sessions", lambda: __import__("telethon").sessions)
test("telethon utils", lambda: __import__("telethon").utils)
test("telethon errors", lambda: __import__("telethon").errors)

# --- Dependencies ---
test("rsa import", lambda: __import__("rsa"))
test("pyaes import", lambda: __import__("pyaes"))

# --- Version Info ---
def test_version():
    import telethon
    v = telethon.__version__
    print(f"    Telethon version: {v}")
    return True
test("version info", test_version)

# --- Core Classes ---
def test_classes():
    from telethon import TelegramClient, utils, types, functions, events, errors, sessions
    classes = [TelegramClient, utils, types, functions, events, errors, sessions]
    for c in classes:
        assert c is not None
    print(f"    Core classes loaded: {len(classes)}")
    return True
test("core classes", test_classes)

# --- TL Schema ---
def test_tl_schema():
    from telethon.tl import types, functions
    assert hasattr(functions, 'users')
    print("    TL schema loaded")
    return True
test("tl schema", test_tl_schema)

# --- Events ---
def test_events():
    from telethon import events
    event_types = [
        events.NewMessage,
        events.MessageEdited,
        events.MessageDeleted,
        events.ChatAction,
        events.UserUpdate,
    ]
    loaded = sum(1 for e in event_types if e is not None)
    print(f"    Event types available: {loaded}/{len(event_types)}")
    return loaded >= 3
test("event types", test_events)

# --- Errors ---
def test_errors():
    from telethon import errors
    error_classes = [
        errors.FloodWaitError,
        errors.SessionPasswordNeededError,
        errors.PhoneCodeInvalidError,
    ]
    loaded = sum(1 for e in error_classes if e is not None)
    print(f"    Error classes available: {loaded}/{len(error_classes)}")
    return loaded >= 2
test("error classes", test_errors)

# --- Sessions ---
def test_sessions():
    from telethon.sessions import StringSession, MemorySession
    s = MemorySession()
    assert s is not None
    print("    Sessions work")
    return True
test("session creation", test_sessions)

# --- Utils ---
def test_utils():
    from telethon import utils
    print("    Utils loaded")
    return True
test("utils", test_utils)

# --- TelegramClient instantiation (no connect) ---
def test_client_init():
    from telethon import TelegramClient
    from telethon.sessions import MemorySession
    client = TelegramClient(MemorySession(), api_id=12345, api_hash='test_hash')
    assert client is not None
    print("    TelegramClient instantiated (no connect)")
    return True
test("client init", test_client_init)

# --- Crypto ---
def test_crypto():
    from telethon.crypto import AuthKey
    key = AuthKey(data=b'\x00' * 256)
    assert key is not None
    print("    AuthKey created")
    return True
test("crypto authkey", test_crypto)

# --- Print Results ---
print()
print("=" * 60)
print(" RESULTS")
print("=" * 60)
for status, name in RESULTS:
    icon = "PASS" if status == "PASS" else "FAIL" if status == "FAIL" else "SKIP"
    print(f"  [{icon}] {name}")
print()
print(f"  PASS: {PASS} | FAIL: {FAIL} | SKIP: {SKIP}")
print(f"  TOTAL: {PASS + FAIL + SKIP}")
print("=" * 60)

if FAIL > 0:
    print("\nTELETHON HAS FAILURES - REBUILD MAY BE NEEDED")
    sys.exit(1)
else:
    print("\nTELETHON ALL PASSED")
    sys.exit(0)
