#!/usr/bin/env python3
"""
Test_rpds_py.py - on-device validation for the rpds-py wheel.

Exercises the Rust/PyO3 persistent data structures through the public API.
Exit code 0 = all tests passed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


# ---------------------------------------------------------------------------
# 1. imports
# ---------------------------------------------------------------------------
def test_import():
    import rpds
    check(rpds is not None, "rpds is None")
    print("  rpds module imported OK")


def test_import_map():
    from rpds import Map
    check(Map is not None, "Map is None")
    print("  Map imported OK")


def test_import_list():
    from rpds import List
    check(List is not None, "List is None")
    print("  List imported OK")


def test_import_set():
    from rpds import Set
    check(Set is not None, "Set is None")
    print("  Set imported OK")


def test_import_stack():
    from rpds import Stack
    check(Stack is not None, "Stack is None")
    print("  Stack imported OK")


def test_import_queue():
    from rpds import Queue
    check(Queue is not None, "Queue is None")
    print("  Queue imported OK")


# ---------------------------------------------------------------------------
# 2. Map
# ---------------------------------------------------------------------------
def test_map_creation():
    from rpds import Map
    m = Map()
    check(len(m) == 0, "empty map")
    print("  Map() created, len=%d" % len(m))


def test_map_insert():
    from rpds import Map
    m = Map()
    m["a"] = 1
    m["b"] = 2
    m["c"] = 3
    check(len(m) == 3, "len=%d" % len(m))
    check(m["a"] == 1, "a mismatch")
    check(m["b"] == 2, "b mismatch")
    check(m["c"] == 3, "c mismatch")
    print("  Map insert: %d items" % len(m))


def test_map_get():
    from rpds import Map
    m = Map()
    m["x"] = 42
    check(m["x"] == 42, "get mismatch")
    try:
        _ = m["nonexistent"]
        check(False, "should raise KeyError")
    except KeyError:
        pass
    print("  Map get: OK")


def test_map_contains():
    from rpds import Map
    m = Map()
    m["key"] = "value"
    check("key" in m, "key not in map")
    check("other" not in m, "other in map")
    print("  Map contains: OK")


def test_map_delete():
    from rpds import Map
    m = Map()
    m["a"] = 1
    m2 = m.delete("a")
    check(len(m2) == 0, "deleted map not empty")
    check(len(m) == 1, "original modified")
    print("  Map delete (persistent): OK")


def test_map_iter():
    from rpds import Map
    m = Map()
    m["a"] = 1
    m["b"] = 2
    m["c"] = 3
    keys = list(m)
    check(len(keys) == 3, "iter length")
    check(sorted(keys) == ["a", "b", "c"], "keys mismatch")
    print("  Map iteration: %s" % sorted(keys))


def test_map_persistent():
    from rpds import Map
    m1 = Map()
    m1["a"] = 1
    m2 = m1.set("b", 2)
    check(len(m1) == 1, "m1 modified")
    check(len(m2) == 2, "m2 wrong length")
    check(m2["a"] == 1, "m2 missing a")
    check(m2["b"] == 2, "m2 missing b")
    print("  Map persistence: OK")


def test_map_set():
    from rpds import Map
    m = Map()
    m = m.set("a", 1)
    m = m.set("a", 99)
    check(m["a"] == 99, "set overwrite")
    print("  Map set overwrite: OK")


# ---------------------------------------------------------------------------
# 3. List
# ---------------------------------------------------------------------------
def test_list_creation():
    from rpds import List
    l = List()
    check(len(l) == 0, "empty list")
    print("  List() created, len=%d" % len(l))


def test_list_append():
    from rpds import List
    l = List()
    l = l.append("a")
    l = l.append("b")
    l = l.append("c")
    check(len(l) == 3, "len=%d" % len(l))
    check(l[0] == "a", "index 0")
    check(l[2] == "c", "index 2")
    print("  List append: %d items" % len(l))


def test_list_get():
    from rpds import List
    l = List()
    l = l.append(10)
    l = l.append(20)
    check(l[0] == 10, "get 0")
    check(l[1] == 20, "get 1")
    print("  List get: OK")


def test_list_persistent():
    from rpds import List
    l1 = List()
    l1 = l1.append("x")
    l2 = l1.append("y")
    check(len(l1) == 1, "l1 modified")
    check(len(l2) == 2, "l2 wrong")
    check(l2[0] == "x", "l2[0]")
    check(l2[1] == "y", "l2[1]")
    print("  List persistence: OK")


def test_list_iter():
    from rpds import List
    l = List()
    l = l.append(1)
    l = l.append(2)
    l = l.append(3)
    items = list(l)
    check(items == [1, 2, 3], "iter mismatch: %s" % items)
    print("  List iteration: %s" % items)


# ---------------------------------------------------------------------------
# 4. Set
# ---------------------------------------------------------------------------
def test_set_creation():
    from rpds import Set
    s = Set()
    check(len(s) == 0, "empty set")
    print("  Set() created, len=%d" % len(s))


def test_set_add():
    from rpds import Set
    s = Set()
    s = s.add("a")
    s = s.add("b")
    s = s.add("c")
    check(len(s) == 3, "len=%d" % len(s))
    print("  Set add: %d items" % len(s))


def test_set_contains():
    from rpds import Set
    s = Set()
    s = s.add("hello")
    check("hello" in s, "not in set")
    check("world" not in s, "in set")
    print("  Set contains: OK")


def test_set_delete():
    from rpds import Set
    s = Set()
    s = s.add("a")
    s2 = s.delete("a")
    check(len(s2) == 0, "s2 not empty")
    check(len(s) == 1, "s modified")
    print("  Set delete (persistent): OK")


def test_set_persistent():
    from rpds import Set
    s1 = Set()
    s1 = s1.add(1)
    s2 = s1.add(2)
    check(len(s1) == 1, "s1 modified")
    check(len(s2) == 2, "s2 wrong")
    print("  Set persistence: OK")


# ---------------------------------------------------------------------------
# 5. Stack
# ---------------------------------------------------------------------------
def test_stack_creation():
    from rpds import Stack
    s = Stack()
    check(len(s) == 0, "empty stack")
    print("  Stack() created, len=%d" % len(s))


def test_stack_push_pop():
    from rpds import Stack
    s = Stack()
    s = s.push("a")
    s = s.push("b")
    check(s.peek() == "b", "peek")
    s2, val = s.drop()
    check(val == "b", "pop value")
    check(s2.peek() == "a", "next peek")
    print("  Stack push/pop: OK")


def test_stack_persistent():
    from rpds import Stack
    s1 = Stack()
    s1 = s1.push(1)
    s2 = s1.push(2)
    check(s1.peek() == 1, "s1 modified")
    check(s2.peek() == 2, "s2 wrong")
    print("  Stack persistence: OK")


# ---------------------------------------------------------------------------
# 6. Queue
# ---------------------------------------------------------------------------
def test_queue_creation():
    from rpds import Queue
    q = Queue()
    check(len(q) == 0, "empty queue")
    print("  Queue() created, len=%d" % len(q))


def test_queue_enqueue_dequeue():
    from rpds import Queue
    q = Queue()
    q = q.enqueue("first")
    q = q.enqueue("second")
    q2, val = q.peek()
    check(val == "first", "dequeue value")
    check(len(q2) == len(q) - 1, "queue length")
    print("  Queue enqueue/dequeue: OK")


def test_queue_persistent():
    from rpds import Queue
    q1 = Queue()
    q1 = q1.enqueue(10)
    q2 = q1.enqueue(20)
    check(len(q1) == 1, "q1 modified")
    check(len(q2) == 2, "q2 wrong")
    print("  Queue persistence: OK")


# ---------------------------------------------------------------------------
# 7. large data
# ---------------------------------------------------------------------------
def test_map_large():
    from rpds import Map
    m = Map()
    for i in range(1000):
        m = m.set(i, i * i)
    check(len(m) == 1000, "len=%d" % len(m))
    check(m[500] == 250000, "m[500]")
    print("  Map(1000): OK")


def test_list_large():
    from rpds import List
    l = List()
    for i in range(500):
        l = l.append(i)
    check(len(l) == 500, "len=%d" % len(l))
    check(l[0] == 0, "l[0]")
    check(l[499] == 499, "l[499]")
    print("  List(500): OK")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    section("1. imports")
    test("import rpds", test_import)
    test("import Map", test_import_map)
    test("import List", test_import_list)
    test("import Set", test_import_set)
    test("import Stack", test_import_stack)
    test("import Queue", test_import_queue)

    section("2. Map")
    test("Map creation", test_map_creation)
    test("Map insert", test_map_insert)
    test("Map get", test_map_get)
    test("Map contains", test_map_contains)
    test("Map delete", test_map_delete)
    test("Map iteration", test_map_iter)
    test("Map persistence", test_map_persistent)
    test("Map set overwrite", test_map_set)

    section("3. List")
    test("List creation", test_list_creation)
    test("List append", test_list_append)
    test("List get", test_list_get)
    test("List persistence", test_list_persistent)
    test("List iteration", test_list_iter)

    section("4. Set")
    test("Set creation", test_set_creation)
    test("Set add", test_set_add)
    test("Set contains", test_set_contains)
    test("Set delete", test_set_delete)
    test("Set persistence", test_set_persistent)

    section("5. Stack")
    test("Stack creation", test_stack_creation)
    test("Stack push/pop", test_stack_push_pop)
    test("Stack persistence", test_stack_persistent)

    section("6. Queue")
    test("Queue creation", test_queue_creation)
    test("Queue enqueue/dequeue", test_queue_enqueue_dequeue)
    test("Queue persistence", test_queue_persistent)

    section("7. large data")
    test("Map(1000)", test_map_large)
    test("List(500)", test_list_large)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
