#!/usr/bin/env python3
"""PyAudio 0.2.14 device test - network-safe, no external files required.

Sections:
  1. import + version + constants surface        (no audio hardware needed)
  2. PyAudio init + host API / device enumeration(no audio hardware needed)
  3. PLAYBACK: raw PCM, base64-encoded PCM string, and a WAV file read back
     by path (all generated locally - NO mp3: pyaudio is raw-PCM only)
  4. stream lifecycle + terminate
Hardware-dependent playback checks are SKIPPED (not failed) when the device
exposes no usable audio output, so the test still exits 0 on audio-less
emulators.

Generated by RIMI
"""
import base64
import math
import os
import struct
import sys
import wave

PASS = FAIL = SKIP = 0


def chk(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print("  PASS  %s %s" % (name, detail))
    else:
        FAIL += 1
        print("  FAIL  %s %s" % (name, detail))


def skip(name, reason):
    global SKIP
    SKIP += 1
    print("  SKIP  %s (hardware: %s)" % (name, reason))


def section(title):
    print("\n=== %s ===" % title)


def make_sine(seconds=0.4, rate=44100, freq=440.0):
    n = int(seconds * rate)
    amp = 8000
    return b"".join(
        struct.pack("<h", int(amp * math.sin(2 * math.pi * freq * i / rate)))
        for i in range(n))


section("1. import + version + constants surface")
import pyaudio

chk("pyaudio imports", pyaudio.__version__ == "0.2.14", pyaudio.__version__)
chk("get_portaudio_version int", isinstance(pyaudio.get_portaudio_version(), int))
chk("get_portaudio_version_text", isinstance(pyaudio.get_portaudio_version_text(), str) and
    len(pyaudio.get_portaudio_version_text()) > 0, repr(pyaudio.get_portaudio_version_text()))
chk("sample format constants", all(hasattr(pyaudio, n) for n in (
    "paFloat32", "paInt32", "paInt24", "paInt16", "paInt8", "paUInt8", "paCustomFormat")))
chk("host api constants", all(hasattr(pyaudio, n) for n in (
    "paInDevelopment", "paDirectSound", "paMME", "paASIO", "paCoreAudio", "paOSS",
    "paALSA", "paWDMKS", "paJACK", "paWASAPI", "paNoDevice")))
chk("error constants", pyaudio.paNoError == 0 and all(hasattr(pyaudio, n) for n in (
    "paNotInitialized", "paUnanticipatedHostError", "paInvalidDevice",
    "paSampleFormatNotSupported", "paDeviceUnavailable", "paHostApiNotFound")))
chk("callback return codes", (pyaudio.paContinue, pyaudio.paComplete, pyaudio.paAbort) == (0, 1, 2))
chk("paFramesPerBufferUnspecified", pyaudio.paFramesPerBufferUnspecified == 0)
chk("get_sample_size paInt8", pyaudio.get_sample_size(pyaudio.paInt8) == 1)
chk("get_sample_size paInt16", pyaudio.get_sample_size(pyaudio.paInt16) == 2)
chk("get_sample_size paInt24", pyaudio.get_sample_size(pyaudio.paInt24) == 3)
chk("get_sample_size paInt32", pyaudio.get_sample_size(pyaudio.paInt32) == 4)
chk("get_sample_size paFloat32", pyaudio.get_sample_size(pyaudio.paFloat32) == 4)
try:
    pyaudio.get_sample_size(999)
    chk("get_sample_size invalid raises", False)
except ValueError:
    chk("get_sample_size invalid raises", True)
chk("get_format_from_width", (pyaudio.get_format_from_width(1), pyaudio.get_format_from_width(1, False),
    pyaudio.get_format_from_width(2), pyaudio.get_format_from_width(3),
    pyaudio.get_format_from_width(4)) == (pyaudio.paUInt8, pyaudio.paInt8,
    pyaudio.paInt16, pyaudio.paInt24, pyaudio.paFloat32))
try:
    pyaudio.get_format_from_width(5)
    chk("get_format_from_width invalid raises", False)
except ValueError:
    chk("get_format_from_width invalid raises", True)

section("2. PyAudio init + host API / device enumeration")
try:
    pa = pyaudio.PyAudio()
    chk("PyAudio() init", True)
except Exception as exc:
    chk("PyAudio() init", False, repr(exc))
    print("===== %d PASS, %d FAIL, %d SKIP =====" % (PASS, FAIL, SKIP))
    sys.exit(1)

try:
    napi = pa.get_host_api_count()
    chk("host api count >= 1", napi >= 1, "count=%d" % napi)
except Exception as exc:
    chk("host api count >= 1", False, repr(exc))
    napi = 0

default_host_api = None
if napi > 0:
    try:
        info = pa.get_default_host_api_info()
        default_host_api = info
        chk("default host api info dict", all(k in info for k in (
            "index", "structVersion", "type", "name", "deviceCount",
            "defaultInputDevice", "defaultOutputDevice")), repr(info.get("name")))
        chk("default host api name", isinstance(info.get("name"), str) and len(info["name"]) > 0)
    except Exception as exc:
        chk("default host api info dict", False, repr(exc))
    for i in range(napi):
        try:
            h = pa.get_host_api_info_by_index(i)
            ok = all(k in h for k in ("index", "type", "name", "deviceCount"))
            chk("host api %d info" % i, ok, "%s devices=%d" % (h.get("name"), h.get("deviceCount")))
        except Exception as exc:
            chk("host api %d info" % i, False, repr(exc))

ndev = pa.get_device_count()
chk("device count >= 0", ndev >= 0, "count=%d" % ndev)
if ndev > 0:
    try:
        d = pa.get_device_info_by_index(0)
        chk("device 0 info dict", all(k in d for k in (
            "index", "name", "maxInputChannels", "maxOutputChannels",
            "defaultSampleRate")), repr(d.get("name")))
        chk("device 0 sample rate > 0", isinstance(d.get("defaultSampleRate"), float) and
            d["defaultSampleRate"] > 0, "rate=%.0f" % d.get("defaultSampleRate", -1))
        chk("device 0 via host api mapping",
            isinstance(pa.get_device_info_by_host_api_device_index(0, 0), dict))
    except Exception as exc:
        chk("device 0 info dict", False, repr(exc))
else:
    skip("device enumeration", "no audio devices exposed")

out_device = None
try:
    out_device = pa.get_default_output_device_info()
    chk("default output device info", out_device["maxOutputChannels"] >= 0, repr(out_device.get("name")))
except Exception as exc:
    skip("default output device", "none (no output device)")

in_device = None
try:
    in_device = pa.get_default_input_device_info()
    chk("default input device info", in_device["maxInputChannels"] >= 0, repr(in_device.get("name")))
except Exception as exc:
    skip("default input device", "none (no input device)")

if ndev > 0 and out_device is not None:
    try:
        supported = pa.is_format_supported(44100.0, output_device=out_device["index"],
                                           output_channels=1, output_format=pyaudio.paInt16)
        chk("is_format_supported 44100/mono/int16", supported is True, repr(supported))
    except ValueError as exc:
        skip("is_format_supported", "unsupported on this device")
    except Exception as exc:
        skip("is_format_supported", repr(exc))
else:
    skip("is_format_supported", "no output device")

section("3. playback (raw PCM, base64 PCM, WAV by path)")
sine = make_sine(0.4)
chk("sine generation size", len(sine) == int(0.4 * 44100) * 2, "%d bytes" % len(sine))

b64 = base64.b64encode(sine).decode("ascii")
chk("base64 encode/decode roundtrip", base64.b64decode(b64) == sine, "b64 len=%d" % len(b64))

home = os.environ.get("HOME") or os.getcwd()
wav_dir = os.path.join(home, "files")
os.makedirs(wav_dir, exist_ok=True)
wav_path = os.path.join(wav_dir, "pyaudio_test.wav")
with wave.open(wav_path, "wb") as wf:
    wf.setnchannels(1)
    wf.setsampwidth(2)
    wf.setframerate(44100)
    wf.writeframes(sine)
chk("wav written", os.path.exists(wav_path) and os.path.getsize(wav_path) > 44, wav_path)


def play_pcm(data, label):
    if out_device is None:
        skip(label, "no output device")
        return
    try:
        stream = pa.open(rate=44100, channels=1, format=pyaudio.paInt16,
                         input=False, output=True,
                         output_device_index=out_device["index"],
                         frames_per_buffer=512, start=True)
        stream.write(data)
        stream.stop_stream()
        stream.close()
        chk(label, True, "%.2fs written" % (len(data) / (44100 * 2)))
    except (IOError, OSError) as exc:
        skip(label, str(exc))


play_pcm(sine, "play raw PCM tone")
play_pcm(base64.b64decode(b64), "play base64-encoded PCM string")

section("4. stream lifecycle")
if out_device is not None:
    try:
        stream = pa.open(rate=44100, channels=1, format=pyaudio.paInt16,
                         input=False, output=True,
                         output_device_index=out_device["index"],
                         frames_per_buffer=512, start=False)
        chk("stream open (not started)", True)
        chk("is_stopped before start", stream.is_stopped() is True)
        stream.start_stream()
        chk("is_active after start", stream.is_active() is True)
        chk("get_time", isinstance(stream.get_time(), float) and stream.get_time() >= 0)
        chk("get_cpu_load", isinstance(stream.get_cpu_load(), float))
        stream.stop_stream()
        chk("is_active after stop", stream.is_active() is False)
        chk("get_write_available", isinstance(stream.get_write_available(), int))
        stream.start_stream()
        stream.write(sine)
        stream.stop_stream()
        stream.close()
        chk("stream start/write/stop/close", True)
    except (IOError, OSError) as exc:
        skip("stream lifecycle", str(exc))
else:
    skip("stream lifecycle", "no output device")

section("5. terminate")
try:
    pa.terminate()
    chk("terminate", True)
    try:
        pa.get_host_api_count()
        chk("use after terminate raises", False)
    except IOError:
        chk("use after terminate raises", True)
    except Exception:
        chk("use after terminate raises", False)
except Exception as exc:
    chk("terminate", False, repr(exc))

print("\n===== %d PASS, %d FAIL, %d SKIP =====" % (PASS, FAIL, SKIP))
sys.exit(0 if FAIL == 0 else 1)
