"""
On-device verification for the cross-compiled opencv-python wheel.

Run after installing:
    pip install opencv_python-5.0.0.93-cp312-cp312-linux_<ABI>.whl

Usage:
    python Test_opencv.py [--quick]

Exit code 0 = everything required PASSed.
Requires: numpy at runtime.

Generated by RIMI
"""
import os
import sys
import tempfile

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


WORKDIR = None


def workdir():
    global WORKDIR
    if WORKDIR is None:
        candidates = [os.environ.get("TMPDIR") or "", tempfile.gettempdir(),
                      "/storage/emulated/0/Download", os.getcwd()]
        for base in candidates:
            if not base:
                continue
            try:
                d = os.path.join(base, "test_cv2_tmp")
                os.makedirs(d, exist_ok=True)
                with open(os.path.join(d, "_probe"), "w") as fh:
                    fh.write("ok")
                WORKDIR = d
                break
            except OSError:
                continue
        if WORKDIR is None:
            WORKDIR = "."
    return WORKDIR


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_cv2():
    import cv2
    print("    cv2", cv2.__version__)
    assert hasattr(cv2, "imread")
    assert hasattr(cv2, "cvtColor")
    assert hasattr(cv2, "GaussianBlur")


def cv2_build_info():
    import cv2
    info = cv2.getBuildInformation()
    assert "OpenCV" in info
    assert "Python" in info or "python" in info.lower()


# ---------------------------------------------------------------------------
# 2. numpy interop
# ---------------------------------------------------------------------------
def numpy_interop():
    import numpy as np
    import cv2
    arr = np.zeros((100, 100, 3), dtype=np.uint8)
    arr[25:75, 25:75] = [255, 255, 255]
    gray = cv2.cvtColor(arr, cv2.COLOR_BGR2GRAY)
    assert gray.shape == (100, 100)
    assert gray.dtype == np.uint8


def ndarray_conversion():
    import numpy as np
    import cv2
    mat = cv2.Mat(np.zeros((50, 50), dtype=np.uint8))
    assert mat is not None


# ---------------------------------------------------------------------------
# 3. image I/O
# ---------------------------------------------------------------------------
def imwrite_imread():
    import numpy as np
    import cv2
    img = np.zeros((100, 100, 3), dtype=np.uint8)
    img[25:75, 25:75] = [0, 0, 255]

    p = os.path.join(workdir(), "test.png")
    ok = cv2.imwrite(p, img)
    assert ok is True
    assert os.path.exists(p)

    loaded = cv2.imread(p)
    assert loaded is not None
    assert loaded.shape == (100, 100, 3)
    assert loaded[50, 50, 2] == 255  # red pixel


def imdecode_encode():
    import numpy as np
    import cv2
    img = np.zeros((50, 50, 3), dtype=np.uint8)
    _, buf = cv2.imencode(".png", img)
    assert buf is not None
    assert len(buf) > 0
    decoded = cv2.imdecode(buf, cv2.IMREAD_COLOR)
    assert decoded is not None
    assert decoded.shape == (50, 50, 3)


# ---------------------------------------------------------------------------
# 4. color conversion
# ---------------------------------------------------------------------------
def color_conversion():
    import numpy as np
    import cv2
    img = np.zeros((10, 10, 3), dtype=np.uint8)
    img[:] = [128, 64, 32]

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    assert gray.shape == (10, 10)

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    assert hsv.shape == (10, 10, 3)

    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    assert rgb[0, 0, 0] == 128  # R should be 128 (was B in BGR)

    rgba = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)
    assert rgba.shape == (10, 10, 4)


# ---------------------------------------------------------------------------
# 5. image processing
# ---------------------------------------------------------------------------
def gaussian_blur():
    import numpy as np
    import cv2
    img = np.random.randint(0, 255, (100, 100, 3), dtype=np.uint8)
    blurred = cv2.GaussianBlur(img, (5, 5), 1.0)
    assert blurred.shape == img.shape
    assert blurred.dtype == np.uint8


def resize():
    import numpy as np
    import cv2
    img = np.zeros((100, 200, 3), dtype=np.uint8)
    resized = cv2.resize(img, (50, 25))
    assert resized.shape == (25, 50, 3)


def threshold():
    import numpy as np
    import cv2
    img = np.random.randint(0, 255, (100, 100), dtype=np.uint8)
    _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
    assert thresh.shape == img.shape
    assert set(thresh.flatten()) <= {0, 255}


def canny_edges():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    img[40:60, 40:60] = 255
    edges = cv2.Canny(img, 50, 150)
    assert edges.shape == img.shape
    assert edges.dtype == np.uint8


# ---------------------------------------------------------------------------
# 6. drawing
# ---------------------------------------------------------------------------
def drawing():
    import numpy as np
    import cv2
    img = np.zeros((200, 200, 3), dtype=np.uint8)
    cv2.line(img, (0, 0), (200, 200), (255, 0, 0), 2)
    cv2.rectangle(img, (10, 10), (50, 50), (0, 255, 0), -1)
    cv2.circle(img, (100, 100), 30, (0, 0, 255), 2)
    cv2.putText(img, "Hi", (10, 180), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    assert img.sum() > 0


# ---------------------------------------------------------------------------
# 7. morphology
# ---------------------------------------------------------------------------
def morphology():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    img[25:75, 25:75] = 255
    kernel = np.ones((5, 5), np.uint8)
    eroded = cv2.erode(img, kernel, iterations=1)
    dilated = cv2.dilate(img, kernel, iterations=1)
    assert eroded.shape == img.shape
    assert dilated.shape == img.shape
    assert eroded.sum() <= img.sum()
    assert dilated.sum() >= img.sum()


# ---------------------------------------------------------------------------
# 8. contours
# ---------------------------------------------------------------------------
def find_contours():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    cv2.rectangle(img, (20, 20), (80, 80), 255, -1)
    contours, _ = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    assert len(contours) >= 1
    area = cv2.contourArea(contours[0])
    assert area > 0


# ---------------------------------------------------------------------------
# 9. histogram
# ---------------------------------------------------------------------------
def histogram_calc():
    import numpy as np
    import cv2
    img = np.random.randint(0, 255, (100, 100), dtype=np.uint8)
    hist = cv2.calcHist([img], [0], None, [256], [0, 256])
    assert hist.shape == (256, 1)
    assert hist.sum() == 100 * 100


# ---------------------------------------------------------------------------
# 10. video writer (no file I/O test, just API)
# ---------------------------------------------------------------------------
def video_api():
    import cv2
    assert hasattr(cv2, "VideoCapture")
    assert hasattr(cv2, "VideoWriter")
    assert hasattr(cv2, "VideoWriter_fourcc")


# ---------------------------------------------------------------------------
# 11. feature detection API check
# ---------------------------------------------------------------------------
def feature_api():
    import cv2
    assert hasattr(cv2, "goodFeaturesToTrack")
    assert hasattr(cv2, "cornerHarris")


def good_features():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    img[49:51, 49:51] = 255
    corners = cv2.goodFeaturesToTrack(img, 5, 0.01, 10)
    assert corners is not None
    assert len(corners) >= 1


# ---------------------------------------------------------------------------
# 12. template matching
# ---------------------------------------------------------------------------
def template_matching():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    img[40:60, 40:60] = 200
    template = img[45:55, 45:55].copy()
    result = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
    assert result.shape == (41, 41)
    _, max_val, _, max_loc = cv2.minMaxLoc(result)
    assert max_val > 0.9


# ---------------------------------------------------------------------------
# 13. distance transform / watershed
# ---------------------------------------------------------------------------
def distance_transform():
    import numpy as np
    import cv2
    img = np.zeros((100, 100), dtype=np.uint8)
    cv2.circle(img, (50, 50), 20, 255, -1)
    dist = cv2.distanceTransform(img, cv2.DIST_L2, 5)
    assert dist.shape == (100, 100)
    assert dist[50, 50] > 0


# ---------------------------------------------------------------------------
# 14. min/max location
# ---------------------------------------------------------------------------
def min_max_loc():
    import numpy as np
    import cv2
    img = np.zeros((50, 50), dtype=np.uint8)
    img[25, 25] = 255
    _, max_val, _, max_loc = cv2.minMaxLoc(img)
    assert max_val == 255
    assert max_loc == (25, 25)


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. cv2 import / version")
    test("import cv2", import_cv2)
    test("build info", cv2_build_info)

    section("2. numpy interop")
    test("cvtColor numpy array", numpy_interop)
    test("ndarray conversion", ndarray_conversion)

    section("3. image I/O")
    test("imwrite + imread", imwrite_imread)
    test("imencode + imdecode", imdecode_encode)

    section("4. color conversion")
    test("BGR to GRAY/HSV/RGB/BGRA", color_conversion)

    section("5. image processing")
    test("GaussianBlur", gaussian_blur)
    test("resize", resize)
    test("threshold", threshold)
    test("Canny edges", canny_edges)

    section("6. drawing")
    test("line/rect/circle/text", drawing)

    section("7. morphology")
    test("erode/dilate", morphology)

    section("8. contours")
    test("findContours + contourArea", find_contours)

    section("9. histogram")
    test("calcHist", histogram_calc)

    section("10. video API")
    test("video API check", video_api)

    section("11. feature detection")
    test("feature API check", feature_api)
    test("goodFeaturesToTrack", good_features)

    section("12. template matching")
    test("matchTemplate + minMaxLoc", template_matching)

    section("13. distance transform")
    test("distanceTransform", distance_transform)

    section("14. min/max location")
    test("minMaxLoc", min_max_loc)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
