"""
On-device verification for the cross-compiled greenlet wheel.

Run after installing:
    pip install greenlet-3.2.3-cp312-cp312-linux_<ABI>.whl

Usage:
    python Test_greenlet.py [--quick]

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_greenlet():
    import greenlet
    print("    greenlet", greenlet.__version__)
    assert hasattr(greenlet, "greenlet")


def has_c_extension():
    import greenlet
    g = greenlet.greenlet(lambda: None)
    assert g.gr_frame is None or g.gr_frame is not None


# ---------------------------------------------------------------------------
# 2. basic greenlet creation
# ---------------------------------------------------------------------------
def create_greenlet():
    import greenlet
    result = []
    def worker():
        result.append("hello")

    g = greenlet.greenlet(worker)
    g.switch()
    assert result == ["hello"]


def switch_back():
    import greenlet
    result = []
    def parent():
        result.append("parent")
        g2.switch()
        result.append("parent_resumed")

    def child():
        result.append("child")
        parent_greenlet.switch()

    parent_greenlet = greenlet.greenlet(parent)
    g2 = greenlet.greenlet(child)
    parent_greenlet.switch()
    assert "parent" in result
    assert "child" in result


# ---------------------------------------------------------------------------
# 3. send / throw
# ---------------------------------------------------------------------------
def send_value():
    import greenlet
    received = []
    def worker():
        val = greenlet.getcurrent().parent.switch()
        received.append(val)
        val2 = greenlet.getcurrent().parent.switch()
        received.append(val2)

    g = greenlet.greenlet(worker)
    g.switch()
    g.switch(42)
    g.switch(99)
    assert received == [42, 99]


def throw_exception():
    import greenlet
    caught = []
    def worker():
        try:
            greenlet.getcurrent().parent.switch()
        except ValueError as e:
            caught.append(str(e))

    g = greenlet.greenlet(worker)
    g.switch()
    g.throw(ValueError, "test_error")
    assert caught == ["test_error"]


# ---------------------------------------------------------------------------
# 4. getcurrent / parent
# ---------------------------------------------------------------------------
def getcurrent():
    import greenlet
    me = greenlet.getcurrent()
    assert me is not None
    assert isinstance(me, greenlet.greenlet)


def parent_access():
    import greenlet
    main = greenlet.getcurrent()
    result = []
    def child():
        result.append(greenlet.getcurrent().parent is main)

    g = greenlet.greenlet(child)
    g.switch()
    assert result == [True]


# ---------------------------------------------------------------------------
# 5. dead state
# ---------------------------------------------------------------------------
def dead_greenlet():
    import greenlet
    result = []
    def worker():
        pass

    g = greenlet.greenlet(worker)
    assert g.dead is False
    g.switch()
    assert g.dead is True


def dead_cannot_switch():
    import greenlet
    def worker():
        pass

    g = greenlet.greenlet(worker)
    g.switch()
    assert g.dead is True
    result = g.switch()
    assert result == ()


# ---------------------------------------------------------------------------
# 6. multiple greenlets round-robin
# ---------------------------------------------------------------------------
def round_robin():
    import greenlet
    order = []
    def make_worker(name):
        def worker():
            order.append(name)
            parent = greenlet.getcurrent().parent
            parent.switch()
            order.append(name + "_resumed")
        return worker

    g1 = greenlet.greenlet(make_worker("A"))
    g2 = greenlet.greenlet(make_worker("B"))

    g1.switch()
    g2.switch()
    g1.switch()
    g2.switch()

    assert order == ["A", "B", "A_resumed", "B_resumed"]


# ---------------------------------------------------------------------------
# 7. greenlet local state
# ---------------------------------------------------------------------------
def greenlet_locals():
    import greenlet
    result = []
    def worker():
        greenlet.getcurrent().my_state = "stored"
        greenlet.getcurrent().parent.switch()
        result.append(greenlet.getcurrent().my_state)

    g = greenlet.greenlet(worker)
    g.switch()
    g.switch()
    assert result == ["stored"]


# ---------------------------------------------------------------------------
# 8. exception propagation
# ---------------------------------------------------------------------------
def exception_propagation():
    import greenlet
    def child():
        raise RuntimeError("boom")

    g = greenlet.greenlet(child)
    try:
        g.switch()
        assert False, "should have raised"
    except RuntimeError as e:
        assert str(e) == "boom"


# ---------------------------------------------------------------------------
# 9. stack_size / direct C extension test
# ---------------------------------------------------------------------------
def c_extension_alive():
    import greenlet
    g = greenlet.greenlet(lambda: None)
    g.switch()
    assert g.dead
    assert greenlet.getcurrent() is not None


def greenlet_type():
    import greenlet
    g = greenlet.greenlet(lambda: None)
    assert type(g).__name__ == "greenlet"
    assert repr(g) is not None


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. greenlet import / version")
    test("import greenlet", import_greenlet)
    test("C extension alive", has_c_extension)

    section("2. basic greenlet creation")
    test("create and switch", create_greenlet)
    test("switch back and forth", switch_back)

    section("3. send / throw")
    test("send values", send_value)
    test("throw exceptions", throw_exception)

    section("4. getcurrent / parent")
    test("getcurrent", getcurrent)
    test("parent access", parent_access)

    section("5. dead state")
    test("dead flag", dead_greenlet)
    test("switch on dead raises", dead_cannot_switch)

    section("6. multiple greenlets round-robin")
    test("round-robin scheduling", round_robin)

    section("7. greenlet local state")
    test("greenlet attribute storage", greenlet_locals)

    section("8. exception propagation")
    test("exception propagates to parent", exception_propagation)

    section("9. C extension sanity")
    test("C extension operational", c_extension_alive)
    test("greenlet type / repr", greenlet_type)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
