"""
On-device verification for the cross-compiled brotli 1.2.0 wheel.

Run after installing:
    pip install brotli-1.2.0-cp312-cp312-android_24_<ABI>.whl

Usage:
    python Test_Brotli.py [--quick]

Exit code 0 = everything required PASSed.

NOTE: the wheel ships the native accelerator as _brotli.cpython-312.so and a
thin pure-python wrapper brotli.py. brotli.compress()/decompress() MUST hit
the compiled backend, not a pure-python fallback (there is no fallback - if
the .so is missing, `import brotli` fails entirely).

Generated by RIMI
"""
import sys
import os
import traceback

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        traceback.print_exc()


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import surface + version
# ---------------------------------------------------------------------------
def imports_correct():
    import brotli
    assert brotli.__version__ == "1.2.0", brotli.__version__
    assert hasattr(brotli, "compress")
    assert hasattr(brotli, "decompress")
    assert hasattr(brotli, "Compressor")
    assert hasattr(brotli, "Decompressor")
    assert hasattr(brotli, "error")
    assert brotli.MODE_GENERIC == 0
    assert brotli.MODE_TEXT == 1
    assert brotli.MODE_FONT == 2


def native_backend_loaded():
    # The C accelerator must exist as a real .so next to brotli.py.
    import brotli
    import importlib.util
    pkg_dir = os.path.dirname(brotli.__file__)
    found = False
    for name in os.listdir(pkg_dir):
        if name.startswith("_brotli") and name.endswith((".so", ".pyd")):
            found = True
    assert found, "no _brotli native extension in %s" % pkg_dir
    spec = importlib.util.find_spec("_brotli")
    assert spec is not None and spec.origin and spec.origin.endswith((".so", ".pyd")), \
        "_brotli did not resolve to a compiled extension"


# ---------------------------------------------------------------------------
# 2. roundtrip correctness (known values)
# ---------------------------------------------------------------------------
def simple_roundtrip():
    import brotli
    data = b"hello brotli 12345" * 1000
    c = brotli.compress(data)
    assert isinstance(c, bytes)
    assert len(c) < len(data), "compressed should be smaller for repetitive data"
    assert brotli.decompress(c) == data


def known_vector():
    # deterministic: same input + same params -> identical output on every ABI
    import brotli
    data = b"PySTB" * 64
    c = brotli.compress(data, quality=11, mode=brotli.MODE_TEXT)
    assert brotli.decompress(c) == data
    # vector is stable across builds/ABIs
    assert c == brotli.compress(data, quality=11, mode=brotli.MODE_TEXT), \
        "brotli output not deterministic"


def binary_roundtrip():
    import brotli
    import os
    rnd = bytes((i * 31 + 7) & 0xFF for i in range(4096))
    c = brotli.compress(rnd, quality=5)
    assert brotli.decompress(c) == rnd


def quality_range():
    import brotli
    data = b"quality test payload" * 200
    for q in range(0, 12):
        c = brotli.compress(data, quality=q)
        assert brotli.decompress(c) == data, "quality %d roundtrip failed" % q


def empty_and_tiny():
    import brotli
    assert brotli.decompress(brotli.compress(b"")) == b""
    assert brotli.decompress(brotli.compress(b"a")) == b"a"
    assert brotli.decompress(brotli.compress(b"ab" * 2)) == b"abab"


def modes_roundtrip():
    import brotli
    data = b"<html><body>font test data \xef\xbb\xbf</body></html>" * 50
    for mode in (brotli.MODE_GENERIC, brotli.MODE_TEXT, brotli.MODE_FONT):
        c = brotli.compress(data, mode=mode)
        assert brotli.decompress(c) == data, "mode %d roundtrip failed" % mode


def streaming_compressor():
    import brotli
    comp = brotli.Compressor(quality=9)
    chunks = []
    for i in range(100):
        chunks.append(comp.process(b"stream block %d " % i))
    tail = comp.finish()
    data = b"".join(chunks) + tail
    assert brotli.decompress(data) == b"".join(b"stream block %d " % i for i in range(100))


def streaming_decompressor():
    import brotli
    src = b"The quick brown fox jumps over the lazy dog. " * 300
    c = brotli.compress(src)
    dec = brotli.Decompressor()
    out = bytearray()
    step = 7
    for i in range(0, len(c), step):
        out += dec.process(c[i:i + step])
    assert bytes(out) == src
    assert dec.is_finished()


# ---------------------------------------------------------------------------
# 3. error handling
# ---------------------------------------------------------------------------
def bad_input_raises():
    import brotli
    try:
        brotli.decompress(b"this is not valid brotli data at all!!!")
    except brotli.error:
        return
    raise AssertionError("corrupt stream did not raise brotli.error")


def type_errors():
    import brotli
    for bad in (None, "str", 123, 1.5, [1, 2, 3]):
        try:
            brotli.compress(bad)
        except (TypeError, ValueError):
            pass
        else:
            raise AssertionError("compress(%r) did not raise" % (bad,))


def main():
    quick = "--quick" in sys.argv
    section("1. import surface")
    test("imports brotli 1.2.0", imports_correct)
    test("native _brotli backend loaded", native_backend_loaded)

    section("2. roundtrip correctness")
    test("simple roundtrip", simple_roundtrip)
    test("known vector deterministic", known_vector)
    test("binary roundtrip", binary_roundtrip)
    test("all qualities 0-11", quality_range)
    test("empty + tiny inputs", empty_and_tiny)
    test("all modes roundtrip", modes_roundtrip)
    test("streaming Compressor", streaming_compressor)
    test("streaming Decompressor", streaming_decompressor)

    section("3. error handling")
    test("corrupt stream raises brotli.error", bad_input_raises)
    test("bad types raise TypeError", type_errors)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
