#!/usr/bin/env python3
"""
Test_pynacl.py - on-device validation for the PyNaCl wheel.

Exercises the CFFI-backed libsodium crypto through the public API.
Exit code 0 = all tests passed.

Generated by RIMI
"""
import os
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


# ---------------------------------------------------------------------------
# 1. import + versions
# ---------------------------------------------------------------------------
def test_import():
    import nacl
    check(hasattr(nacl, "__version__"), "no __version__")
    print("  nacl version:", nacl.__version__)


def test_import_bindings():
    import nacl._sodium as _sodium
    check(_sodium is not None, "no _sodium")


def test_version_string():
    import nacl.utils
    import nacl._sodium as _sodium
    # libsodium version
    v = _sodium.sodium_version_string()
    check(v is not None, "no version string")
    print("  libsodium version:", v)


# ---------------------------------------------------------------------------
# 2. Random bytes
# ---------------------------------------------------------------------------
def test_random_bytes():
    from nacl.utils import random
    r1 = random(32)
    r2 = random(32)
    check(len(r1) == 32, "wrong length")
    check(r1 != r2, "random bytes identical")
    print("  random(32):", r1.hex()[:16] + "...")


def test_random_exception():
    from nacl.utils import random
    try:
        random(0)
        check(False, "should raise for length=0")
    except Exception:
        pass
    print("  random(0) raises: OK")


# ---------------------------------------------------------------------------
# 3. SecretBox (symmetric encryption)
# ---------------------------------------------------------------------------
def test_secretbox_encrypt_decrypt():
    from nacl.secret import SecretBox
    from nacl.utils import random

    key = random(SecretBox.KEY_SIZE)
    box = SecretBox(key)

    plaintext = b"hello pynacl secret box " * 100
    ciphertext = box.encrypt(plaintext)
    check(len(ciphertext) > len(plaintext), "ciphertext not longer")

    decrypted = box.decrypt(ciphertext)
    check(decrypted == plaintext, "decrypt mismatch")
    print("  SecretBox: encrypt %d -> %d bytes, decrypt OK" % (len(plaintext), len(ciphertext)))


def test_secretbox_wrong_key():
    from nacl.secret import SecretBox
    from nacl.utils import random

    k1 = random(SecretBox.KEY_SIZE)
    k2 = random(SecretBox.KEY_SIZE)
    box1 = SecretBox(k1)
    box2 = SecretBox(k2)

    ct = box1.encrypt(b"secret")
    try:
        box2.decrypt(ct)
        check(False, "should fail with wrong key")
    except Exception:
        pass
    print("  SecretBox wrong key: raises OK")


# ---------------------------------------------------------------------------
# 4. PublicKey / PrivateKey / SigningKey
# ---------------------------------------------------------------------------
def test_key_generation():
    from nacl.signing import SigningKey

    sk = SigningKey.generate()
    vk = sk.verify_key
    check(len(bytes(sk)) == 32, "sk size")
    check(len(bytes(vk)) == 32, "vk size")
    print("  SigningKey.generate: OK")


def test_sign_verify():
    from nacl.signing import SigningKey

    sk = SigningKey.generate()
    msg = b"message to sign"
    signed = sk.sign(msg)

    check(len(signed.signature) == 64, "sig size")
    check(signed.message == msg, "message mismatch")

    # Verify
    vk = sk.verify_key
    verified = vk.verify(signed)
    check(verified == msg, "verify mismatch")
    print("  sign + verify: OK")


def test_verify_bad_signature():
    from nacl.signing import SigningKey

    sk1 = SigningKey.generate()
    sk2 = SigningKey.generate()

    signed = sk1.sign(b"msg")
    try:
        sk2.verify_key.verify(signed)
        check(False, "should fail")
    except Exception:
        pass
    print("  verify bad signature: raises OK")


# ---------------------------------------------------------------------------
# 5. Box (public-key encryption)
# ---------------------------------------------------------------------------
def test_box_encrypt_decrypt():
    from nacl.public import PrivateKey, Box

    sk1 = PrivateKey.generate()
    sk2 = PrivateKey.generate()

    box1 = Box(sk1, sk2.public_key)
    box2 = Box(sk2, sk1.public_key)

    plaintext = b"hello public key box " * 50
    ct = box1.encrypt(plaintext)
    pt = box2.decrypt(ct)
    check(pt == plaintext, "decrypt mismatch")
    print("  Box encrypt/decrypt: OK (%d bytes)" % len(plaintext))


def test_box_shared_key():
    from nacl.public import PrivateKey, Box

    sk1 = PrivateKey.generate()
    sk2 = PrivateKey.generate()

    box1 = Box(sk1, sk2.public_key)
    box2 = Box(sk2, sk1.public_key)

    check(box1.shared_key() == box2.shared_key(), "shared keys differ")
    print("  Box shared_key: OK")


# ---------------------------------------------------------------------------
# 6. Hashing
# ---------------------------------------------------------------------------
def test_hash_sha256():
    from nacl.hash import sha256

    h = sha256(b"hello world")
    check(isinstance(h, bytes), "not bytes")
    check(len(h) == 32 * 2, "wrong hex length")  # hex encoded
    print("  sha256:", h.hex()[:16] + "...")


def test_hash_sha512():
    from nacl.hash import sha512

    h = sha512(b"hello world")
    check(len(h) == 64 * 2, "wrong hex length")
    print("  sha512:", h.hex()[:16] + "...")


def test_hash_blake2b():
    from nacl.hash import blake2b

    h = blake2b(b"hello world", digest_size=32)
    check(len(h) == 32 * 2, "wrong hex length")
    print("  blake2b:", h.hex()[:16] + "...")


# ---------------------------------------------------------------------------
# 7. encoding
# ---------------------------------------------------------------------------
def test_encoding_hex():
    from nacl.encoding import HexEncoder

    data = b"\xde\xad\xbe\xef"
    enc = HexEncoder.encode(data)
    check(enc == b"deadbeef", "hex encode")
    dec = HexEncoder.decode(enc)
    check(dec == data, "hex decode")
    print("  HexEncoder: OK")


def test_encoding_base64():
    from nacl.encoding import Base64Encoder

    data = b"hello world"
    enc = Base64Encoder.encode(data)
    dec = Base64Encoder.decode(enc)
    check(dec == data, "base64 roundtrip")
    print("  Base64Encoder: OK")


# ---------------------------------------------------------------------------
# 8. sign/verify with message extraction
# ---------------------------------------------------------------------------
def test_signed_message():
    from nacl.signing import SigningKey

    sk = SigningKey.generate()
    msg = b"test message"
    signed = sk.sign(msg)

    # signed.signature is 64 bytes
    check(len(signed.signature) == 64, "sig size")
    # signed.message is the original message
    check(signed.message == msg, "message extraction")
    print("  SignedMessage extraction: OK")


# ---------------------------------------------------------------------------
# 9. secretbox with nonce
# ---------------------------------------------------------------------------
def test_secretbox_deterministic():
    from nacl.secret import SecretBox
    from nacl.utils import nonce as make_nonce

    key = b"\x00" * SecretBox.KEY_SIZE
    box = SecretBox(key)

    nonce1 = make_nonce(box)
    nonce2 = make_nonce(box)
    check(nonce1 != nonce2, "nonces identical")

    ct1 = box.encrypt(b"same plaintext", nonce1)
    ct2 = box.encrypt(b"same plaintext", nonce2)
    check(ct1 != ct2, "ciphertexts identical with different nonces")
    print("  SecretBox nonce uniqueness: OK")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    section("1. import + versions")
    test("import nacl", test_import)
    test("import _sodium bindings", test_import_bindings)
    test("libsodium version", test_version_string)

    section("2. random bytes")
    test("random(32)", test_random_bytes)
    test("random(0) raises", test_random_exception)

    section("3. SecretBox (symmetric)")
    test("encrypt + decrypt", test_secretbox_encrypt_decrypt)
    test("wrong key raises", test_secretbox_wrong_key)

    section("4. signing keys")
    test("key generation", test_key_generation)
    test("sign + verify", test_sign_verify)
    test("bad signature raises", test_verify_bad_signature)

    section("5. Box (public-key)")
    test("encrypt + decrypt", test_box_encrypt_decrypt)
    test("shared_key", test_box_shared_key)

    section("6. hashing")
    test("sha256", test_hash_sha256)
    test("sha512", test_hash_sha512)
    test("blake2b", test_hash_blake2b)

    section("7. encoding")
    test("HexEncoder", test_encoding_hex)
    test("Base64Encoder", test_encoding_base64)

    section("8. signed messages")
    test("SignedMessage extraction", test_signed_message)

    section("9. nonce generation")
    test("nonce uniqueness", test_secretbox_deterministic)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
