"""
Test script for scipy on Android Python STB
Device test: validates import, 129 submodules, core functionality.

Generated by RIMI
"""

import sys
import time
import platform

RESULTS = []

def section(name):
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

def test(name, func):
    global RESULTS
    try:
        result = func()
        RESULTS.append((name, "PASS", result if result else ""))
        print(f"  [PASS] {name}")
    except Exception as e:
        RESULTS.append((name, "FAIL", str(e)))
        print(f"  [FAIL] {name}: {e}")

def test():
    section("Environment")
    print(f"  Python: {sys.version}")
    print(f"  Platform: {platform.platform()}")
    print(f"  Arch: {platform.machine()}")

    # --- Core Import ---
    section("Core Import")
    test("import scipy", lambda: __import__("scipy"))
    test("scipy.__version__", lambda: __import__("scipy").__version__)
    test("scipy.show_config()", lambda: __import__("scipy").show_config())

    # --- Submodules (129 total) ---
    section("Submodules (~129)")
    submodules = [
        # Core
        "__init__", "cluster", "cluster.hierarchy", "cluster.vq",
        "constants", "constants.constants",
        # FFT
        "fft", "fft._pocketfft", "fft._helper",
        # Integrate
        "integrate", "integrate._ode", "integrate.quadpack",
        "integrate.lsoda", "integrate.vode",
        # Interpolate
        "interpolate", "interpolate._bspl", "interpolate._cubic",
        "interpolate._interpnd", "interpolate._ppoly",
        "interpolate.fitpack", "interpolate.fitpack2",
        # IO
        "io", "io._fortran", "io._netcdf", "io.matlab",
        # Linalg
        "linalg", "linalg._basic", "linalg._decomp",
        "linalg._decomp_cholesky", "linalg._decomp_lu",
        "linalg._decomp_qr", "linalg._decomp_schur",
        "linalg._decomp_svd", "linalg._expm",
        "linalg._flinalg_py", "linalg._matfuncs",
        "linalg._special_matrices", "linalg.lapack",
        "linalg.blas", "linalg.cblas", "linalg.clapack",
        # NDimage
        "ndimage", "ndimage._interpolation", "ndimage._ni_support",
        # Optimize
        "optimize", "optimize._cobyla", "optimize._constraints",
        "optimize._differentiable_functions", "optimize._differentialevolution",
        "optimize._dispatch", "optimize._dual_annealing",
        "optimize._hessian_update_strategy", "optimize._linprog",
        "optimize._linprog_doc", "optimize._lsq",
        "optimize._minimize", "optimize._minpack_py",
        "optimize._nnls", "optimize._nonlin",
        "optimize._qap", "optimize._remove_redundancy",
        "optimize._root", "optimize._shgo",
        "optimize._trustregion", "optimize._trustregion_constr",
        "optimize._basinhopping", "optimize.linesearch",
        "optimize.minpack", "optimize.zeros",
        # Signal
        "signal", "signal._arraytools", "signal._bsplines",
        "signal._cubic", "signal._discrete_utils",
        "signal._filter_design", "signal._fir_filter_design",
        "signal._lti_conversion", "signal._ltisys",
        "signal._peak_finding", "signal._polyutils",
        "signal._savitzky_golay", "signal._short_time_fft",
        "signal._signaltools", "signal._sosfilt",
        "signal._spectral", "signal._spectral_py",
        "signal._waveforms", "signal._wavelets",
        "signal.cont2discrete", "signal.filter_design",
        "signal.fir_filter_design", "signal.lti_conversion",
        "signal.signaltools", "signal.waveforms",
        "signal.wavelets", "signal.windows",
        # Sparse
        "sparse", "sparse._compressed", "sparse._coo",
        "sparse._csc", "sparse._csr", "sparse._dia",
        "sparse._dok", "sparse._extract", "sparse._lil",
        "sparse._matrix", "sparse._sparray", "sparse.csgraph",
        "sparse.linalg",
        # Spatial
        "spatial", "spatial._ckdtree", "spatial._distance_pybind",
        "spatial._qhull", "spatial.distance",
        # Special
        "special", "special._logsumexp", "special._sf_error",
        "special._specfun", "special._support_alternative_backends",
        "special._ufuncs", "special._ellip_harm_2",
        "special.add_newdoc", "special.basic",
        "special.orthogonal", "special.sf_error",
        # Stats
        "stats", "stats._levy_stable", "stats._multivariate",
        "stats._boost", "stats._binned_statistic",
        "stats._bootstrap", "stats._censored_data",
        "stats._correlation", "stats._crosstab",
        "stats._discrete_distns", "stats._distn_infrastructure",
        "stats._distributions", "stats._fit",
        "stats._hypotests", "stats._kde",
        "stats._mannwhitneyu", "stats._morestats",
        "stats._mstats_basic", "stats._mstats_extras",
        "stats._multicomp", "stats._odds_ratio",
        "stats._probability_distribution", "stats._qmc",
        "stats._relative_risk", "stats._resampling",
        "stats._rv_continous", "stats._stats_py",
        "stats._survival", "stats._tukeylambda_stats",
        "stats._variation", "stats._warnings_stats",
        "stats.biasedurn", "stats.contingency",
        "stats.distributions", "stats.kde", "stats.morestats",
        "stats.mstats", "stats.mstats_basic", "stats.mstats_extras",
        "stats.qmc", "stats.rv_discrete", "stats.stats",
        # Special remaining
        "special.spence", "special.zeta",
        # Misc
        "dataset", "fft", "fftpack",
    ]

    imported = 0
    failed_mods = []
    for mod in submodules:
        try:
            __import__(f"scipy.{mod}", fromlist=["_"])
            imported += 1
        except Exception as e:
            failed_mods.append((mod, str(e)))

    print(f"\n  Submodules imported: {imported}/{len(submodules)}")
    if failed_mods:
        print(f"  Failed ({len(failed_mods)}):")
        for m, err in failed_mods[:10]:
            print(f"    - {m}: {err[:80]}")
    test(f"imported {imported}/{len(submodules)} submodules", lambda: imported)

    # --- Core Functionality ---
    section("Core Functionality")
    test("numpy available", lambda: __import__("numpy"))

    def test_linalg_solve():
        import numpy as np
        from scipy import linalg
        A = np.array([[3, 1], [1, 2]])
        b = np.array([9, 8])
        x = linalg.solve(A, b)
        assert np.allclose(A @ x, b), f"solution incorrect: {x}"
        return f"solution={x}"

    test("linalg.solve", test_linalg_solve)

    def test_linalg_det():
        import numpy as np
        from scipy import linalg
        A = np.array([[1, 2], [3, 4]])
        det = linalg.det(A)
        assert abs(det - (-2.0)) < 1e-10
        return f"det={det}"

    test("linalg.det", test_linalg_det)

    def test_linalg_inv():
        import numpy as np
        from scipy import linalg
        A = np.array([[1, 2], [3, 4]])
        Ainv = linalg.inv(A)
        product = A @ Ainv
        assert np.allclose(product, np.eye(2)), "inverse check failed"
        return f"inverse OK"

    test("linalg.inv", test_linalg_inv)

    def test_linalg_svd():
        import numpy as np
        from scipy import linalg
        A = np.random.rand(10, 8)
        U, S, Vh = linalg.svd(A, full_matrices=False)
        assert U.shape[0] == 10 and S.shape[0] == 8
        return f"U={U.shape}, S={S.shape}, Vh={Vh.shape}"

    test("linalg.svd", test_linalg_svd)

    def test_optimize_minimize():
        import numpy as np
        from scipy.optimize import minimize
        def rosen(x):
            return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)
        x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
        result = minimize(rosen, x0, method='Nelder-Mead')
        assert result.fun < 1.0, f"Rosenbrock minimum not found: {result.fun}"
        return f"min={result.fun:.6f}"

    test("optimize.minimize (Rosenbrock)", test_optimize_minimize)

    def test_optimize_curve_fit():
        import numpy as np
        from scipy.optimize import curve_fit
        def func(x, a, b):
            return a * x + b
        xdata = np.array([1, 2, 3, 4, 5])
        ydata = np.array([2.1, 3.9, 6.2, 7.8, 10.1])
        popt, pcov = curve_fit(func, xdata, ydata)
        assert abs(popt[0] - 2.0) < 0.5, f"slope wrong: {popt[0]}"
        return f"a={popt[0]:.3f}, b={popt[1]:.3f}"

    test("optimize.curve_fit", test_optimize_curve_fit)

    def test_signal_wiener():
        import numpy as np
        from scipy.signal import wiener
        np.random.seed(42)
        signal = np.sin(np.linspace(0, 2*np.pi, 100))
        noisy = signal + np.random.randn(100) * 0.5
        filtered = wiener(noisy, 5)
        assert filtered.shape == noisy.shape
        return f"wiener filter applied, shape={filtered.shape}"

    test("signal.wiener", test_signal_wiener)

    def test_signal_butter():
        import numpy as np
        from scipy.signal import butter, lfilter
        b, a = butter(4, 0.2, btype='low')
        t = np.linspace(0, 1, 500)
        signal = np.sin(2*np.pi*5*t) + np.sin(2*np.pi*50*t)
        filtered = lfilter(b, a, signal)
        assert filtered.shape == signal.shape
        return f"Butterworth lowpass, order=4"

    test("signal.butter + lfilter", test_signal_butter)

    def test_fft():
        import numpy as np
        from scipy import fft
        x = np.array([1.0, 2.0, 3.0, 4.0])
        y = fft.fft(x)
        assert y.shape == (4,)
        assert np.allclose(np.abs(y[0]), 10.0)
        return f"fft OK, DC={np.abs(y[0]):.1f}"

    test("fft.fft", test_fft)

    def test_fft_rfft():
        import numpy as np
        from scipy.fft import rfft, irfft
        x = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
        y = rfft(x)
        x_back = irfft(y, n=len(x))
        assert np.allclose(x, x_back), "rfft/irfft roundtrip failed"
        return f"rfft/irfft roundtrip OK, n={len(x)}"

    test("fft.rfft / irfft", test_fft_rfft)

    def test_integrate_quad():
        import numpy as np
        from scipy.integrate import quad
        result, error = quad(lambda x: x**2, 0, 1)
        assert abs(result - 1/3) < 1e-10
        return f"integral={result:.6f}, error={error:.2e}"

    test("integrate.quad (x^2)", test_integrate_quad)

    def test_interpolate():
        import numpy as np
        from scipy.interpolate import interp1d
        x = np.array([0, 1, 2, 3, 4])
        y = np.array([0, 1, 4, 9, 16])
        f = interp1d(x, y, kind='cubic')
        val = f(2.5)
        assert 5.0 < val < 8.0, f"interpolation wrong: {val}"
        return f"f(2.5)={val:.3f}"

    test("interpolate.interp1d", test_interpolate)

    def test_stats_mean():
        import numpy as np
        from scipy.stats import trim_mean
        data = np.array([1, 2, 3, 4, 5, 100])
        mean = trim_mean(data, 0.1)
        assert 2.0 < mean < 5.0
        return f"trim_mean={mean:.3f}"

    test("stats.trim_mean", test_stats_mean)

    def test_stats_ttest():
        import numpy as np
        from scipy.stats import ttest_ind
        np.random.seed(42)
        a = np.random.randn(100) + 0.5
        b = np.random.randn(100)
        stat, pval = ttest_ind(a, b)
        assert stat > 0
        return f"t-stat={stat:.3f}, p={pval:.4f}"

    test("stats.ttest_ind", test_stats_ttest)

    def test_ndimage():
        import numpy as np
        from scipy import ndimage
        data = np.array([[1, 0, 0],
                         [0, 1, 0],
                         [0, 0, 1]], dtype=np.float64)
        labeled, num_features = ndimage.label(data)
        assert num_features == 3
        return f"labeled {num_features} features"

    test("ndimage.label", test_ndimage)

    def test_sparse():
        import numpy as np
        from scipy import sparse
        A = sparse.random(100, 100, density=0.1, format='csr')
        assert A.shape == (100, 100)
        assert A.nnz > 0
        return f"sparse {A.shape}, nnz={A.nnz}"

    test("sparse.random", test_sparse)

    def test_spatial_distance():
        import numpy as np
        from scipy.spatial.distance import pdist, squareform
        points = np.random.rand(5, 3)
        dists = pdist(points, metric='euclidean')
        square = squareform(dists)
        assert square.shape == (5, 5)
        return f"pdist euclidean, {len(dists)} pairs"

    test("spatial.distance.pdist", test_spatial_distance)

    def test_special():
        from scipy.special import gamma, factorial
        g = gamma(5)
        assert abs(g - 24.0) < 1e-10
        f = factorial(5)
        assert f == 120
        return f"gamma(5)={g:.1f}, 5!={f}"

    test("special.gamma + factorial", test_special)

    # --- Summary ---
    section("SUMMARY")
    passed = sum(1 for _, status, _ in RESULTS if status == "PASS")
    failed = sum(1 for _, status, _ in RESULTS if status == "FAIL")
    total = len(RESULTS)
    print(f"  Total: {total} | Passed: {passed} | Failed: {failed}")
    if failed > 0:
        print(f"\n  Failed tests:")
        for name, status, msg in RESULTS:
            if status == "FAIL":
                print(f"    - {name}: {msg}")
    print(f"\n  {'ALL TESTS PASSED' if failed == 0 else 'SOME TESTS FAILED'}")
    return failed == 0


if __name__ == "__main__":
    ok = test()
    sys.exit(0 if ok else 1)
