"""
Test_RSA.py - RSA Test Suite for PythonSTB (Android)
Generated by RIMI
"""
import sys

PASS = 0
FAIL = 0
SKIP = 0
RESULTS = []

def test(name, func):
    global PASS, FAIL, SKIP
    try:
        result = func()
        if result is not False:
            PASS += 1
            RESULTS.append(("PASS", name))
        elif result == "SKIP":
            SKIP += 1
            RESULTS.append(("SKIP", name))
        else:
            FAIL += 1
            RESULTS.append(("FAIL", name))
    except Exception as e:
        FAIL += 1
        RESULTS.append(("FAIL", f"{name} -> {type(e).__name__}: {e}"))

print("=" * 60)
print(" RSA TEST SUITE")
print(" PythonSTB - Android ARM64/x86_64")
print("=" * 60)
print()

# --- Core Imports ---
test("rsa import", lambda: __import__("rsa"))
test("rsa.newkeys", lambda: __import__("rsa").newkeys)
test("rsa.encrypt", lambda: __import__("rsa").encrypt)
test("rsa.decrypt", lambda: __import__("rsa").decrypt)
test("rsa.sign", lambda: __import__("rsa").sign)
test("rsa.verify", lambda: __import__("rsa").verify)
test("rsa.PublicKey", lambda: __import__("rsa").PublicKey)
test("rsa.PrivateKey", lambda: __import__("rsa").PrivateKey)

# --- Version ---
def test_version():
    import rsa
    print(f"    RSA version: {rsa.__version__}")
    return True
test("version info", test_version)

# --- Key Generation ---
def test_keygen():
    import rsa
    (pubkey, privkey) = rsa.newkeys(512)
    assert pubkey is not None
    assert privkey is not None
    print(f"    Generated 512-bit keypair")
    return True
test("key generation (512-bit)", test_keygen)

# --- 1024-bit Key ---
def test_keygen1024():
    import rsa
    (pubkey, privkey) = rsa.newkeys(1024)
    assert pubkey is not None
    assert privkey is not None
    print(f"    Generated 1024-bit keypair")
    return True
test("key generation (1024-bit)", test_keygen1024)

# --- Encrypt/Decrypt (512-bit) ---
def test_encrypt_decrypt():
    import rsa
    (pubkey, privkey) = rsa.newkeys(512)
    message = b'Hello World'
    encrypted = rsa.encrypt(message, pubkey)
    decrypted = rsa.decrypt(encrypted, privkey)
    assert decrypted == message
    print(f"    Encrypt/decrypt: {len(message)} bytes OK")
    return True
test("encrypt/decrypt", test_encrypt_decrypt)

# --- Sign/Verify SHA-256 (512-bit) ---
def test_sha256():
    import rsa
    (pubkey, privkey) = rsa.newkeys(512)
    message = b'Hello World'
    signature = rsa.sign(message, privkey, 'SHA-256')
    rsa.verify(message, signature, pubkey)
    print(f"    Sign/verify: SHA-256 OK")
    return True
test("sign/verify (SHA-256)", test_sha256)

# --- Sign/Verify SHA-384 (1024-bit key needed) ---
def test_sha384():
    import rsa
    (pubkey, privkey) = rsa.newkeys(1024)
    message = b'Hello World'
    signature = rsa.sign(message, privkey, 'SHA-384')
    rsa.verify(message, signature, pubkey)
    print(f"    Sign/verify: SHA-384 OK")
    return True
test("sign/verify (SHA-384)", test_sha384)

# --- Sign/Verify SHA-512 (1024-bit key needed) ---
def test_sha512():
    import rsa
    (pubkey, privkey) = rsa.newkeys(1024)
    message = b'Hello World'
    signature = rsa.sign(message, privkey, 'SHA-512')
    rsa.verify(message, signature, pubkey)
    print(f"    Sign/verify: SHA-512 OK")
    return True
test("sign/verify (SHA-512)", test_sha512)

# --- PEM Export/Import ---
def test_pem():
    import rsa
    (pubkey, privkey) = rsa.newkeys(512)
    pub_pem = pubkey.save_pkcs1()
    priv_pem = privkey.save_pkcs1()
    assert len(pub_pem) > 0
    assert len(priv_pem) > 0
    pubkey2 = rsa.PublicKey.load_pkcs1(pub_pem)
    privkey2 = rsa.PrivateKey.load_pkcs1(priv_pem)
    message = b'test'
    encrypted = rsa.encrypt(message, pubkey2)
    decrypted = rsa.decrypt(encrypted, privkey2)
    assert decrypted == message
    print(f"    PEM export/import: OK")
    return True
test("PEM export/import", test_pem)

# --- Large message (1024-bit key) ---
def test_large():
    import rsa
    (pubkey, privkey) = rsa.newkeys(1024)
    message = b'X' * 100
    encrypted = rsa.encrypt(message, pubkey)
    decrypted = rsa.decrypt(encrypted, privkey)
    assert decrypted == message
    print(f"    Large message: {len(message)} bytes OK")
    return True
test("large message (100 bytes)", test_large)

# --- Print Results ---
print()
print("=" * 60)
print(" RESULTS")
print("=" * 60)
for status, name in RESULTS:
    icon = "PASS" if status == "PASS" else "FAIL" if status == "FAIL" else "SKIP"
    print(f"  [{icon}] {name}")
print()
print(f"  PASS: {PASS} | FAIL: {FAIL} | SKIP: {SKIP}")
print(f"  TOTAL: {PASS + FAIL + SKIP}")
print("=" * 60)

if FAIL > 0:
    print("\nRSA HAS FAILURES")
    sys.exit(1)
else:
    print("\nRSA ALL PASSED")
    sys.exit(0)
