"""
On-device verification for the cross-compiled pycryptodome 3.23.0 wheel.

Run after installing:
    pip install pycryptodome-3.23.0-cp312-abi3-android_24_<ABI>.whl

Usage:
    python Test_PyCryptodome.py [--quick]

Exit code 0 = everything required PASSed. All hashes/ciphers here use the
NIST / RFC known-answer vectors, so a wrong native build fails loudly.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def hx(b):
    return bytes(b).hex()


# ---------------------------------------------------------------------------
# 1. import surface + native module loading (ctypes .abi3.so)
# ---------------------------------------------------------------------------
def imports_core():
    from Crypto.Util._raw_api import load_pycryptodome_raw_lib
    assert load_pycryptodome_raw_lib("Crypto.Hash._SHA256", "int dummy(void);") is not None


def imports_subpackages():
    import Crypto.Cipher  # noqa: F401
    import Crypto.Hash  # noqa: F401
    import Crypto.Math  # noqa: F401
    import Crypto.Protocol  # noqa: F401
    import Crypto.PublicKey  # noqa: F401
    import Crypto.Random  # noqa: F401
    import Crypto.Signature  # noqa: F401
    import Crypto.Util  # noqa: F401


# ---------------------------------------------------------------------------
# 2. hashes (NIST vectors)
# ---------------------------------------------------------------------------
def sha256():
    from Crypto.Hash import SHA256
    assert SHA256.new(b"abc").hexdigest() == (
        "ba7816bf8f01cfea414140de5dae2223"
        "b00361a396177a9cb410ff61f20015ad"), "SHA256(abc)"


def sha1():
    from Crypto.Hash import SHA1
    assert SHA1.new(b"abc").hexdigest() == (
        "a9993e364706816aba3e25717850c26c9cd0d89d"), "SHA1(abc)"


def md5():
    from Crypto.Hash import MD5
    assert MD5.new(b"abc").hexdigest() == (
        "900150983cd24fb0d6963f7d28e17f72"), "MD5(abc)"


def sha512():
    from Crypto.Hash import SHA512
    assert SHA512.new(b"abc").hexdigest().startswith(
        "ddaf35a193617aba"), "SHA512(abc)"


def ripemd160():
    from Crypto.Hash import RIPEMD160
    assert RIPEMD160.new(b"abc").hexdigest() == (
        "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc"), "RIPEMD160(abc)"


def keccak():
    from Crypto.Hash import keccak
    assert keccak.new(digest_bits=256, data=b"abc").hexdigest() == (
        "4e03657aea45a94fc7d47ba826c8d667"
        "c0d1e6e33a64a036ec44f58fa12d6c45"), "keccak256(abc)"


def blake2():
    from Crypto.Hash import BLAKE2b, BLAKE2s
    assert len(BLAKE2b.new(digest_bits=512, data=b"abc").digest()) == 64
    assert len(BLAKE2s.new(digest_bits=256, data=b"abc").digest()) == 32


def md2_md4():
    from Crypto.Hash import MD2, MD4
    assert len(MD2.new(b"abc").digest()) == 16
    assert len(MD4.new(b"abc").digest()) == 16


def hmac_():
    from Crypto.Hash import HMAC, SHA256
    # RFC 4231 test case 1
    key = b"\x0b" * 20
    data = b"Hi There"
    assert HMAC.new(key, data, digestmod=SHA256).hexdigest() == (
        "b0344c61d8db38535ca8afceaf0bf12b"
        "881dc200c9833da726e9376c2e32cff7"), "HMAC-SHA256 RFC4231"


def cmac():
    from Crypto.Hash import CMAC
    from Crypto.Cipher import AES
    # NIST SP 800-38B example
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    msg = bytes.fromhex("6bc1bee22e409f96e93d7e117393172a")
    assert CMAC.new(key, msg, ciphermod=AES).hexdigest() == (
        "070a16b46b4d4144f79bdd9dd04a287c"), "CMAC-AES"


# ---------------------------------------------------------------------------
# 3. block ciphers (NIST AES vectors)
# ---------------------------------------------------------------------------
def aes_ecb():
    from Crypto.Cipher import AES
    # FIPS-197 AES-128 vector
    key = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
    pt = bytes.fromhex("00112233445566778899aabbccddeeff")
    c = AES.new(key, AES.MODE_ECB)
    assert hx(c.encrypt(pt)) == (
        "69c4e0d86a7b0430d8cdb78070b4c55a"), "AES-128 ECB vector"


def aes_cbc():
    from Crypto.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    iv = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
    pt = bytes.fromhex("6bc1bee22e409f96e93d7e117393172a")
    c = AES.new(key, AES.MODE_CBC, iv)
    assert hx(c.encrypt(pt)) == (
        "7649abac8119b246cee98e9b12e9197d"), "AES-CBC vector"


def aes_gcm():
    from Crypto.Cipher import AES
    # NIST GCM example
    key = bytes.fromhex("feffe9928665731c6d6a8f9467308308")
    nonce = bytes.fromhex("cafebabefacedbaddecaf888")
    pt = bytes.fromhex("d9313225f88406e5a55909c5aff5269a"
                       "86a7a9531534f7da2e4c303d8a318a72"
                       "1c3c0c95956809532fcf0e2449a6b525"
                       "b16aedf5aa0de657ba637b39")
    aad = bytes.fromhex("feedfacedeadbeeffeedfacedeadbeefabaddad2")
    c = AES.new(key, AES.MODE_GCM, nonce=nonce)
    c.update(aad)
    ct, tag = c.encrypt_and_digest(pt)
    assert hx(ct[:16]) == (
        "42831ec2217774244b7221b784d0d49c"), "AES-GCM ct"
    assert hx(tag) == (
        "5bc94fbc3221a5db94fae95ae7121a47"), "AES-GCM tag"
    d = AES.new(key, AES.MODE_GCM, nonce=nonce)
    d.update(aad)
    assert d.decrypt_and_verify(ct, tag) == pt, "AES-GCM decrypt"


def aes_ocb():
    from Crypto.Cipher import AES
    key = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
    nonce = bytes.fromhex("000102030405060708090a0b")
    pt = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
    c = AES.new(key, AES.MODE_OCB, nonce=nonce)
    ct, tag = c.encrypt_and_digest(pt)
    d = AES.new(key, AES.MODE_OCB, nonce=nonce)
    assert d.decrypt_and_verify(ct, tag) == pt, "AES-OCB roundtrip"


def aes_ctr():
    from Crypto.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    nonce = bytes.fromhex("f0f1f2f3f4f5f6f7")
    c = AES.new(key, AES.MODE_CTR, nonce=nonce)
    pt = b"a" * 32
    ct = c.encrypt(pt)
    d = AES.new(key, AES.MODE_CTR, nonce=nonce)
    assert d.decrypt(ct) == pt, "AES-CTR roundtrip"


def des_des3():
    from Crypto.Cipher import DES, DES3
    # FIPS 81 example
    key = bytes.fromhex("133457799bbcdff1")
    pt = bytes.fromhex("0123456789abcdef")
    assert hx(DES.new(key, DES.MODE_ECB).encrypt(pt)) == (
        "85e813540f0ab405"), "DES-ECB vector"
    k3 = key + bytes.fromhex("0123456789abcdef") + bytes.fromhex("1f2e3d4c5b6a7968")
    assert len(DES3.new(k3, DES3.MODE_ECB).encrypt(pt)) == 8, "3DES-ECB"


def arc2_cast_blowfish():
    from Crypto.Cipher import ARC2, CAST, Blowfish
    assert len(ARC2.new(bytes(8), ARC2.MODE_ECB).encrypt(b"01234567")) == 8
    assert len(CAST.new(bytes(16), CAST.MODE_ECB).encrypt(b"01234567")) == 8
    assert len(Blowfish.new(bytes(8), Blowfish.MODE_ECB).encrypt(b"01234567")) == 8


def stream_ciphers():
    from Crypto.Cipher import ARC4, ChaCha20, Salsa20
    key = bytes(range(32))
    rc4 = ARC4.new(key)
    assert rc4.encrypt(b"attack at dawn") != b"attack at dawn", "ARC4"
    c = ChaCha20.new(key=key)
    ct = c.encrypt(b"x" * 64)
    assert len(ct) == 64, "ChaCha20"
    s = Salsa20.new(key=key)
    assert len(s.encrypt(b"x" * 64)) == 64, "Salsa20"


# ---------------------------------------------------------------------------
# 4. public key
# ---------------------------------------------------------------------------
def rsa_keygen_sign():
    from Crypto.PublicKey import RSA
    from Crypto.Signature import pkcs1_15
    from Crypto.Hash import SHA256
    key = RSA.generate(2048)
    h = SHA256.new(b"data")
    sig = pkcs1_15.new(key).sign(h)
    pkcs1_15.new(key.publickey()).verify(h, sig)
    pem = key.publickey().export_key()
    assert RSA.import_key(pem).n == key.n, "RSA PEM roundtrip"


def ecdsa():
    from Crypto.PublicKey import ECC
    from Crypto.Signature import DSS
    from Crypto.Hash import SHA256
    key = ECC.generate(curve="P-256")
    h = SHA256.new(b"msg")
    sig = DSS.new(key, "fips-186-3").sign(h)
    DSS.new(key.public_key(), "fips-186-3").verify(h, sig)


def ed25519_ed448():
    from Crypto.PublicKey import ECC
    from Crypto.Signature import eddsa
    from Crypto.Hash import SHA512
    for curve, hashcls in (("Ed25519", None), ("Ed448", None)):
        key = ECC.generate(curve=curve)
        msg = b"msg"
        sig = eddsa.new(key, "rfc8032").sign(msg)
        eddsa.new(key.public_key(), "rfc8032").verify(msg, sig)


def x25519_x448():
    from Crypto.Protocol import DH
    from Crypto.PublicKey import ECC
    kdf = lambda x: x
    a = ECC.generate(curve="X25519")
    b = ECC.generate(curve="X25519")
    s1 = DH.key_agreement(static_priv=a, static_pub=b.public_key(), kdf=kdf)
    s2 = DH.key_agreement(static_priv=b, static_pub=a.public_key(), kdf=kdf)
    assert s1 == s2, "X25519 shared secret"
    a = ECC.generate(curve="X448")
    b = ECC.generate(curve="X448")
    s1 = DH.key_agreement(static_priv=a, static_pub=b.public_key(), kdf=kdf)
    s2 = DH.key_agreement(static_priv=b, static_pub=a.public_key(), kdf=kdf)
    assert s1 == s2, "X448 shared secret"


def pkcs1_oaep():
    from Crypto.PublicKey import RSA
    from Crypto.Cipher import PKCS1_OAEP
    key = RSA.generate(1024)
    ct = PKCS1_OAEP.new(key.publickey()).encrypt(b"secret")
    assert PKCS1_OAEP.new(key).decrypt(ct) == b"secret"


# ---------------------------------------------------------------------------
# 5. KDF / protocols
# ---------------------------------------------------------------------------
def pbkdf2():
    from Crypto.Protocol.KDF import PBKDF2
    # RFC 6070: PBKDF2-HMAC-SHA1("password","salt",1,20)
    k = PBKDF2(b"password", b"salt", dkLen=20, count=1)
    assert hx(k) == "0c60c80f961f0e71f3a9b524af6012062fe037a6", "PBKDF2 RFC6070"


def scrypt():
    from Crypto.Protocol.KDF import scrypt
    # RFC 7914: scrypt(P="password", S="NaCl", N=1024, r=8, p=16, 64)
    k = scrypt(b"password", b"NaCl", 64, N=2 ** 10, r=8, p=16)
    assert hx(k) == (
        "fdbabe1c9d3472007856e7190d01e9fe"
        "7c6ad7cbc8237830e77376634b373162"
        "2eaf30d92e22a3886ff109279d9830da"
        "c727afb94a83ee6d8360cbdfa2cc0640"), "scrypt RFC7914"


def random_():
    from Crypto.Random import get_random_bytes
    a = get_random_bytes(32)
    b = get_random_bytes(32)
    assert len(a) == 32 and a != b, "random bytes"


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. import surface + native modules")
    test("raw native module load (ctypes .abi3.so)", imports_core)
    test("all Crypto.* subpackages import", imports_subpackages)

    section("2. hashes / MACs")
    test("SHA256 (NIST vector)", sha256)
    test("SHA1 (NIST vector)", sha1)
    test("MD5 (RFC1321 vector)", md5)
    test("SHA512", sha512)
    test("RIPEMD160", ripemd160)
    test("Keccak", keccak)
    test("BLAKE2b/BLAKE2s", blake2)
    test("MD2/MD4", md2_md4)
    test("HMAC-SHA256 (RFC4231)", hmac_)
    test("CMAC-AES (SP800-38B)", cmac)

    section("3. ciphers")
    test("AES-ECB (NIST vector)", aes_ecb)
    test("AES-CBC (NIST vector)", aes_cbc)
    test("AES-GCM (NIST vector + decrypt)", aes_gcm)
    test("AES-OCB roundtrip", aes_ocb)
    test("AES-CTR roundtrip", aes_ctr)
    test("DES / 3DES", des_des3)
    test("ARC2 / CAST / Blowfish", arc2_cast_blowfish)
    test("ARC4 / ChaCha20 / Salsa20", stream_ciphers)

    section("4. public key")
    test("RSA keygen + sign/verify + PEM", rsa_keygen_sign)
    test("ECDSA P-256", ecdsa)
    test("Ed25519 / Ed448", ed25519_ed448)
    test("X25519 / X448 key agreement", x25519_x448)
    test("RSA-OAEP", pkcs1_oaep)

    section("5. KDF / protocols")
    test("PBKDF2 (RFC6070)", pbkdf2)
    test("scrypt (RFC7914)", scrypt)
    test("random bytes", random_)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()

