"""
On-device verification for the cross-compiled orjson wheel.

Run after installing:
    pip install orjson-3.11.9-cp312-cp312-linux_<ABI>.whl

Usage:
    python Test_orjson.py [--quick]

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_orjson():
    import orjson
    print("    orjson", orjson.__version__)
    assert hasattr(orjson, "dumps")
    assert hasattr(orjson, "loads")
    assert hasattr(orjson, "OPT_INDENT_2")


# ---------------------------------------------------------------------------
# 2. dumps / loads basic
# ---------------------------------------------------------------------------
def dumps_loads_str():
    import orjson
    data = {"hello": "world", "num": 42, "flag": True}
    b = orjson.dumps(data)
    assert isinstance(b, bytes)
    result = orjson.loads(b)
    assert result == data


def dumps_loads_int():
    import orjson
    for v in (0, 1, -1, 1000000, 2**53, -(2**53)):
        assert orjson.loads(orjson.dumps(v)) == v


def dumps_loads_float():
    import orjson
    import math
    for v in (0.0, 1.5, -3.14, 1e10, 1e-10):
        result = orjson.loads(orjson.dumps(v))
        assert abs(result - v) < 1e-6


def dumps_loads_none():
    import orjson
    assert orjson.loads(orjson.dumps(None)) is None


def dumps_loads_bool():
    import orjson
    assert orjson.loads(orjson.dumps(True)) is True
    assert orjson.loads(orjson.dumps(False)) is False


# ---------------------------------------------------------------------------
# 3. nested structures
# ---------------------------------------------------------------------------
def nested_structures():
    import orjson
    data = {
        "list": [1, 2, 3],
        "nested": {"a": {"b": {"c": [1, 2, 3]}}},
        "mixed": [{"x": 1}, {"x": 2}, [1, 2, 3]],
    }
    result = orjson.loads(orjson.dumps(data))
    assert result == data


# ---------------------------------------------------------------------------
# 4. strings / unicode
# ---------------------------------------------------------------------------
def unicode_strings():
    import orjson
    data = {"text": "hello", "emoji": "\u2764", "chinese": "\u4f60\u597d"}
    result = orjson.loads(orjson.dumps(data))
    assert result == data


def escape_sequences():
    import orjson
    data = {"tab": "\t", "newline": "\n", "quote": '"', "backslash": "\\"}
    result = orjson.loads(orjson.dumps(data))
    assert result == data


# ---------------------------------------------------------------------------
# 5. special float values
# ---------------------------------------------------------------------------
def special_floats():
    import orjson
    import math
    import orjson as oj
    data = {"inf": float("inf"), "neg_inf": float("-inf"), "nan": float("nan")}
    b = oj.dumps(data)
    result = oj.loads(b)
    assert result["inf"] == float("inf")
    assert result["neg_inf"] == float("-inf")
    assert math.isnan(result["nan"])


# ---------------------------------------------------------------------------
# 6. options / flags
# ---------------------------------------------------------------------------
def opt_indent_2():
    import orjson
    data = {"a": 1, "b": [1, 2, 3]}
    b = orjson.dumps(data, option=orjson.OPT_INDENT_2)
    text = b.decode()
    assert "\n" in text
    assert "  " in text


def opt_sorted_keys():
    import orjson
    data = {"z": 1, "a": 2, "m": 3}
    b = orjson.dumps(data, option=orjson.OPT_SORT_KEYS)
    text = b.decode()
    keys = list(orjson.loads(b).keys())
    assert keys == ["a", "m", "z"]


def opt_dumps_numpy():
    import orjson
    try:
        import numpy as np
        arr = np.array([1, 2, 3])
        b = orjson.dumps({"arr": arr}, option=orjson.OPT_SERIALIZE_NUMPY)
        result = orjson.loads(b)
        assert result["arr"] == [1, 2, 3]
    except ImportError:
        raise NotImplementedError("numpy not installed")


# ---------------------------------------------------------------------------
# 7. dataclass support
# ---------------------------------------------------------------------------
def dataclass_support():
    import orjson
    from dataclasses import dataclass

    @dataclass
    class Point:
        x: float
        y: float

    p = Point(1.0, 2.0)
    b = orjson.dumps(p)
    result = orjson.loads(b)
    assert result == {"x": 1.0, "y": 2.0}


# ---------------------------------------------------------------------------
# 8. large data
# ---------------------------------------------------------------------------
def large_list():
    import orjson
    data = list(range(100000))
    b = orjson.dumps(data)
    result = orjson.loads(b)
    assert len(result) == 100000
    assert result[0] == 0
    assert result[-1] == 99999


def large_dict():
    import orjson
    data = {"key_%d" % i: i for i in range(10000)}
    b = orjson.dumps(data)
    result = orjson.loads(b)
    assert len(result) == 10000


# ---------------------------------------------------------------------------
# 9. binary data (raw)
# ---------------------------------------------------------------------------
def raw_bytes():
    import orjson
    data = {"raw": [1, 2, 3]}
    b = orjson.dumps(data)
    assert isinstance(b, bytes)
    assert b == b'{"raw":[1,2,3]}'


# ---------------------------------------------------------------------------
# 10. datetime support (if available)
# ---------------------------------------------------------------------------
def datetime_support():
    import orjson
    from datetime import datetime, timezone
    dt = datetime(2024, 1, 15, 12, 30, 45, tzinfo=timezone.utc)
    b = orjson.dumps({"ts": dt})
    result = orjson.loads(b)
    assert "2024" in result["ts"]


# ---------------------------------------------------------------------------
# 11. exception handling
# ---------------------------------------------------------------------------
def invalid_json():
    import orjson
    try:
        orjson.loads(b"not valid json")
        assert False, "should have raised"
    except orjson.JSONDecodeError:
        pass


def dumps_unsupported():
    import orjson
    try:
        orjson.dumps(object())
        assert False, "should have raised"
    except TypeError:
        pass


# ---------------------------------------------------------------------------
# 12. decode output type
# ---------------------------------------------------------------------------
def decode_type():
    import orjson
    b = orjson.dumps({"a": 1})
    assert isinstance(b, bytes)
    # loads accepts both bytes and str
    r1 = orjson.loads(b)
    r2 = orjson.loads(b.decode())
    assert r1 == r2


# ---------------------------------------------------------------------------
# 13. array of objects (common pattern)
# ---------------------------------------------------------------------------
def array_of_objects():
    import orjson
    data = [{"id": i, "name": "item_%d" % i, "value": i * 1.5} for i in range(1000)]
    b = orjson.dumps(data)
    result = orjson.loads(b)
    assert len(result) == 1000
    assert result[0]["name"] == "item_0"
    assert result[999]["value"] == 999 * 1.5


# ---------------------------------------------------------------------------
# 14. key types
# ---------------------------------------------------------------------------
def key_types():
    import orjson
    # String keys
    data = {"a": 1, "b": 2}
    assert orjson.loads(orjson.dumps(data)) == data

    # Integer keys (JSON converts to strings)
    data = {1: "one", 2: "two"}
    b = orjson.dumps(data)
    result = orjson.loads(b)
    assert result == {"1": "one", "2": "two"}


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. orjson import / version")
    test("import orjson", import_orjson)

    section("2. dumps / loads basic")
    test("str roundtrip", dumps_loads_str)
    test("int roundtrip", dumps_loads_int)
    test("float roundtrip", dumps_loads_float)
    test("None roundtrip", dumps_loads_none)
    test("bool roundtrip", dumps_loads_bool)

    section("3. nested structures")
    test("nested dict/list", nested_structures)

    section("4. strings / unicode")
    test("unicode strings", unicode_strings)
    test("escape sequences", escape_sequences)

    section("5. special float values")
    test("inf / nan handling", special_floats)

    section("6. options / flags")
    test("OPT_INDENT_2", opt_indent_2)
    test("OPT_SORT_KEYS", opt_sorted_keys)
    test("OPT_SERIALIZE_NUMPY", opt_dumps_numpy)

    section("7. dataclass support")
    test("dataclass serialization", dataclass_support)

    section("8. large data")
    test("large list (100K)", large_list)
    test("large dict (10K)", large_dict)

    section("9. binary output")
    test("raw bytes output", raw_bytes)

    section("10. datetime support")
    test("datetime roundtrip", datetime_support)

    section("11. exception handling")
    test("invalid JSON raises", invalid_json)
    test("unsupported type raises", dumps_unsupported)

    section("12. decode output type")
    test("bytes and str input to loads", decode_type)

    section("13. common patterns")
    test("array of objects (1K)", array_of_objects)
    test("integer keys", key_types)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
