"""
Test_blosc.py - on-device validation for the blosc wheel.

Generated by RIMI
"""
import sys

SECTIONS = []

def sec(name):
    def deco(fn):
        SECTIONS.append((name, fn))
        return fn
    return deco

passed = skipped = failed = 0

def run_section(name, fn):
    global passed, failed
    print("=" * 60)
    print("===== %s =====" % name)
    print("=" * 60)
    try:
        fn()
        print("[PASS] %s" % name)
        passed += 1
    except Exception as e:
        print("[FAIL] %s  (%s: %s)" % (name, type(e).__name__, e))
        failed += 1

def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True

@sec("import surface")
def t_import():
    import blosc
    eq("version", blosc.__version__, "1.11.4")
    assert blosc.VERSION_STRING.startswith("1.2"), blosc.VERSION_STRING
    eq("MAX_TYPESIZE", blosc.MAX_TYPESIZE, 255)
    assert blosc.MAX_BUFFERSIZE > 0
    eq("init ok", True, callable(blosc.init))
    names = blosc.compressor_list()
    print("  codecs:", names)
    for n in ("blosclz", "lz4", "zlib", "zstd"):
        assert n in names, "missing codec %s" % n
    eq("filters noshuffle", blosc.filters[blosc.NOSHUFFLE], "noshuffle")
    eq("filters shuffle", blosc.filters[blosc.SHUFFLE], "shuffle")
    eq("filters bitshuffle", blosc.filters[blosc.BITSHUFFLE], "bitshuffle")
    for name in names:
        lib, ver = blosc.clib_info(name)
        assert lib and ver, "clib_info %s empty" % name

@sec("compress round-trips")
def t_compress():
    import blosc
    data = bytes(range(256)) * 64
    for cname in blosc.compressor_list():
        for clevel in (1, 5, 9):
            for shuffle in (blosc.NOSHUFFLE, blosc.SHUFFLE, blosc.BITSHUFFLE):
                c = blosc.compress(data, typesize=8, clevel=clevel, shuffle=shuffle, cname=cname)
                assert isinstance(c, bytes) and len(c) > 0, (cname, clevel, shuffle)
                d = blosc.decompress(c)
                eq("roundtrip %s/%d/%s" % (cname, clevel, shuffle), d, data)
    big = bytes(bytearray([i % 251 for i in range(1024 * 1024)]))
    c = blosc.compress(big, typesize=1, clevel=5, shuffle=blosc.SHUFFLE, cname="zstd")
    d = blosc.decompress(c)
    eq("1MiB zstd roundtrip", d, big)
    sizes = blosc.get_cbuffer_sizes(c)
    eq("cbuffer nbytes", sizes[0], len(big))
    eq("cbuffer cbytes > 0", True, sizes[1] > 0)
    assert isinstance(sizes[2], int) and sizes[2] > 0, sizes
    eq("cbuffer validate", True, blosc.cbuffer_validate(c))

@sec("compress_ptr / decompress_ptr")
def t_ptr():
    import blosc
    import ctypes
    data = bytes(range(256)) * 16
    buf = ctypes.create_string_buffer(data)
    addr = ctypes.addressof(buf)
    c = blosc.compress_ptr(addr, len(data), typesize=1, clevel=5,
                           shuffle=blosc.SHUFFLE, cname="lz4")
    assert isinstance(c, bytes) and len(c) > 0
    out = ctypes.create_string_buffer(len(data))
    n = blosc.decompress_ptr(c, ctypes.addressof(out))
    eq("decompressed size", n, len(data))
    eq("content", out.raw, data)

@sec("numpy pack/unpack")
def t_numpy():
    import numpy as np
    import blosc
    for dtype in (np.int32, np.int64, np.float64, np.float32):
        a = np.arange(1000, dtype=dtype) + (0.5 if dtype in (np.float64, np.float32) else 0)
        packed = blosc.pack_array(a)
        assert isinstance(packed, bytes) and len(packed) > 0
        b = blosc.unpack_array(packed)
        eq("dtype %s" % dtype.__name__, b.dtype, a.dtype)
        eq("shape %s" % dtype.__name__, b.shape, a.shape)
        assert (b == a).all(), "values differ for %s" % dtype.__name__
    a = np.arange(24, dtype=np.float64).reshape(2, 3, 4)
    b = blosc.unpack_array(blosc.pack_array(a))
    eq("ndim shape", b.shape, (2, 3, 4))
    assert (b == a).all()

@sec("settings + threading")
def t_settings():
    import blosc
    old = blosc.set_nthreads(2)
    assert isinstance(old, int) and old >= 1
    blosc.set_blocksize(0)
    blosc.set_blocksize(1 << 16)
    eq("get_blocksize", True, isinstance(blosc.get_blocksize(), int))
    eq("releasegil", True, callable(blosc.set_releasegil))
    blosc.set_releasegil(True)
    data = bytes(range(256)) * 16
    d = blosc.decompress(blosc.compress(data, typesize=8, cname="blosclz"))
    eq("roundtrip after releasegil", d, data)
    blosc.set_releasegil(False)
    eq("free_resources", True, callable(blosc.free_resources))
    blosc.free_resources()

@sec("edge cases")
def t_edge():
    import blosc
    empty = blosc.decompress(blosc.compress(b"", typesize=8, cname="lz4"))
    eq("empty roundtrip", empty, b"")
    one = blosc.decompress(blosc.compress(b"x", typesize=1, cname="zstd"))
    eq("single byte", one, b"x")
    eq("print_versions", True, callable(blosc.print_versions))
    blosc.print_versions()

print("=" * 60)
print("===== import ===== (blosc)")
print("=" * 60)
print("blosc: %s" % __import__("blosc", fromlist=["__file__"]).__file__)
for name, fn in SECTIONS:
    run_section(name, fn)

print()
print("===== result =====")
print("passed=%d skipped=%d failed=%d" % (passed, skipped, failed))
sys.exit(1 if failed else 0)
