"""psycopg2 2.9.12 android smoke test - NETWORK-SAFE (no SQL server used).

Validates the extension + statically linked libpq 16.6 load and behave:
module surface, version infos, DBAPI constants, client-side adapters,
conninfo/DSN parsing, and the libpq connect error path (dead endpoint must
raise OperationalError carrying a real libpq error message). No live
database round-trip is attempted (no server allowed on the host machine).

Generated by RIMI
"""
import sys
import time

PASS = FAIL = SKIP = 0


def section(name):
    print("\n=== %s ===" % name)


def chk(name, cond, info=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print("  PASS  %s %s" % (name, info))
    else:
        FAIL += 1
        print("  FAIL  %s %s" % (name, info))


def chk_skip(name):
    global SKIP
    SKIP += 1
    print("  SKIP  %s" % name)


try:
    import psycopg2
    from psycopg2 import extensions, extras, errors, sql, pool, tz
except Exception:
    print("FATAL: cannot import psycopg2")
    raise

section("1. import + version surface")
chk("module imports", True)
chk("psycopg2.__version__", psycopg2.__version__.startswith("2.9.12"), psycopg2.__version__)
chk("psycopg2.__libpq_version__ int", isinstance(psycopg2.__libpq_version__, int), psycopg2.__libpq_version__)
chk("libpq >= 15 (PG16 client)", psycopg2.__libpq_version__ >= 150000)
chk("apilevel", psycopg2.apilevel == "2.0")
chk("threadsafety", psycopg2.threadsafety == 2)
chk("paramstyle", psycopg2.paramstyle == "pyformat")
chk("module functions", all(hasattr(psycopg2, n) for n in (
    "connect", "BINARY", "Binary", "Date", "Time", "Timestamp", "DateFromTicks",
    "TimeFromTicks", "TimestampFromTicks")))

section("2. submodules surface")
chk("extensions.connection", callable(extensions.connection))
chk("extensions.cursor", callable(extensions.cursor))
chk("extensions ISOLATION_LEVEL_*", all(hasattr(extensions, n) for n in (
    "ISOLATION_LEVEL_AUTOCOMMIT", "ISOLATION_LEVEL_READ_COMMITTED",
    "ISOLATION_LEVEL_SERIALIZABLE")))
chk("extensions.set_wait_callback", callable(extensions.set_wait_callback))
chk("errors module classes", all(hasattr(errors, n) for n in (
    "ProgrammingError", "OperationalError", "IntegrityError", "DataError",
    "NotNullViolation", "UniqueViolation", "UndefinedTable")))
chk("pool module", all(hasattr(pool, n) for n in (
    "SimpleConnectionPool", "ThreadedConnectionPool")))
chk("sql module", all(hasattr(sql, n) for n in ("SQL", "Identifier", "Literal", "Placeholder", "Composed")))

section("3. DBAPI exception hierarchy")
chk("Error base", issubclass(psycopg2.Error, Exception))
chk("OperationalError < Error", issubclass(psycopg2.OperationalError, psycopg2.Error))
chk("ProgrammingError < Error", issubclass(psycopg2.ProgrammingError, psycopg2.Error))
chk("InterfaceError < Error", issubclass(psycopg2.InterfaceError, psycopg2.Error))
chk("DataError < DatabaseError", issubclass(psycopg2.DataError, psycopg2.DatabaseError))

section("4. client-side adapters (no server)")
import decimal
import datetime
chk("adapt int", extensions.adapt(42).getquoted() == b"42")
chk("adapt float", extensions.adapt(3.5).getquoted() == b"3.5")
chk("adapt None", extensions.adapt(None).getquoted() == b"NULL")
chk("adapt str quoted", extensions.adapt("it's").getquoted() == b"'it''s'")
chk("adapt bytes (bytea literal)", (lambda q: q.startswith(b"'") and q.endswith(b"'::bytea") and len(q) > 10)(extensions.adapt(b"\x00\x01").getquoted()))
chk("adapt Decimal", extensions.adapt(decimal.Decimal("1.25")).getquoted() == b"1.25")
chk("adapt date", extensions.adapt(datetime.date(2026, 8, 15)).getquoted() == b"'2026-08-15'::date")
chk("adapt datetime", extensions.adapt(datetime.datetime(2026, 8, 15, 1, 2, 3)).getquoted() == b"'2026-08-15T01:02:03'::timestamp")
chk("adapt bool", extensions.adapt(True).getquoted() in (b"true", b"TRUE"))
chk("extras.Json", isinstance(extras.Json, type))
chk("AsIs passthrough", extensions.AsIs("raw").getquoted() == b"raw")

section("5. sql composition + conninfo parsing (client-side)")
q = sql.SQL("SELECT {f} FROM {t} WHERE x = {v}").format(
    f=sql.Identifier("name"), t=sql.Identifier("users"), v=sql.Literal(7))
parts = list(q)
chk("sql composed parts list", isinstance(parts, list) and len(parts) >= 5)
chk("sql part Identifier('name')", any(isinstance(p, sql.Identifier) and p.string == "name" for p in parts))
chk("sql part Literal(7)", any(isinstance(p, sql.Literal) and p.wrapped == 7 for p in parts))
chk("sql.SQL plain as_string(None)", sql.SQL("SELECT 1").as_string(None) == "SELECT 1")
chk("sql.Identifier.string", sql.Identifier("a b").string == "a b")
try:
    psycopg2.connect("dbname=;;; invalid dsn ;;")
    chk("bad dsn rejected", False)
except psycopg2.Error as e:
    chk("bad dsn rejected (client-side error)", "dsn" in str(e).lower() or "invalid" in str(e).lower() or "unterminated" in str(e).lower(), str(e)[:80])
except Exception as e:
    chk("bad dsn rejected (other error type)", True, "%s: %s" % (type(e).__name__, str(e)[:80]))

section("6. libpq connect error path (dead endpoint)")
started = time.time()
try:
    psycopg2.connect(host="127.0.0.1", port=1, dbname="x", user="y", connect_timeout=3)
    chk("dead endpoint raises", False)
except psycopg2.OperationalError as e:
    msg = str(e)
    chk("dead endpoint raises OperationalError", True)
    chk("error carries libpq text", len(msg) > 0, msg[:80])
    chk("connection failed fast (<10s)", (time.time() - started) < 10, "%.1fs" % (time.time() - started))
except Exception as e:
    chk("dead endpoint error type", False, "%s: %s" % (type(e).__name__, str(e)[:80]))

section("7. close/term")
print("  (no live connection to close - skipped)")
SKIP += 1
print("  SKIP  live connection lifecycle (no server)")

print("\n===== %d PASS, %d FAIL, %d SKIP =====" % (PASS, FAIL, SKIP))
sys.exit(0 if FAIL == 0 else 2)
