"""
On-device verification for the cross-compiled pycryptodomex 3.23.0 wheel.

Run after installing:
    pip install pycryptodomex-3.23.0-cp312-abi3-android_24_<ABI>.whl

Usage:
    python Test_PyCryptodomex.py [--quick]

Exit code 0 = everything required PASSed. All hashes/ciphers here use the
NIST / RFC known-answer vectors, so a wrong native build fails loudly.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def hx(b):
    return bytes(b).hex()


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_cryptodome():
    import Cryptodome
    print("    Cryptodome.__file__:", Cryptodome.__file__)


def import_cipher():
    from Cryptodome.Cipher import AES


def import_hash():
    from Cryptodome.Hash import SHA256, MD5


def import_publickey():
    from Cryptodome.PublicKey import RSA


def import_signature():
    from Cryptodome.Signature import pkcs1_15


def import_util():
    from Cryptodome.Util import Padding


# ---------------------------------------------------------------------------
# 2. AES encrypt/decrypt
# ---------------------------------------------------------------------------
def aes_ecb_roundtrip():
    from Cryptodome.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    pt = b"This is a test!!"
    cipher = AES.new(key, AES.MODE_ECB)
    ct = cipher.encrypt(pt)
    cipher2 = AES.new(key, AES.MODE_ECB)
    dt = cipher2.decrypt(ct)
    assert dt == pt, "AES ECB roundtrip failed"


def aes_cbc_roundtrip():
    from Cryptodome.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    iv = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
    pt = b"CBC mode test!!"
    cipher = AES.new(key, AES.MODE_CBC, iv)
    ct = cipher.encrypt(pt)
    cipher2 = AES.new(key, AES.MODE_CBC, iv)
    dt = cipher2.decrypt(ct)
    assert dt == pt, "AES CBC roundtrip failed"


def aes_gcm_roundtrip():
    from Cryptodome.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    pt = b"GCM mode test!!"
    cipher = AES.new(key, AES.MODE_GCM)
    ct, tag = cipher.encrypt_and_digest(pt)
    cipher2 = AES.new(key, AES.MODE_GCM, nonce=cipher.nonce)
    dt = cipher2.decrypt_and_verify(ct, tag)
    assert dt == pt, "AES GCM roundtrip failed"


def aes_ctr_roundtrip():
    from Cryptodome.Cipher import AES
    key = bytes.fromhex("2b7e151628aed2a6abf7158809cf4f3c")
    pt = b"CTR mode test!!"
    cipher = AES.new(key, AES.MODE_CTR)
    ct = cipher.encrypt(pt)
    cipher2 = AES.new(key, AES.MODE_CTR, nonce=cipher.nonce)
    dt = cipher2.decrypt(ct)
    assert dt == pt, "AES CTR roundtrip failed"


# ---------------------------------------------------------------------------
# 3. Hash functions
# ---------------------------------------------------------------------------
def sha256_test():
    from Cryptodome.Hash import SHA256
    h = SHA256.new()
    h.update(b"abc")
    expected = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    assert h.hexdigest() == expected, "SHA256 failed"


def md5_test():
    from Cryptodome.Hash import MD5
    h = MD5.new()
    h.update(b"abc")
    expected = "900150983cd24fb0d6963f7d28e17f72"
    assert h.hexdigest() == expected, "MD5 failed"


def sha512_test():
    from Cryptodome.Hash import SHA512
    h = SHA512.new()
    h.update(b"abc")
    expected = "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f"
    assert h.hexdigest() == expected, "SHA512 failed"


def sha1_test():
    from Cryptodome.Hash import SHA1
    h = SHA1.new()
    h.update(b"abc")
    expected = "a9993e364706816aba3e25717850c26c9cd0d89d"
    assert h.hexdigest() == expected, "SHA1 failed"


# ---------------------------------------------------------------------------
# 4. RSA key generation + sign/verify
# ---------------------------------------------------------------------------
def rsa_sign_verify():
    from Cryptodome.PublicKey import RSA
    from Cryptodome.Signature import pkcs1_15
    from Cryptodome.Hash import SHA256
    key = RSA.generate(2048)
    msg = b"Hello RSA"
    h = SHA256.new(msg)
    sig = pkcs1_15.new(key).sign(h)
    h2 = SHA256.new(msg)
    pkcs1_15.new(key).verify(h2, sig)


def rsa_encrypt_decrypt():
    from Cryptodome.PublicKey import RSA
    from Cryptodome.Cipher import PKCS1_OAEP
    key = RSA.generate(2048)
    cipher = PKCS1_OAEP.new(key)
    pt = b"RSA OAEP test"
    ct = cipher.encrypt(pt)
    dt = cipher.decrypt(ct)
    assert dt == pt, "RSA OAEP roundtrip failed"


# ---------------------------------------------------------------------------
# 5. Padding
# ---------------------------------------------------------------------------
def pkcs7_pad_unpad():
    from Cryptodome.Util import Padding
    data = b"hello"
    padded = Padding.pad(data, 16)
    assert len(padded) == 16, "PKCS7 pad failed"
    unpadded = Padding.unpad(padded, 16)
    assert unpadded == data, "PKCS7 unpad failed"


# ---------------------------------------------------------------------------
# Run all
# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. IMPORT")
    test("import Cryptodome", import_cryptodome)
    test("import AES", import_cipher)
    test("import SHA256/MD5", import_hash)
    test("import RSA", import_publickey)
    test("import pkcs1_15", import_signature)
    test("import Padding", import_util)

    if not quick:
        section("2. AES CIPHER")
        test("AES ECB roundtrip", aes_ecb_roundtrip)
        test("AES CBC roundtrip", aes_cbc_roundtrip)
        test("AES GCM roundtrip", aes_gcm_roundtrip)
        test("AES CTR roundtrip", aes_ctr_roundtrip)

        section("3. HASH FUNCTIONS")
        test("SHA256 known vector", sha256_test)
        test("MD5 known vector", md5_test)
        test("SHA512 known vector", sha512_test)
        test("SHA1 known vector", sha1_test)

        section("4. RSA SIGN/VERIFY + ENCRYPT/DECRYPT")
        test("RSA 2048 sign+verify", rsa_sign_verify)
        test("RSA OAEP encrypt+decrypt", rsa_encrypt_decrypt)

        section("5. PADDING")
        test("PKCS7 pad/unpad", pkcs7_pad_unpad)

    # summary
    print()
    print("=" * 60)
    print("RESULTS")
    print("=" * 60)
    passed = sum(1 for _, s, _ in RESULTS if s == "PASS")
    failed = sum(1 for _, s, _ in RESULTS if s == "FAIL")
    skipped = sum(1 for _, s, _ in RESULTS if s == "SKIP")
    for name, status, msg in RESULTS:
        flag = {"PASS": "[OK]", "FAIL": "[FAIL]", "SKIP": "[SKIP]"}[status]
        line = "  %s %s" % (flag, name)
        if msg:
            line += " -- %s" % msg
        print(line)
    print()
    print("Total: %d passed, %d failed, %d skipped" % (passed, failed, skipped))
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
