"""
On-device verification for the cross-compiled MarkupSafe 3.0.3 wheel.

Requires: typing_extensions (already on device - aiohttp dependency).
Usage:
    python Test_markupsafe.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


# ---------------------------------------------------------------------------
# 1. import surface + version + C speedups active
# ---------------------------------------------------------------------------
def t_import():
    import markupsafe
    section("===== import =====")
    print("markupsafe imported from:", markupsafe.__file__)
    eq("version", markupsafe.__version__, "3.0.3")
    # The C extension MUST provide _escape_inner (fast path).
    import markupsafe._speedups as sp
    print("speedups module:", sp.__file__)
    # _speedups exports exactly one function: _escape_inner (see _speedups.c
    # module_methods). escape() itself lives in markupsafe/__init__.py and
    # calls _escape_inner.
    eq("_escape_inner from C ext", markupsafe._escape_inner.__module__, "markupsafe._speedups")
    eq("C module exports _escape_inner", True, hasattr(sp, "_escape_inner"))
    eq("_escape_inner callable", True, callable(sp._escape_inner))


# ---------------------------------------------------------------------------
# 2. escape() - the C fast path
# ---------------------------------------------------------------------------
def t_escape():
    section("===== escape() =====")
    from markupsafe import escape
    eq("angle brackets", str(escape("a <b>c</b> d")), "a &lt;b&gt;c&lt;/b&gt; d")
    eq("ampersand first", str(escape("A & B")), "A &amp; B")
    eq("quotes", str(escape("say 'hi' \"yo\"")), "say &#39;hi&#39; &#34;yo&#34;")
    eq("greater sign", str(escape("5 > 3 < 4")), "5 &gt; 3 &lt; 4")
    eq("clean string unchanged", str(escape("plain text")), "plain text")
    eq("int", str(escape(42)), "42")
    eq("none", str(escape(None)), "None")
    eq("float", str(escape(1.5)), "1.5")
    eq("returns Markup", type(escape("x")).__name__, "Markup")
    eq("unicode kept", str(escape("caf\u00e9 \u2603")), "caf\u00e9 \u2603")
    eq("emoji kept", str(escape("\U0001f600")), "\U0001f600")


# ---------------------------------------------------------------------------
# 3. Markup class: concat/format/join/mul
# ---------------------------------------------------------------------------
def t_markup():
    section("===== Markup =====")
    from markupsafe import Markup, escape
    m = Markup("<b>hi</b>")
    eq("str subclass", isinstance(m, str), True)
    eq("html marker", m.__html__() is m, True)

    # string concat auto-escapes the str side
    res = m + " & friends"
    eq("concat escapes str", str(res), "<b>hi</b> &amp; friends")
    eq("concat returns Markup", type(res).__name__, "Markup")

    # Markup + Markup does NOT double-escape
    eq("markup+markup no double escape", str(Markup("<i>a</i>") + Markup("<i>b</i>")),
       "<i>a</i><i>b</i>")

    # format auto-escapes substitutions
    f = Markup("Hello, {0}! {x}").format(escape("<world>"), x="<x>")
    eq("format escapes", str(f), "Hello, &lt;world&gt;! &lt;x&gt;")

    # % style
    p = Markup("%s and %s") % ("<a>", "<b>")
    eq("percent escapes", str(p), "&lt;a&gt; and &lt;b&gt;")

    # join
    joined = Markup(", ").join(["<a>", "<b>"])
    eq("join escapes", str(joined), "&lt;a&gt;, &lt;b&gt;")

    # mul
    eq("mul", str(Markup("ab") * 2), "abab")

    # striptags
    eq("striptags", Markup("<b>Keep</b><script>x</script>").striptags(), "Keepx")

    # unescape round trip
    e = escape("<b>hi & bye</b>")
    eq("unescape round trip", str(Markup(str(e)).unescape()), "<b>hi & bye</b>")

    # __html__ protocol: escape() calls it
    class Obj:
        def __html__(self):
            return "<em>already html</em>"

    eq("escape uses __html__", str(escape(Obj())), "<em>already html</em>")


# ---------------------------------------------------------------------------
# 4. escape_silent + soft_str
# ---------------------------------------------------------------------------
def t_silent_soft():
    section("===== escape_silent + soft_str =====")
    from markupsafe import escape_silent, soft_str
    eq("silent none", str(escape_silent(None)), "")
    eq("silent value", str(escape_silent("<x>")), "&lt;x&gt;")
    eq("soft_str str passthrough", soft_str("abc"), "abc")
    eq("soft_str bytes str()", soft_str(b"abc"), "b'abc'")
    eq("soft_str type", type(soft_str("x")).__name__, "str")


# ---------------------------------------------------------------------------
# 5. round-trip torture (the classic escaping matrix)
# ---------------------------------------------------------------------------
def t_matrix():
    section("===== escape matrix =====")
    from markupsafe import escape
    from html import unescape
    chars = "<>&'\""
    e = str(escape(chars))
    eq("all five escaped", e, "&lt;&gt;&amp;&#39;&#34;")
    eq("round trip", unescape(e), chars)


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import + C speedups", t_import),
        ("escape()", t_escape),
        ("Markup class", t_markup),
        ("escape_silent + soft_str", t_silent_soft),
        ("escape matrix", t_matrix),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
