#!/usr/bin/env python3
"""
Test_pycurl.py - on-device validation for the pycurl wheel.

Exercises the C extension (_pycurl) through the public API.
Exit code 0 = all tests passed.

Generated by RIMI
"""
import os
import sys
import tempfile

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


# ---------------------------------------------------------------------------
# 1. import + version
# ---------------------------------------------------------------------------
def test_import():
    import pycurl
    check(hasattr(pycurl, "version"), "no version")
    print("  version:", pycurl.version)
    print("  version_info:", pycurl.version_info())


def test_c_extension():
    import _pycurl
    check(hasattr(_pycurl, "Curl"), "no Curl in _pycurl")


# ---------------------------------------------------------------------------
# 2. Curl object creation
# ---------------------------------------------------------------------------
def test_curl_create():
    import pycurl
    c = pycurl.Curl()
    check(c is not None, "Curl() returned None")
    check(isinstance(c, pycurl.Curl), "wrong type")
    c.close()


def test_curl_version_info():
    import pycurl
    info = pycurl.version_info()
    check(isinstance(info, tuple), "not tuple")
    check(len(info) >= 5, "too short")
    print("  ssl_backend:", info[4])


def test_curl_easy_options():
    import pycurl
    c = pycurl.Curl()
    # Test setting basic options
    c.setopt(pycurl.CONNECTTIMEOUT, 5)
    c.setopt(pycurl.TIMEOUT, 10)
    c.close()


# ---------------------------------------------------------------------------
# 3. HTTP operations
# ---------------------------------------------------------------------------
def test_perform_http():
    import pycurl
    c = pycurl.Curl()
    buf = []
    c.setopt(c.URL, "http://httpbin.org/get")
    c.setopt(c.WRITEFUNCTION, buf.append)
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 10)
    try:
        c.perform()
        code = c.getinfo(pycurl.RESPONSE_CODE)
        check(200 <= code < 400, "HTTP %d" % code)
        body = "".join(buf)
        check("httpbin" in body.lower() or "headers" in body.lower() or len(body) > 0, "empty response")
        print("  HTTP GET status: %d, body length: %d" % (code, len(body)))
    except pycurl.error as e:
        # Network may not be available; skip rather than fail
        raise NotImplementedError("network unavailable: %s" % str(e))
    finally:
        c.close()


def test_perform_head():
    import pycurl
    c = pycurl.Curl()
    c.setopt(c.URL, "http://httpbin.org/get")
    c.setopt(c.NOBODY, True)
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 10)
    try:
        c.perform()
        code = c.getinfo(pycurl.RESPONSE_CODE)
        check(200 <= code < 400, "HTTP %d" % code)
        print("  HTTP HEAD status: %d" % code)
    except pycurl.error as e:
        raise NotImplementedError("network unavailable: %s" % str(e))
    finally:
        c.close()


# ---------------------------------------------------------------------------
# 4. write-to-file
# ---------------------------------------------------------------------------
def test_write_to_file():
    import pycurl
    c = pycurl.Curl()
    c.setopt(c.URL, "http://httpbin.org/get")
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 10)
    tmpf = tempfile.NamedTemporaryFile(delete=False, suffix=".txt")
    tmpf.close()
    try:
        with open(tmpf.name, "w") as fh:
            c.setopt(c.WRITEDATA, fh)
            try:
                c.perform()
                code = c.getinfo(pycurl.RESPONSE_CODE)
                check(200 <= code < 400, "HTTP %d" % code)
                size = os.path.getsize(tmpf.name)
                check(size > 0, "empty file")
                print("  write-to-file: %d bytes" % size)
            except pycurl.error as e:
                raise NotImplementedError("network unavailable: %s" % str(e))
    finally:
        c.close()
        os.unlink(tmpf.name)


# ---------------------------------------------------------------------------
# 5. getinfo
# ---------------------------------------------------------------------------
def test_getinfo():
    import pycurl
    c = pycurl.Curl()
    c.setopt(c.URL, "http://httpbin.org/get")
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 10)
    try:
        c.perform()
        # All these should return without error
        c.getinfo(pycurl.RESPONSE_CODE)
        c.getinfo(pycurl.EFFECTIVE_URL)
        c.getinfo(pycurl.TOTAL_TIME)
        c.getinfo(pycurl.NAMELOOKUP_TIME)
        c.getinfo(pycurl.CONNECT_TIME)
        c.getinfo(pycurl.SIZE_DOWNLOAD)
        c.getinfo(pycurl.CONTENT_TYPE)
        print("  getinfo: all info fields accessible")
    except pycurl.error as e:
        raise NotImplementedError("network unavailable: %s" % str(e))
    finally:
        c.close()


# ---------------------------------------------------------------------------
# 6. reset
# ---------------------------------------------------------------------------
def test_reset():
    import pycurl
    c = pycurl.Curl()
    c.setopt(c.URL, "http://example.com")
    c.reset()
    # After reset, options should be cleared
    c.close()
    print("  reset: OK")


# ---------------------------------------------------------------------------
# 7. SSL info
# ---------------------------------------------------------------------------
def test_ssl_verification():
    import pycurl
    c = pycurl.Curl()
    c.setopt(c.URL, "https://httpbin.org/get")
    c.setopt(c.CONNECTTIMEOUT, 5)
    c.setopt(c.TIMEOUT, 10)
    try:
        c.perform()
        ssl = c.getinfo(pycurl.SSL_VERIFYRESULT)
        print("  SSL verify result:", ssl)
    except pycurl.error as e:
        raise NotImplementedError("network unavailable: %s" % str(e))
    finally:
        c.close()


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    section("1. import + C extension")
    test("import pycurl", test_import)
    test("C extension loaded", test_c_extension)

    section("2. Curl object")
    test("Curl create", test_curl_create)
    test("version_info tuple", test_curl_version_info)
    test("easy setopt", test_curl_easy_options)

    section("3. HTTP operations")
    test("HTTP GET", test_perform_http)
    test("HTTP HEAD", test_perform_head)

    section("4. write to file")
    test("WRITEDATA file", test_write_to_file)

    section("5. getinfo")
    test("getinfo fields", test_getinfo)

    section("6. reset")
    test("Curl reset", test_reset)

    section("7. SSL")
    test("SSL verification", test_ssl_verification)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
