"""
On-device verification for the cross-compiled cbor2 wheel (Rust/PyO3).

Run after installing:
    pip install cbor2-<ver>-cp312-cp312-android_24_<ABI>.whl
        where <ABI> = arm64_v8a (real device) or x86_64 (emulator)

Usage:
    python Test_cbor2.py [--quick]

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys
import math

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_cbor2():
    import cbor2
    print("    cbor2", cbor2.__version__)
    assert isinstance(cbor2.__version__, str)


def import_submodules():
    import cbor2
    assert hasattr(cbor2, "dumps")
    assert hasattr(cbor2, "loads")
    assert hasattr(cbor2, "dump")
    assert hasattr(cbor2, "load")
    print("    core functions OK")


# ---------------------------------------------------------------------------
# 2. encode / decode integers
# ---------------------------------------------------------------------------
def roundtrip_int():
    import cbor2
    for v in (0, 1, -1, 23, 24, 255, 256, 65535, 65536, 2**32 - 1, -(2**32)):
        data = cbor2.dumps(v)
        assert cbor2.loads(data) == v, "failed for %d" % v


# ---------------------------------------------------------------------------
# 3. encode / decode strings
# ---------------------------------------------------------------------------
def roundtrip_str():
    import cbor2
    for s in ("", "hello", "h\u00e9llo", "\u00e9\u00e8\u00ea", "x" * 10000):
        data = cbor2.dumps(s)
        assert cbor2.loads(data) == s


# ---------------------------------------------------------------------------
# 4. encode / decode bytes
# ---------------------------------------------------------------------------
def roundtrip_bytes():
    import cbor2
    for b in (b"", b"\x00", b"\xff" * 256, b"hello world"):
        data = cbor2.dumps(b)
        result = cbor2.loads(data)
        assert result == b


# ---------------------------------------------------------------------------
# 5. encode / decode booleans
# ---------------------------------------------------------------------------
def roundtrip_bool():
    import cbor2
    for v in (True, False, None):
        data = cbor2.dumps(v)
        assert cbor2.loads(data) is v


# ---------------------------------------------------------------------------
# 6. encode / decode float
# ---------------------------------------------------------------------------
def roundtrip_float():
    import cbor2
    for v in (0.0, 1.5, -1.5, 3.14159, float("inf"), float("-inf")):
        data = cbor2.dumps(v)
        result = cbor2.loads(data)
        assert result == v, "failed for %s" % v


def roundtrip_float_nan():
    import cbor2
    data = cbor2.dumps(float("nan"))
    result = cbor2.loads(data)
    assert math.isnan(result)


# ---------------------------------------------------------------------------
# 7. encode / decode list
# ---------------------------------------------------------------------------
def roundtrip_list():
    import cbor2
    for lst in ([], [1, 2, 3], ["a", "b", "c"], [True, None, 42]):
        data = cbor2.dumps(lst)
        assert cbor2.loads(data) == lst


# ---------------------------------------------------------------------------
# 8. encode / decode dict
# ---------------------------------------------------------------------------
def roundtrip_dict():
    import cbor2
    for d in ({}, {"a": 1}, {"key": "value", "num": 42}):
        data = cbor2.dumps(d)
        assert cbor2.loads(data) == d


# ---------------------------------------------------------------------------
# 9. nested structures
# ---------------------------------------------------------------------------
def roundtrip_nested():
    import cbor2
    obj = {
        "users": [
            {"name": "Alice", "scores": [100, 200, 300]},
            {"name": "Bob", "scores": [50, 75]},
        ],
        "meta": {"count": 2, "version": "1.0"},
    }
    data = cbor2.dumps(obj)
    result = cbor2.loads(data)
    assert result == obj


# ---------------------------------------------------------------------------
# 10. tuple as CBOR array
# ---------------------------------------------------------------------------
def roundtrip_tuple():
    import cbor2
    t = (1, 2, 3)
    data = cbor2.dumps(t)
    result = cbor2.loads(data)
    assert result == list(t)


# ---------------------------------------------------------------------------
# 11. set encoding
# ---------------------------------------------------------------------------
def roundtrip_set():
    import cbor2
    s = {1, 2, 3}
    data = cbor2.dumps(s)
    result = cbor2.loads(data)
    assert set(result) == s


# ---------------------------------------------------------------------------
# 12. OrderedDict
# ---------------------------------------------------------------------------
def roundtrip_ordereddict():
    from collections import OrderedDict
    import cbor2
    od = OrderedDict([("b", 2), ("a", 1)])
    data = cbor2.dumps(od)
    result = cbor2.loads(data)
    assert isinstance(result, dict)
    assert result == od


# ---------------------------------------------------------------------------
# 13. datetime
# ---------------------------------------------------------------------------
def roundtrip_datetime():
    import cbor2
    from datetime import datetime, timezone
    dt = datetime(2026, 1, 15, 12, 30, 45, tzinfo=timezone.utc)
    data = cbor2.dumps(dt)
    result = cbor2.loads(data)
    assert result.year == 2026
    assert result.month == 1
    assert result.day == 15


# ---------------------------------------------------------------------------
# 14. Decimal
# ---------------------------------------------------------------------------
def roundtrip_decimal():
    from decimal import Decimal
    import cbor2
    d = Decimal("3.14159")
    data = cbor2.dumps(d)
    result = cbor2.loads(data)
    assert result == d


# ---------------------------------------------------------------------------
# 15. Tag
# ---------------------------------------------------------------------------
def roundtrip_tag():
    import cbor2
    tag = cbor2.CBORTag(1, "2026-01-15")
    data = cbor2.dumps(tag)
    result = cbor2.loads(data)
    assert result.tag == 1
    assert result.value == "2026-01-15"


# ---------------------------------------------------------------------------
# 16. CBOR tag with URL
# ---------------------------------------------------------------------------
def tag_url():
    import cbor2
    tag = cbor2.CBORTag(32, "https://example.com")
    data = cbor2.dumps(tag)
    result = cbor2.loads(data)
    assert result.tag == 32
    assert result.value == "https://example.com"


# ---------------------------------------------------------------------------
# 17. Binary roundtrip
# ---------------------------------------------------------------------------
def binary_roundtrip():
    import cbor2
    original = {"data": b"\x00\x01\x02\xff", "count": 10}
    encoded = cbor2.dumps(original)
    decoded = cbor2.loads(encoded)
    assert decoded == original


# ---------------------------------------------------------------------------
# 18. Large integer
# ---------------------------------------------------------------------------
def roundtrip_large_int():
    import cbor2
    big = 2**128
    data = cbor2.dumps(big)
    assert cbor2.loads(data) == big
    big_neg = -(2**128)
    data = cbor2.dumps(big_neg)
    assert cbor2.loads(data) == big_neg


# ---------------------------------------------------------------------------
# 19. CBOR canonical / sorted keys
# ---------------------------------------------------------------------------
def sorted_keys():
    import cbor2
    d = {"z": 1, "a": 2, "m": 3}
    data = cbor2.dumps(d, sort_keys=True)
    result = cbor2.loads(data)
    assert result == d


# ---------------------------------------------------------------------------
# 20. dumps to bytes
# ---------------------------------------------------------------------------
def dumps_returns_bytes():
    import cbor2
    data = cbor2.dumps(42)
    assert isinstance(data, bytes)


# ---------------------------------------------------------------------------
# 21. dump / load with file
# ---------------------------------------------------------------------------
def dump_load_file():
    import cbor2
    import tempfile
    import os
    obj = {"key": [1, 2, 3]}
    path = os.path.join(tempfile.gettempdir(), "test_cbor2.bin")
    with open(path, "wb") as f:
        cbor2.dump(obj, f)
    with open(path, "rb") as f:
        result = cbor2.load(f)
    assert result == obj
    os.remove(path)


# ---------------------------------------------------------------------------
# 22. payload size estimation
# ---------------------------------------------------------------------------
def encode_size():
    import cbor2
    small = cbor2.dumps(0)
    medium = cbor2.dumps(1000)
    large = cbor2.dumps(1000000)
    assert len(small) <= len(medium) <= len(large)


# ---------------------------------------------------------------------------
# 23. decode from raw bytes
# ---------------------------------------------------------------------------
def decode_raw_bytes():
    import cbor2
    # manually encoded: 24 (major type 0, value 24 = 0x18 0x18)
    raw = bytes([0x18, 0x18])
    assert cbor2.loads(raw) == 24


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. cbor2 import / version")
    test("import cbor2", import_cbor2)
    test("core functions available", import_submodules)

    section("2. integers")
    test("roundtrip int (various sizes)", roundtrip_int)

    section("3. strings")
    test("roundtrip str (unicode, empty, long)", roundtrip_str)

    section("4. bytes")
    test("roundtrip bytes", roundtrip_bytes)

    section("5. booleans / None")
    test("roundtrip True, False, None", roundtrip_bool)

    section("6. floats")
    test("roundtrip float (+inf, -inf)", roundtrip_float)
    test("roundtrip float NaN", roundtrip_float_nan)

    section("7. lists")
    test("roundtrip list", roundtrip_list)

    section("8. dicts")
    test("roundtrip dict", roundtrip_dict)

    section("9. nested structures")
    test("roundtrip nested dict+list", roundtrip_nested)

    section("10. tuples / sets")
    test("tuple -> CBOR array", roundtrip_tuple)
    test("set roundtrip", roundtrip_set)

    section("11. collections")
    test("OrderedDict roundtrip", roundtrip_ordereddict)

    section("12. datetime / Decimal / Tag")
    test("datetime roundtrip", roundtrip_datetime)
    test("Decimal roundtrip", roundtrip_decimal)
    test("CBORTag roundtrip", roundtrip_tag)
    test("CBORTag URL (tag 32)", tag_url)

    section("13. binary and large ints")
    test("binary roundtrip", binary_roundtrip)
    test("large int (2^128)", roundtrip_large_int)

    section("14. sorting / canonical")
    test("sorted keys encoding", sorted_keys)

    section("15. output types")
    test("dumps returns bytes", dumps_returns_bytes)

    section("16. file I/O")
    test("dump/load file roundtrip", dump_load_file)

    section("17. encoding size")
    test("small/medium/large payload sizes", encode_size)

    section("18. raw byte decode")
    test("decode raw CBOR bytes", decode_raw_bytes)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
