"""
On-device verification for the cross-compiled hiredis 3.4.1 wheel.

hiredis is a minimal C wrapper around the hiredis C library. It supplies the
RESP protocol reader + command packer used by redis-py (fast path). The native
extension is hiredis/hiredis.cpython-312.so; without it redis imports fall back
to the slow pure-Python parser.

No runtime deps. requires-python >=3.8.

Usage:
    python Test_hiredis.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


def reader():
    return __import__("hiredis").Reader()


# ---------------------------------------------------------------------------
# 1. import surface + version + native extension active
# ---------------------------------------------------------------------------
def t_import():
    import hiredis
    import hiredis.hiredis as ext
    section("===== import =====")
    print("hiredis:", hiredis.__file__)
    eq("version", hiredis.__version__, "3.4.1")
    eq("native ext", True, ext.__file__.endswith(".so")
       or ext.__file__.endswith(".pyd"))
    eq("hiredis submodule", True, hasattr(hiredis, "hiredis"))
    for name in ("Reader", "ReplyError", "ProtocolError", "HiredisError",
                 "pack_command"):
        eq("exports %s" % name, True, hasattr(hiredis, name))


# ---------------------------------------------------------------------------
# 2. basic RESP2 replies
# ---------------------------------------------------------------------------
def t_resp2():
    import hiredis
    section("===== RESP2 replies =====")
    r = reader()
    r.feed(b"*3\r\n$3\r\nfoo\r\n:5\r\n$-1\r\n")
    eq("array w/ null elem", r.gets(), [b"foo", 5, None])
    eq("bulk string", single(b"$3\r\nbar\r\n"), b"bar")
    eq("empty bulk", single(b"$0\r\n\r\n"), b"")
    eq("integer", single(b":42\r\n"), 42)
    eq("status", single(b"+OK\r\n"), b"OK")
    eq("null", single(b"_\r\n"), None)
    eq("empty array", single(b"*0\r\n"), [])
    eq("nested array", single(b"*2\r\n*1\r\n:1\r\n*0\r\n"), [[1], []])


def single(data):
    r = reader()
    r.feed(data)
    return r.gets()


# ---------------------------------------------------------------------------
# 3. error replies vs protocol errors
# ---------------------------------------------------------------------------
def t_errors():
    import hiredis
    section("===== errors =====")
    r = reader()
    r.feed(b"-ERR boom\r\n")
    v = r.gets()
    eq("error is ReplyError", True, isinstance(v, hiredis.ReplyError))
    eq("ReplyError is HiredisError", True,
       isinstance(v, hiredis.HiredisError))
    eq("error message", str(v), "ERR boom")
    eq("error args", v.args, ("ERR boom",))
    try:
        single(b"@garbage\r\n")
        raise AssertionError("garbage reply type did not raise")
    except hiredis.ProtocolError:
        pass


# ---------------------------------------------------------------------------
# 4. incremental / streaming feed
# ---------------------------------------------------------------------------
def t_incremental():
    import hiredis
    section("===== incremental feed =====")
    r = reader()
    r.feed(b"*2\r\n$3\r\nfo")
    eq("partial len>0", True, r.len() > 0)
    eq("partial no reply", r.gets(), False)
    r.feed(b"o\r\n:1\r\n")
    eq("assembled", r.gets(), [b"foo", 1])
    eq("has_data after", r.has_data(), False)
    eq("gets on empty", r.gets(), False)
    # two replies buffered at once
    r.feed(b":1\r\n:2\r\n")
    eq("multi reply 1", r.gets(), 1)
    eq("multi reply 2", r.gets(), 2)


# ---------------------------------------------------------------------------
# 5. extended reply types (double, bool, big int, binary)
# ---------------------------------------------------------------------------
def t_extended():
    section("===== extended types =====")
    eq("double", single(b",2.5\r\n"), 2.5)
    eq("bool t", single(b"#t\r\n"), True)
    eq("bool f", single(b"#f\r\n"), False)
    eq("big int -> bytes", single(b"(12345678901234567890\r\n"),
       b"12345678901234567890")
    eq("binary bulk", single(b"$4\r\n\x00\x01\x02\xff\r\n"),
       b"\x00\x01\x02\xff")


# ---------------------------------------------------------------------------
# 6. pack_command
# ---------------------------------------------------------------------------
def t_pack():
    import hiredis
    section("===== pack_command =====")
    eq("simple", hiredis.pack_command(("SET", "k", "v")),
       b"*3\r\n$3\r\nSET\r\n$1\r\nk\r\n$1\r\nv\r\n")
    eq("space in arg", hiredis.pack_command(("SET", "k", "hello world")),
       b"*3\r\n$3\r\nSET\r\n$1\r\nk\r\n$11\r\nhello world\r\n")
    eq("bytes args", hiredis.pack_command((b"SET", b"k", b"v")),
       b"*3\r\n$3\r\nSET\r\n$1\r\nk\r\n$1\r\nv\r\n")
    eq("empty", hiredis.pack_command(()), b"*0\r\n")


# ---------------------------------------------------------------------------
# 7. set_encoding + buffer limits
# ---------------------------------------------------------------------------
def t_encoding():
    import hiredis
    section("===== encoding / buffer limits =====")
    r = reader()
    r.set_encoding("utf-8")
    r.feed(b"$5\r\nhello\r\n")
    eq("encoded str", r.gets(), "hello")
    eq("maxbuf round trip", r.setmaxbuf(r.getmaxbuf()), None)
    eq("maxbuf default", True, r.getmaxbuf() > 0)


# ---------------------------------------------------------------------------
# 8. stress: many pipelined replies round trip
# ---------------------------------------------------------------------------
def t_stress():
    section("===== stress =====")
    r = reader()
    parts = []
    for i in range(500):
        s = b"item%d" % i
        parts.append(b"$%d\r\n%s\r\n" % (len(s), s))
    blob = b"".join(parts) + b":999\r\n"
    r.feed(blob)
    ok = True
    for i in range(500):
        if r.gets() != b"item%d" % i:
            ok = False
            break
    eq("500 bulks", ok, True)
    eq("trailing int", r.gets(), 999)
    eq("exhausted", r.gets(), False)
    # a deep nested array
    inner = b":1\r\n"
    for _ in range(50):
        inner = b"*1\r\n" + inner
    eq("deep nesting", True, isinstance(single(inner), list))
    deep = single(inner)
    depth = 0
    while isinstance(deep, list):
        depth += 1
        deep = deep[0]
    eq("deep depth 50", depth, 50)
    eq("deep leaf", deep, 1)


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import surface", t_import),
        ("RESP2 replies", t_resp2),
        ("error replies vs protocol errors", t_errors),
        ("incremental feed", t_incremental),
        ("extended reply types", t_extended),
        ("pack_command", t_pack),
        ("encoding + buffer limits", t_encoding),
        ("stress", t_stress),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
