"""
Test script for uvloop on Android Python STB
Device test: validates import, single extension module, event loop functionality.

Generated by RIMI
"""

import sys
import time
import platform

RESULTS = []

def section(name):
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

def test(name, func):
    global RESULTS
    try:
        result = func()
        RESULTS.append((name, "PASS", result if result else ""))
        print(f"  [PASS] {name}")
    except Exception as e:
        RESULTS.append((name, "FAIL", str(e)))
        print(f"  [FAIL] {name}: {e}")

def test():
    section("Environment")
    print(f"  Python: {sys.version}")
    print(f"  Platform: {platform.platform()}")
    print(f"  Arch: {platform.machine()}")

    # --- Core Import ---
    section("Core Import")
    test("import uvloop", lambda: __import__("uvloop"))
    test("uvloop.__version__", lambda: __import__("uvloop").__version__)

    # --- Extension Module ---
    section("Extension Module")
    test("uvloop.loop module", lambda: __import__("uvloop.loop"))
    test("loop.cpython-312-aarch64-linux-gnu.so exists",
         lambda: hasattr(__import__("uvloop.loop", fromlist=["loop"]), "loop"))

    # --- libuv ---
    section("libuv (static)")
    test("uvloop._is_uvloop (C extension check)",
         lambda: getattr(__import__("uvloop"), "__uvloop__", False) or
                 hasattr(__import__("uvloop"), "install"))

    # --- Event Loop Installation ---
    section("Event Loop Installation")
    test("uvloop.install()",
         lambda: __import__("uvloop").install() or "installed")

    def test_get_event_loop():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        assert loop is not None
        assert "uvloop" in type(loop).__module__
        asyncio.set_event_loop(loop)
        loop.close()
        return f"loop type: {type(loop).__module__}"

    test("uvloop event loop created", test_get_event_loop)

    # --- Async Functionality ---
    section("Async Functionality")

    def test_async_simple():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def coro():
            return 42
        result = loop.run_until_complete(coro())
        loop.close()
        assert result == 42
        return f"coroutine result: {result}"

    test("simple coroutine", test_async_simple)

    def test_async_sleep():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def coro():
            await asyncio.sleep(0.01)
            return "slept"
        result = loop.run_until_complete(coro())
        loop.close()
        assert result == "slept"
        return "asyncio.sleep(0.01) OK"

    test("asyncio.sleep", test_async_sleep)

    def test_async_wait_for():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def slow():
            await asyncio.sleep(10)
            return "slow"
        async def fast():
            return "fast"
        result = loop.run_until_complete(
            asyncio.wait_for(fast(), timeout=1.0)
        )
        loop.close()
        assert result == "fast"
        return "wait_for timeout OK"

    test("asyncio.wait_for", test_async_wait_for)

    def test_async_gather():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def task(n):
            await asyncio.sleep(0.01)
            return n * 2
        results = loop.run_until_complete(
            asyncio.gather(task(1), task(2), task(3))
        )
        loop.close()
        assert results == [2, 4, 6]
        return f"gather results: {results}"

    test("asyncio.gather", test_async_gather)

    def test_async_create_task():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        results = []
        async def worker(name):
            await asyncio.sleep(0.01)
            results.append(name)
        async def main():
            tasks = [asyncio.create_task(worker(f"t{i}")) for i in range(5)]
            await asyncio.gather(*tasks)
        loop.run_until_complete(main())
        loop.close()
        assert len(results) == 5
        return f"tasks completed: {len(results)}"

    test("asyncio.create_task", test_async_create_task)

    def test_async_queue():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def producer_consumer():
            queue = asyncio.Queue()
            for i in range(10):
                await queue.put(i)
            total = 0
            while not queue.empty():
                total += await queue.get()
            return total
        result = loop.run_until_complete(producer_consumer())
        loop.close()
        assert result == 45
        return f"queue sum: {result}"

    test("asyncio.Queue", test_async_queue)

    def test_async_event():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        event = asyncio.Event()
        results = []
        async def waiter():
            await event.wait()
            results.append("done")
        async def setter():
            await asyncio.sleep(0.01)
            event.set()
        async def main():
            w = asyncio.create_task(waiter())
            s = asyncio.create_task(setter())
            await asyncio.gather(w, s)
        loop.run_until_complete(main())
        loop.close()
        assert results == ["done"]
        return "Event set/wait OK"

    test("asyncio.Event", test_async_event)

    def test_async_lock():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        lock = asyncio.Lock()
        results = []
        async def worker(name):
            async with lock:
                results.append(name)
                await asyncio.sleep(0.01)
        async def main():
            await asyncio.gather(
                worker("a"), worker("b"), worker("c")
            )
        loop.run_until_complete(main())
        loop.close()
        assert len(results) == 3
        return f"lock order: {results}"

    test("asyncio.Lock", test_async_lock)

    # --- Speed Comparison ---
    section("Performance")

    def test_event_loop_speed():
        import asyncio
        __import__("uvloop").install()
        loop = asyncio.new_event_loop()
        async def noop():
            pass
        start = time.perf_counter()
        for _ in range(10000):
            loop.run_until_complete(noop())
        elapsed = time.perf_counter() - start
        loop.close()
        ops_per_sec = 10000 / elapsed
        return f"{ops_per_sec:.0f} loops/sec, {elapsed:.3f}s total"

    test("10000 event loop iterations", test_event_loop_speed)

    # --- Summary ---
    section("SUMMARY")
    passed = sum(1 for _, status, _ in RESULTS if status == "PASS")
    failed = sum(1 for _, status, _ in RESULTS if status == "FAIL")
    total = len(RESULTS)
    print(f"  Total: {total} | Passed: {passed} | Failed: {failed}")
    if failed > 0:
        print(f"\n  Failed tests:")
        for name, status, msg in RESULTS:
            if status == "FAIL":
                print(f"    - {name}: {msg}")
    print(f"\n  {'ALL TESTS PASSED' if failed == 0 else 'SOME TESTS FAILED'}")
    return failed == 0


if __name__ == "__main__":
    ok = test()
    sys.exit(0 if ok else 1)
