"""
On-device verification for the cross-compiled duckdb wheel (C++ / pybind11).

Run after installing:
    pip install duckdb-<ver>-cp312-cp312-android_24_<ABI>.whl
        where <ABI> = arm64_v8a (real device) or x86_64 (emulator)

Usage:
    python Test_duckdb.py [--quick]

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import os
import sys
import tempfile

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


WORKDIR = None


def workdir():
    global WORKDIR
    if WORKDIR is None:
        candidates = [os.environ.get("TMPDIR") or "", tempfile.gettempdir(),
                      "/storage/emulated/0/Download", os.getcwd()]
        for base in candidates:
            if not base:
                continue
            try:
                d = os.path.join(base, "test_duckdb_tmp")
                os.makedirs(d, exist_ok=True)
                with open(os.path.join(d, "_probe"), "w") as fh:
                    fh.write("ok")
                WORKDIR = d
                break
            except OSError:
                continue
        if WORKDIR is None:
            WORKDIR = "."
    return WORKDIR


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_duckdb():
    import duckdb
    print("    duckdb", duckdb.__version__)
    assert isinstance(duckdb.__version__, str)


def version_tuple():
    import duckdb
    v = getattr(duckdb, "__version_tuple__", None)
    if v is None:
        parts = tuple(int(x) for x in duckdb.__version__.split(".")[:3])
        v = parts
        print("    version_tuple (derived):", v)
    else:
        print("    version_tuple:", v)
    assert isinstance(v, tuple)
    assert len(v) >= 2


# ---------------------------------------------------------------------------
# 2. connect
# ---------------------------------------------------------------------------
def connect_memory():
    import duckdb
    con = duckdb.connect(":memory:")
    assert con is not None
    con.close()


def connect_database():
    import duckdb
    path = os.path.join(workdir(), "test.duckdb")
    con = duckdb.connect(path)
    assert con is not None
    con.close()
    if os.path.exists(path):
        os.remove(path)


# ---------------------------------------------------------------------------
# 3. CREATE TABLE / INSERT / SELECT
# ---------------------------------------------------------------------------
def create_insert_select():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER, name VARCHAR, value DOUBLE)")
    con.execute("INSERT INTO t VALUES (1, 'alice', 1.0)")
    con.execute("INSERT INTO t VALUES (2, 'bob', 2.5)")
    result = con.execute("SELECT * FROM t ORDER BY id").fetchall()
    assert result == [(1, "alice", 1.0), (2, "bob", 2.5)]
    con.close()


# ---------------------------------------------------------------------------
# 4. fetchdf / fetchall / fetchone / fetchmany
# ---------------------------------------------------------------------------
def fetch_methods():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER, name VARCHAR)")
    for i in range(10):
        con.execute("INSERT INTO t VALUES (?, ?)", [i, "name_%d" % i])
    rows = con.execute("SELECT * FROM t ORDER BY id").fetchall()
    assert len(rows) == 10
    assert rows[0] == (0, "name_0")
    assert rows[9] == (9, "name_9")
    con.close()


def fetchmany():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    for i in range(5):
        con.execute("INSERT INTO t VALUES (?)", [i])
    cur = con.execute("SELECT * FROM t ORDER BY id")
    batch = cur.fetchmany(3)
    assert len(batch) == 3
    con.close()


# ---------------------------------------------------------------------------
# 5. execute with parameters
# ---------------------------------------------------------------------------
def parameterized_query():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER, name VARCHAR)")
    con.execute("INSERT INTO t VALUES (?, ?)", [1, "test"])
    result = con.execute("SELECT * FROM t WHERE id = ?", [1]).fetchall()
    assert result == [(1, "test")]
    con.close()


# ---------------------------------------------------------------------------
# 6. transactions
# ---------------------------------------------------------------------------
def transactions():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    con.execute("BEGIN TRANSACTION")
    con.execute("INSERT INTO t VALUES (1)")
    con.execute("COMMIT")
    result = con.execute("SELECT COUNT(*) FROM t").fetchone()
    assert result[0] == 1
    con.execute("BEGIN TRANSACTION")
    con.execute("INSERT INTO t VALUES (2)")
    con.execute("ROLLBACK")
    result = con.execute("SELECT COUNT(*) FROM t").fetchone()
    assert result[0] == 1
    con.close()


# ---------------------------------------------------------------------------
# 7. aggregate functions
# ---------------------------------------------------------------------------
def aggregates():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(val DOUBLE)")
    for v in [1.0, 2.0, 3.0, 4.0, 5.0]:
        con.execute("INSERT INTO t VALUES (?)", [v])
    avg = con.execute("SELECT AVG(val) FROM t").fetchone()[0]
    assert abs(avg - 3.0) < 1e-10
    total = con.execute("SELECT SUM(val) FROM t").fetchone()[0]
    assert abs(total - 15.0) < 1e-10
    cnt = con.execute("SELECT COUNT(*) FROM t").fetchone()[0]
    assert cnt == 5
    con.close()


# ---------------------------------------------------------------------------
# 8. GROUP BY / HAVING
# ---------------------------------------------------------------------------
def group_by():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(cat VARCHAR, val INTEGER)")
    for cat, val in [("a", 1), ("a", 2), ("b", 3), ("b", 4), ("b", 5)]:
        con.execute("INSERT INTO t VALUES (?, ?)", [cat, val])
    result = con.execute(
        "SELECT cat, SUM(val), COUNT(*) FROM t GROUP BY cat ORDER BY cat"
    ).fetchall()
    assert result == [("a", 3, 2), ("b", 12, 3)]
    con.close()


# ---------------------------------------------------------------------------
# 9. JOIN
# ---------------------------------------------------------------------------
def inner_join():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE a(id INTEGER, name VARCHAR)")
    con.execute("CREATE TABLE b(id INTEGER, score DOUBLE)")
    con.execute("INSERT INTO a VALUES (1, 'alice'), (2, 'bob')")
    con.execute("INSERT INTO b VALUES (1, 95.0), (2, 87.0)")
    result = con.execute(
        "SELECT a.name, b.score FROM a INNER JOIN b ON a.id = b.id ORDER BY a.name"
    ).fetchall()
    assert result == [("alice", 95.0), ("bob", 87.0)]
    con.close()


# ---------------------------------------------------------------------------
# 10. window functions
# ---------------------------------------------------------------------------
def window_functions():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(dept VARCHAR, salary INTEGER)")
    for dept, sal in [("a", 100), ("a", 200), ("b", 150), ("b", 300)]:
        con.execute("INSERT INTO t VALUES (?, ?)", [dept, sal])
    result = con.execute(
        "SELECT dept, salary, RANK() OVER (PARTITION BY dept ORDER BY salary) FROM t ORDER BY dept, salary"
    ).fetchall()
    assert len(result) == 4
    con.close()


# ---------------------------------------------------------------------------
# 11. CREATE VIEW
# ---------------------------------------------------------------------------
def create_view():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER, name VARCHAR)")
    con.execute("INSERT INTO t VALUES (1, 'alice')")
    con.execute("CREATE VIEW v AS SELECT * FROM t")
    result = con.execute("SELECT * FROM v").fetchall()
    assert result == [(1, "alice")]
    con.close()


# ---------------------------------------------------------------------------
# 12. subquery
# ---------------------------------------------------------------------------
def subquery():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER, name VARCHAR)")
    con.execute("INSERT INTO t VALUES (1, 'alice'), (2, 'bob')")
    result = con.execute(
        "SELECT * FROM t WHERE id IN (SELECT id FROM t WHERE id = 1)"
    ).fetchall()
    assert result == [(1, "alice")]
    con.close()


# ---------------------------------------------------------------------------
# 13. DATE / TIMESTAMP types
# ---------------------------------------------------------------------------
def date_types():
    import duckdb
    con = duckdb.connect(":memory:")
    result = con.execute("SELECT DATE '2026-01-15'").fetchone()
    assert result is not None
    result = con.execute("SELECT TIMESTAMP '2026-01-15 12:30:00'").fetchone()
    assert result is not None
    con.close()


# ---------------------------------------------------------------------------
# 14. CASE expression
# ---------------------------------------------------------------------------
def case_expression():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    for i in range(5):
        con.execute("INSERT INTO t VALUES (?)", [i])
    result = con.execute(
        "SELECT CASE WHEN id < 2 THEN 'small' WHEN id < 4 THEN 'medium' ELSE 'large' END FROM t ORDER BY id"
    ).fetchall()
    assert result[0] == ("small",)
    assert result[2] == ("medium",)
    assert result[4] == ("large",)
    con.close()


# ---------------------------------------------------------------------------
# 15. DROP TABLE
# ---------------------------------------------------------------------------
def drop_table():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    con.execute("DROP TABLE t")
    try:
        con.execute("SELECT * FROM t")
        assert False, "table should be dropped"
    except Exception:
        pass
    con.close()


# ---------------------------------------------------------------------------
# 16. ALTER TABLE
# ---------------------------------------------------------------------------
def alter_table():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    con.execute("ALTER TABLE t ADD COLUMN name VARCHAR DEFAULT 'x'")
    con.execute("INSERT INTO t VALUES (1, 'y')")
    result = con.execute("SELECT * FROM t").fetchone()
    assert result == (1, "y")
    con.close()


# ---------------------------------------------------------------------------
# 17. EXPLAIN
# ---------------------------------------------------------------------------
def explain():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    result = con.execute("EXPLAIN SELECT * FROM t").fetchall()
    assert len(result) > 0
    con.close()


# ---------------------------------------------------------------------------
# 18. fetchdf -> pandas-like DataFrame
# ---------------------------------------------------------------------------
def fetchdf():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(a INTEGER, b VARCHAR)")
    con.execute("INSERT INTO t VALUES (1, 'x'), (2, 'y')")
    df = con.execute("SELECT * FROM t ORDER BY a").fetchdf()
    assert df is not None
    assert hasattr(df, "columns")
    assert list(df.columns) == ["a", "b"]
    con.close()


# ---------------------------------------------------------------------------
# 19. fetch_arrow_table (if pyarrow available)
# ---------------------------------------------------------------------------
def fetch_arrow():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(a INTEGER)")
    con.execute("INSERT INTO t VALUES (1), (2), (3)")
    try:
        at = con.execute("SELECT * FROM t").fetch_arrow_table()
        assert at is not None
    except Exception:
        raise NotImplementedError("pyarrow not installed")


# ---------------------------------------------------------------------------
# 20. list_tables
# ---------------------------------------------------------------------------
def list_tables():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE a(id INTEGER)")
    con.execute("CREATE TABLE b(id INTEGER)")
    tables = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='main'").fetchall()
    names = sorted([t[0] for t in tables])
    assert "a" in names
    assert "b" in names
    con.close()


# ---------------------------------------------------------------------------
# 21. array type
# ---------------------------------------------------------------------------
def array_type():
    import duckdb
    con = duckdb.connect(":memory:")
    result = con.execute("SELECT [1, 2, 3]::INTEGER[]").fetchone()
    assert result[0] == [1, 2, 3]
    con.close()


# ---------------------------------------------------------------------------
# 22. struct type
# ---------------------------------------------------------------------------
def struct_type():
    import duckdb
    con = duckdb.connect(":memory:")
    result = con.execute("SELECT {'x': 1, 'y': 'hello'}").fetchone()
    assert result is not None
    con.close()


# ---------------------------------------------------------------------------
# 23. map type
# ---------------------------------------------------------------------------
def map_type():
    import duckdb
    con = duckdb.connect(":memory:")
    result = con.execute("SELECT map(['a','b'], [1, 2])").fetchone()
    assert result is not None
    con.close()


# ---------------------------------------------------------------------------
# 24. C extension loaded
# ---------------------------------------------------------------------------
def c_extension():
    import duckdb
    assert hasattr(duckdb, "connect")


# ---------------------------------------------------------------------------
# 25. ATTACH database
# ---------------------------------------------------------------------------
def attach_detach():
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("CREATE TABLE t(id INTEGER)")
    con.execute("INSERT INTO t VALUES (1)")
    path = os.path.join(workdir(), "attach_test.duckdb")
    con.execute("ATTACH '%s' AS db2" % path)
    con.execute("CREATE TABLE db2.s(id INTEGER)")
    con.execute("INSERT INTO db2.s VALUES (99)")
    result = con.execute("SELECT * FROM db2.s").fetchone()
    assert result == (99,)
    con.execute("DETACH db2")
    con.close()
    if os.path.exists(path):
        os.remove(path)


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. duckdb import / version")
    test("import duckdb", import_duckdb)
    test("version_tuple", version_tuple)

    section("2. connect")
    test("connect to :memory:", connect_memory)
    test("connect to file", connect_database)

    section("3. CREATE / INSERT / SELECT")
    test("create table, insert, select", create_insert_select)

    section("4. fetch methods")
    test("fetchall (10 rows)", fetch_methods)
    test("fetchmany", fetchmany)

    section("5. parameterized queries")
    test("parameterized query", parameterized_query)

    section("6. transactions")
    test("BEGIN / COMMIT / ROLLBACK", transactions)

    section("7. aggregates")
    test("AVG / SUM / COUNT", aggregates)

    section("8. GROUP BY / HAVING")
    test("group by with aggregation", group_by)

    section("9. JOIN")
    test("INNER JOIN", inner_join)

    section("10. window functions")
    test("RANK() OVER PARTITION", window_functions)

    section("11. VIEW")
    test("CREATE VIEW", create_view)

    section("12. subquery")
    test("subquery IN", subquery)

    section("13. DATE / TIMESTAMP")
    test("date and timestamp types", date_types)

    section("14. CASE expression")
    test("CASE WHEN", case_expression)

    section("15. DDL")
    test("DROP TABLE", drop_table)
    test("ALTER TABLE ADD COLUMN", alter_table)

    section("16. EXPLAIN")
    test("EXPLAIN query", explain)

    section("17. DataFrame output")
    test("fetchdf (DataFrame)", fetchdf)
    test("fetch_arrow_table (optional)", fetch_arrow)

    section("18. schema introspection")
    test("list tables via information_schema", list_tables)

    section("19. complex types")
    test("ARRAY type", array_type)
    test("STRUCT type", struct_type)
    test("MAP type", map_type)

    section("20. C extension")
    test("duckdb C extension loaded", c_extension)

    section("21. ATTACH / DETACH")
    test("attach external database", attach_detach)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
