"""
On-device verification for the cross-compiled msgpack 1.2.1 wheel.

msgpack (MessagePack) is a fast binary serialization format. The native
extension msgpack/_cmsgpack.cpython-312.so is REQUIRED for the fast path -
msgpack prefers it and only falls back to the pure-Python fallback.py when
the .so is missing (e.g. MSGPACK_PUREPYTHON=1).

No runtime deps. requires-python >=3.10.

Usage:
    python Test_msgpack.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


# ---------------------------------------------------------------------------
# 1. import surface + version + C extension active
# ---------------------------------------------------------------------------
def t_import():
    import msgpack
    section("===== import =====")
    print("msgpack:", msgpack.__file__)
    eq("version", msgpack.version, (1, 2, 1))
    # C extension must be the real .so
    import msgpack._cmsgpack as ext
    print("C extension:", ext.__file__)
    eq("ext is compiled", True,
       ext.__file__.endswith(".so") or ext.__file__.endswith(".pyd"))
    for name in ("packb", "unpackb", "Packer", "Unpacker", "ExtType",
                 "Timestamp", "pack", "unpack", "dumps", "loads"):
        eq("exports %s" % name, True, hasattr(msgpack, name))


# ---------------------------------------------------------------------------
# 2. packb / unpackb round trip
# ---------------------------------------------------------------------------
def t_roundtrip():
    import msgpack
    section("===== packb / unpackb =====")
    obj = {"a": 1, "b": [1, 2, None], "c": "x", "d": True}
    eq("round trip", msgpack.unpackb(msgpack.packb(obj)), obj)
    eq("binary is bytes", type(msgpack.packb(obj)).__name__, "bytes")
    eq("dumps/loads", msgpack.loads(msgpack.dumps([1, "a", None])), [1, "a", None])


# ---------------------------------------------------------------------------
# 3. raw=True returns bytes for str-typed msgpack data
# ---------------------------------------------------------------------------
def t_raw():
    import msgpack
    section("===== raw=True =====")
    eq("raw str->bytes", msgpack.unpackb(b"\xa3abc", raw=True), b"abc")
    eq("raw False str", msgpack.unpackb(b"\xa3abc"), "abc")


# ---------------------------------------------------------------------------
# 4. bin type (bytes) round trip (use_bin_type default True)
# ---------------------------------------------------------------------------
def t_bin():
    import msgpack
    section("===== bin type =====")
    b = b"\x00\x01\xff"
    eq("bytes preserved", msgpack.unpackb(msgpack.packb(b)), b)


# ---------------------------------------------------------------------------
# 5. ExtType
# ---------------------------------------------------------------------------
def t_ext():
    import msgpack
    from msgpack import ExtType
    section("===== ExtType =====")
    e = ExtType(42, b"hello")
    eq("ext round trip", msgpack.unpackb(msgpack.packb(e)), e)


# ---------------------------------------------------------------------------
# 6. Timestamp (msgpack timestamp ext)
# ---------------------------------------------------------------------------
def t_timestamp():
    import msgpack
    from msgpack import Timestamp
    section("===== Timestamp =====")
    t = Timestamp(1700000000, 123)
    eq("timestamp round trip", msgpack.unpackb(msgpack.packb(t)), t)
    eq("to_unix", int(t.to_unix()), 1700000000)
    eq("to_datetime", t.to_datetime().year, 2023)
    t2 = Timestamp.from_unix(1700000000)
    eq("from_unix secs", t2.seconds, 1700000000)


# ---------------------------------------------------------------------------
# 7. Packer / Unpacker streaming
# ---------------------------------------------------------------------------
def t_stream():
    import msgpack
    section("===== Packer / Unpacker =====")
    p = msgpack.Packer()
    u = msgpack.Unpacker(raw=False)
    u.feed(p.pack(1))
    u.feed(p.pack("two"))
    u.feed(p.pack({"k": [1, 2, 3]}))
    items = list(u)
    eq("stream items", items, [1, "two", {"k": [1, 2, 3]}])


# ---------------------------------------------------------------------------
# 8. error handling (malformed / truncated buffers)
# ---------------------------------------------------------------------------
def t_errors():
    import msgpack
    section("===== errors =====")
    try:
        msgpack.unpackb(b"\xc1")  # 0xc1 is a never-used byte -> FormatError
        raise AssertionError("bad byte did not raise")
    except msgpack.FormatError:
        pass
    try:
        msgpack.unpackb(b"\x92\x01")  # array(2) but only 1 element -> error
        raise AssertionError("truncated buffer did not raise")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import surface", t_import),
        ("packb/unpackb round trip", t_roundtrip),
        ("raw=True", t_raw),
        ("bin type", t_bin),
        ("ExtType", t_ext),
        ("Timestamp", t_timestamp),
        ("Packer/Unpacker streaming", t_stream),
        ("error handling", t_errors),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
