"""
On-device verification for the cross-compiled matplotlib wheel.

Run after installing:
    pip install matplotlib-<ver>-cp312-cp312-linux_<ABI>.whl

Usage:
    python Test_matplotlib.py [--quick]

Exit code 0 = everything required PASSed.
Requires: numpy, pillow, contourpy, kiwisolver, packaging, pyparsing,
          fonttools, cycler at runtime.

Generated by RIMI
"""
import os
import sys
import tempfile

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


WORKDIR = None


def workdir():
    global WORKDIR
    if WORKDIR is None:
        candidates = [os.environ.get("TMPDIR") or "", tempfile.gettempdir(),
                      "/storage/emulated/0/Download", os.getcwd()]
        for base in candidates:
            if not base:
                continue
            try:
                d = os.path.join(base, "test_mpl_tmp")
                os.makedirs(d, exist_ok=True)
                with open(os.path.join(d, "_probe"), "w") as fh:
                    fh.write("ok")
                WORKDIR = d
                break
            except OSError:
                continue
        if WORKDIR is None:
            WORKDIR = "."
    return WORKDIR


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_matplotlib():
    import matplotlib
    print("    matplotlib", matplotlib.__version__)
    assert hasattr(matplotlib, "pyplot")
    assert hasattr(matplotlib, "cm")
    assert hasattr(matplotlib, "colors")


def import_pyplot():
    import matplotlib
    matplotlib.use("Agg")   # headless backend for device
    import matplotlib.pyplot as plt
    assert hasattr(plt, "figure")
    assert hasattr(plt, "savefig")


# ---------------------------------------------------------------------------
# 2. C extensions loaded
# ---------------------------------------------------------------------------
def c_extensions():
    import matplotlib
    matplotlib.use("Agg")
    # ft2font, _path, _contour, _image, _tri, _qhull
    from matplotlib.ft2font import FT2Font
    assert FT2Font is not None


def ft2font_basic():
    import matplotlib
    matplotlib.use("Agg")
    from matplotlib.ft2font import FT2Font
    import matplotlib.font_manager as fm
    # Find a default font
    default = fm.findfont(fm.FontProperties())
    assert os.path.exists(default)
    font = FT2Font(default)
    assert font.num_faces >= 1
    assert font.family_name is not None


# ---------------------------------------------------------------------------
# 3. basic plot creation
# ---------------------------------------------------------------------------
def simple_plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [4, 5, 6])
    assert len(ax.lines) == 1
    plt.close(fig)


def scatter_plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.scatter([1, 2, 3], [4, 5, 6])
    assert len(ax.collections) == 1
    plt.close(fig)


def bar_plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.bar([1, 2, 3], [4, 5, 6])
    assert len(ax.patches) == 3
    plt.close(fig)


def histogram_plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.hist([1, 2, 2, 3, 3, 3])
    assert len(ax.patches) > 0
    plt.close(fig)


# ---------------------------------------------------------------------------
# 4. figure save to file
# ---------------------------------------------------------------------------
def savefig_png():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    p = os.path.join(workdir(), "test_plot.png")
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [1, 4, 9])
    fig.savefig(p, dpi=72)
    plt.close(fig)
    assert os.path.exists(p)
    assert os.path.getsize(p) > 100


def savefig_svg():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    p = os.path.join(workdir(), "test_plot.svg")
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [1, 4, 9])
    fig.savefig(p)
    plt.close(fig)
    assert os.path.exists(p)
    content = open(p, "r").read()
    assert "<svg" in content


def savefig_jpg():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    p = os.path.join(workdir(), "test_plot.jpg")
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [1, 4, 9])
    fig.savefig(p, dpi=72)
    plt.close(fig)
    assert os.path.exists(p)
    assert os.path.getsize(p) > 100


# ---------------------------------------------------------------------------
# 5. colormaps / colors
# ---------------------------------------------------------------------------
def colormaps():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.cm as cm
    assert "viridis" in cm.colormaps
    assert "jet" in cm.colormaps
    assert "hot" in cm.colormaps
    cmap = cm.get_cmap("viridis")
    assert cmap(0.0) is not None
    assert cmap(1.0) is not None
    assert cmap(0.5) is not None


def colors_conversion():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.colors as mcolors
    r, g, b, a = mcolors.to_rgba("red")
    assert abs(r - 1.0) < 1e-6
    assert abs(g) < 1e-6
    r2, g2, b2, a2 = mcolors.to_rgba("#ff0000")
    assert abs(r2 - 1.0) < 1e-6


# ---------------------------------------------------------------------------
# 6. figure / subplot layout
# ---------------------------------------------------------------------------
def subplot_layout():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, axes = plt.subplots(2, 3)
    assert axes.shape == (2, 3)
    for ax in axes.flat:
        ax.plot([1, 2])
    plt.close(fig)


def tight_layout():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.set_title("Test Title")
    ax.set_xlabel("X axis")
    ax.plot([1, 2, 3])
    fig.tight_layout()
    plt.close(fig)


# ---------------------------------------------------------------------------
# 7. text / annotations
# ---------------------------------------------------------------------------
def text_elements():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.set_title("My Title")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.text(0.5, 0.5, "hello", transform=ax.transAxes)
    ax.annotate("note", xy=(1, 1), xytext=(0.5, 0.8))
    plt.close(fig)


# ---------------------------------------------------------------------------
# 8. patches / shapes
# ---------------------------------------------------------------------------
def patches():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle, Circle
    fig, ax = plt.subplots()
    ax.add_patch(Rectangle((0.1, 0.1), 0.3, 0.4))
    ax.add_patch(Circle((0.5, 0.5), 0.2))
    assert len(ax.patches) == 2
    plt.close(fig)


# ---------------------------------------------------------------------------
# 9. axes formatting
# ---------------------------------------------------------------------------
def axes_formatting():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3], [1, 4, 9])
    ax.set_xlim(0, 4)
    ax.set_ylim(0, 10)
    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_aspect("equal")
    ax.legend(["data"])
    ax.grid(True)
    plt.close(fig)


# ---------------------------------------------------------------------------
# 10. numpy integration
# ---------------------------------------------------------------------------
def numpy_integration():
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    x = np.linspace(0, 2 * np.pi, 100)
    y = np.sin(x)
    ax.plot(x, y)
    assert len(ax.lines) == 1
    plt.close(fig)


def contour_plot():
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    x = np.linspace(-2, 2, 50)
    y = np.linspace(-2, 2, 50)
    xx, yy = np.meshgrid(x, y)
    zz = np.sin(xx) * np.cos(yy)
    cs = ax.contour(xx, yy, zz)
    assert cs is not None
    plt.close(fig)


# ---------------------------------------------------------------------------
# 11. image display
# ---------------------------------------------------------------------------
def imshow_plot():
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    data = np.random.default_rng(42).random((20, 20))
    im = ax.imshow(data, cmap="viridis")
    assert im is not None
    plt.close(fig)


# ---------------------------------------------------------------------------
# 12. polar plot
# ---------------------------------------------------------------------------
def polar_plot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(subplot_kw={"projection": "polar"})
    ax.plot([0, 1, 2, 3], [1, 0.5, 1, 0.5])
    plt.close(fig)


# ---------------------------------------------------------------------------
# 13. style / rcParams
# ---------------------------------------------------------------------------
def rcparams():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    prev = plt.rcParams["font.size"]
    plt.rcParams["font.size"] = 14
    assert plt.rcParams["font.size"] == 14
    plt.rcParams["font.size"] = prev


def style_sheets():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    styles = plt.style.available
    assert len(styles) > 0
    # Just check we can access them, don't apply (may not all work without font)
    assert "default" in styles or "Solarize_Light2" in styles


# ---------------------------------------------------------------------------
# 14. savefig to bytes / in-memory
# ---------------------------------------------------------------------------
def savefig_bytesio():
    import io
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3])
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    data = buf.getvalue()
    assert len(data) > 100
    assert data[:4] == b"\x89PNG"


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. matplotlib import / version")
    test("import matplotlib", import_matplotlib)
    test("import pyplot (Agg)", import_pyplot)

    section("2. C extensions")
    test("C extensions loaded", c_extensions)
    test("ft2font basic", ft2font_basic)

    section("3. basic plot creation")
    test("line plot", simple_plot)
    test("scatter plot", scatter_plot)
    test("bar plot", bar_plot)
    test("histogram", histogram_plot)

    section("4. figure save to file")
    test("savefig PNG", savefig_png)
    test("savefig SVG", savefig_svg)
    test("savefig JPEG", savefig_jpg)

    section("5. colormaps / colors")
    test("colormaps access", colormaps)
    test("colors conversion", colors_conversion)

    section("6. figure / subplot layout")
    test("subplot grid", subplot_layout)
    test("tight_layout", tight_layout)

    section("7. text / annotations")
    test("text and annotations", text_elements)

    section("8. patches / shapes")
    test("Rectangle and Circle", patches)

    section("9. axes formatting")
    test("axes formatting", axes_formatting)

    section("10. numpy integration")
    test("numpy plot", numpy_integration)
    test("contour plot", contour_plot)

    section("11. image display")
    test("imshow", imshow_plot)

    section("12. polar plot")
    test("polar projection", polar_plot)

    section("13. style / rcParams")
    test("rcParams", rcparams)
    test("style sheets list", style_sheets)

    section("14. savefig to bytes")
    test("savefig BytesIO PNG", savefig_bytesio)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
