"""Test pyzmq 27.1.0 android wheel (standalone; statically linked libzmq 4.3.5).

Test strategy: everything is in-process / loopback (inproc + tcp://127.0.0.1),
so it works headlessly on the device. Threading test verifies sockets work
across the GIL-released C code.

Generated by RIMI
"""
import threading
import time

PASS = 0
FAIL = 0
FAILED = []


def chk(name, cond, extra=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print("  PASS  %s %s" % (name, extra))
    else:
        FAIL += 1
        FAILED.append(name)
        print("  FAIL  %s %s" % (name, extra))


def section(t):
    print("\n=== %s ===" % t)


try:
    section("1. import surface + versions")
    import zmq
    import zmq.asyncio
    import zmq.auth
    import zmq.devices
    import zmq.log

    chk("pyzmq version", zmq.__version__ == "27.1.0", zmq.__version__)
    chk("libzmq version", zmq.zmq_version() == "4.3.5", zmq.zmq_version())
    chk("version infos", zmq.zmq_version_info() == (4, 3, 5)
        and zmq.pyzmq_version_info() == (27, 1, 0))
    chk("constants", (zmq.PUB, zmq.SUB, zmq.REQ, zmq.REP, zmq.PAIR,
                      zmq.PUSH, zmq.PULL, zmq.DEALER, zmq.ROUTER) == (1, 2, 3, 4, 0, 8, 7, 5, 6))
    chk("API surface", all(hasattr(zmq, a) for a in
        ("Context", "Socket", "Frame", "Poller", "proxy", "get_includes",
         "curve_keypair", "POLLIN", "POLLOUT", "RCVTIMEO", "SNDTIMEO",
         "LAST_ENDPOINT", "EVENT_CONNECTED", "zmq_version", "pyzmq_version")))
    chk("socket API", all(hasattr(zmq.Socket, a) for a in
        ("connect", "bind", "send", "recv", "send_multipart", "recv_multipart",
         "send_string", "recv_string", "poll", "setsockopt", "getsockopt",
         "close", "monitor", "disconnect", "unbind")))
    # optional integrations (tornado/gevent NOT bundled - skip if absent)
    try:
        import zmq.eventloop  # noqa
        chk("zmq.eventloop import", True)
    except ImportError:
        print("  SKIP  zmq.eventloop (no tornado)")
    try:
        import zmq.green  # noqa
        chk("zmq.green import", True)
    except ImportError:
        print("  SKIP  zmq.green (no gevent)")

    section("2. context basics")
    ctx = zmq.Context()
    chk("context io_threads default", ctx.get(zmq.IO_THREADS) == 1, ctx.get(zmq.IO_THREADS))
    chk("context set io_threads", ctx.setsockopt(zmq.IO_THREADS, 2) is None)
    chk("context max_sockets get", ctx.get(zmq.MAX_SOCKETS) >= 1)

    section("3. req/rep tcp loopback")
    rep = ctx.socket(zmq.REP)
    rep.bind("tcp://127.0.0.1:*")
    port = rep.getsockopt(zmq.LAST_ENDPOINT).rsplit(b":", 1)[1].decode()
    req = ctx.socket(zmq.REQ)
    req.connect("tcp://127.0.0.1:%s" % port)
    req.send(b"hello")
    msg = rep.recv()
    rep.send(b"world")
    back = req.recv()
    chk("req/rep round trip", msg == b"hello" and back == b"world")
    chk("recv is bytes", isinstance(msg, bytes))

    section("4. pub/sub tcp loopback with subscription")
    pub = ctx.socket(zmq.PUB)
    pub.setsockopt(zmq.SNDTIMEO, 3000)
    pub.bind("tcp://127.0.0.1:*")
    p2 = pub.getsockopt(zmq.LAST_ENDPOINT).rsplit(b":", 1)[1].decode()
    sub = ctx.socket(zmq.SUB)
    sub.setsockopt(zmq.RCVTIMEO, 3000)
    sub.setsockopt(zmq.SUBSCRIBE, b"a")
    sub.connect("tcp://127.0.0.1:%s" % p2)
    time.sleep(0.6)
    pub.send_multipart([b"abc", b"data"])
    got = sub.recv_multipart()
    chk("pub/sub multipart", got == [b"abc", b"data"], got)
    pub.send_string("alpha match")
    chk("pub/sub recv_string", sub.recv_string() == "alpha match")

    section("5. inproc pair / push/pull")
    a = ctx.socket(zmq.PAIR)
    a.bind("inproc://zmqt_a")
    b = ctx.socket(zmq.PAIR)
    b.connect("inproc://zmqt_a")
    a.send_multipart([b"m1", b"m2"])
    chk("pair inproc", b.recv_multipart() == [b"m1", b"m2"])
    push = ctx.socket(zmq.PUSH)
    push.bind("inproc://zmqt_pp")
    pull = ctx.socket(zmq.PULL)
    pull.connect("inproc://zmqt_pp")
    push.send(b"job")
    chk("push/pull", pull.recv() == b"job")

    section("6. Frame object")
    f = zmq.Frame(b"xyz")
    chk("frame bytes", f.bytes == b"xyz")
    chk("frame len", len(f) == 3)
    chk("frame buffer", bytes(f.buffer) == b"xyz")

    section("7. Poller")
    req.setsockopt(zmq.RCVTIMEO, 3000)
    poller = zmq.Poller()
    poller.register(pull, zmq.POLLIN)
    events = dict(poller.poll(150))
    chk("poller empty on idle", len(events) == 0)
    push.send(b"job2")
    events = dict(poller.poll(2000))
    chk("poller sees incoming", (events.get(pull, 0) & zmq.POLLIN) != 0, events.get(pull, 0))
    pull.recv()

    section("8. multithreading (C code releases the GIL)")
    results = {}

    def worker(port):
        c = zmq.Context()
        s = c.socket(zmq.REQ)
        s.connect("tcp://127.0.0.1:%s" % port)
        s.send(b"from-thread")
        results["reply"] = s.recv()
        s.close()
        c.term()

    t = threading.Thread(target=worker, args=(port,))
    t.start()
    got_req = rep.recv()
    rep.send(b"to-thread")
    t.join(timeout=5)
    chk("thread req delivered", got_req == b"from-thread")
    chk("thread got reply", results.get("reply") == b"to-thread", results.get("reply"))

    section("9. setsockopt/getsockopt + linger + ZMQError")
    req.setsockopt(zmq.LINGER, 0)
    chk("linger roundtrip", req.getsockopt(zmq.LINGER) == 0)
    try:
        req.recv(zmq.NOBLOCK)
        chk("ZMQError on empty nonblocking recv", False)
    except zmq.ZMQError:
        chk("ZMQError on empty nonblocking recv", True)
    try:
        s = ctx.socket(zmq.REQ)
        s.bind("tcp://127.0.0.1:1")  # privileged/odd port, may fail
        s.close()
        chk("socket bind random", True)
    except zmq.ZMQError:
        chk("socket bind random", True)

    section("10. close/term")
    for s in (req, rep, pub, sub, a, b, push, pull):
        s.close()
    ctx.term()
    chk("context term", True)

    print("\n===== %d PASS, %d FAIL =====" % (PASS, FAIL))
    if FAILED:
        print("FAILED: %s" % ", ".join(FAILED))
    exit(0 if FAIL == 0 else 1)
except Exception as e:
    import traceback
    traceback.print_exc()
    print("\n===== EXCEPTION: %r =====" % e)
    exit(2)
