"""
Test script for scikit-image on Android Python STB
Device test: validates import, 38 submodules, core functionality.

Generated by RIMI
"""

import sys
import time
import platform

RESULTS = []

def section(name):
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

def test(name, func):
    global RESULTS
    try:
        result = func()
        RESULTS.append((name, "PASS", result if result else ""))
        print(f"  [PASS] {name}")
    except Exception as e:
        RESULTS.append((name, "FAIL", str(e)))
        print(f"  [FAIL] {name}: {e}")

def test():
    section("Environment")
    print(f"  Python: {sys.version}")
    print(f"  Platform: {platform.platform()}")
    print(f"  Arch: {platform.machine()}")

    # --- Core Import ---
    section("Core Import")
    test("import skimage", lambda: __import__("skimage"))
    test("skimage.__version__", lambda: __import__("skimage").__version__)

    # --- 38 Submodules ---
    section("Submodules (38)")
    submodules = [
        "__init__",
        "_shared",
        "_shared.utils",
        "_shared.testing",
        "_shared.measure",
        "_shared.version_requirements",
        "_shared.filters",
        "_shared._geometry",
        "_fft",
        "_-registration",
        "_registration.ecc",
        "_registration.phase_cross_correlation",
        "color",
        "color.colorconv",
        "color.colorlabel",
        "color.colorwheel",
        "data",
        "data._binary_blobs",
        "data._fetcher",
        "draw",
        "draw.draw",
        "draw.line_nd",
        "draw.disk",
        "exposure",
        "exposure.exposure",
        "exposure.histogram",
        "feature",
        "feature.hog",
        "feature.peak",
        "filters",
        "filters.gaussian",
        "filters.median",
        "filters.threshold",
        "graph",
        "graph._rag",
        "io",
        "measure",
        "measure.label",
        "measure.regionprops",
        "morphology",
        "morphology.binary",
        "morphology.disk",
        "morphology.remove_small_holes",
        "registration",
        "registration.phase_cross_correlation",
        "restoration",
        "restoration.denoise",
        "segmentation",
        "segmentation.slic",
        "segmentation.felzenszwalb",
        "transform",
        "transform.hough",
        "transform.rotate",
        "utils",
        "utils.compare",
    ]
    imported = 0
    for mod in submodules:
        test(f"import skimage.{mod}", lambda m=mod: __import__(f"skimage.{m}", fromlist=["_"]))
        imported += 1

    # --- Core Functionality ---
    section("Core Functionality")
    test("numpy available", lambda: __import__("numpy"))
    test("scipy available (optional)", lambda: __import__("scipy"))

    def test_create_image():
        import numpy as np
        from skimage import data
        img = data.camera()
        assert img.shape == (512, 512), f"Unexpected shape: {img.shape}"
        return f"shape={img.shape}"

    test("data.camera() image", test_create_image)

    def test_gaussian_filter():
        import numpy as np
        from skimage.filters import gaussian
        img = np.random.rand(64, 64).astype(np.float64)
        filtered = gaussian(img, sigma=1.0)
        assert filtered.shape == img.shape
        return f"output shape={filtered.shape}"

    test("gaussian filter", test_gaussian_filter)

    def test_median_filter():
        import numpy as np
        from skimage.filters import median
        from skimage.morphology import disk
        img = np.random.rand(64, 64).astype(np.float64)
        filtered = median(img, disk(3))
        assert filtered.shape == img.shape
        return f"output shape={filtered.shape}"

    test("median filter", test_median_filter)

    def test_threshold_otsu():
        import numpy as np
        from skimage.filters import threshold_otsu
        img = np.random.rand(64, 64)
        thresh = threshold_otsu(img)
        assert 0.0 <= thresh <= 1.0
        return f"threshold={thresh:.4f}"

    test("threshold_otsu", test_threshold_otsu)

    def test_morphology_disk():
        import numpy as np
        from skimage.morphology import disk, binary_erosion
        selem = disk(3)
        assert selem.shape[0] == 7
        img = np.ones((32, 32), dtype=bool)
        eroded = binary_erosion(img, selem)
        assert eroded.shape == img.shape
        return f"disk size={selem.shape}, eroded OK"

    test("morphology disk + erosion", test_morphology_disk)

    def test_resize():
        import numpy as np
        from skimage.transform import resize
        img = np.random.rand(64, 64)
        resized = resize(img, (32, 32))
        assert resized.shape == (32, 32)
        return f"resized {img.shape} -> {resized.shape}"

    test("transform resize", test_resize)

    def test_hsv_conversion():
        import numpy as np
        from skimage.color import rgb2hsv, hsv2rgb
        rgb = np.random.rand(16, 16, 3).astype(np.float64)
        rgb = rgb / rgb.max()
        hsv = rgb2hsv(rgb)
        assert hsv.shape == rgb.shape
        back = hsv2rgb(hsv)
        assert back.shape == rgb.shape
        return f"rgb->hsv->rgb OK, shape={hsv.shape}"

    test("color rgb2hsv / hsv2rgb", test_hsv_conversion)

    def test_label_regions():
        import numpy as np
        from skimage.measure import label
        mask = np.zeros((64, 64), dtype=int)
        mask[10:20, 10:20] = 1
        mask[40:50, 40:50] = 2
        labeled = label(mask)
        assert labeled.max() == 2
        return f"regions found: {labeled.max()}"

    test("measure label", test_label_regions)

    def test_regionprops():
        import numpy as np
        from skimage.measure import label, regionprops
        mask = np.zeros((64, 64), dtype=int)
        mask[10:20, 10:20] = 1
        labeled = label(mask)
        props = regionprops(labeled)
        assert len(props) == 1
        return f"area={props[0].area}"

    test("measure regionprops", test_regionprops)

    def test_hog():
        import numpy as np
        from skimage.feature import hog
        from skimage import data
        img = data.astronaut()
        fd, hog_img = hog(img, orientations=9, pixels_per_cell=(8, 8),
                          cells_per_block=(2, 2), visualize=True, channel_axis=-1)
        assert fd.shape[0] > 0
        return f"HOG features: {fd.shape[0]}"

    test("feature hog", test_hog)

    def test_slic():
        import numpy as np
        from skimage.segmentation import slic
        from skimage import data
        img = data.astronaut()
        segments = slic(img, n_segments=50, compactness=10,
                        start_label=1, channel_axis=-1)
        assert segments.shape[:2] == img.shape[:2]
        return f"segments shape={segments.shape}, unique={len(np.unique(segments))}"

    test("segmentation slic", test_slic)

    def test_hough_circle():
        import numpy as np
        from skimage.transform import hough_circle, hough_circle_peaks
        from skimage.draw import circle_perimeter
        img = np.zeros((128, 128), dtype=np.uint8)
        rr, cc = circle_perimeter(64, 64, 20)
        img[rr, cc] = 1
        hough_res = hough_circle(img, [15, 20, 25])
        assert len(hough_res) == 3
        return f"tested 3 radii: {len(hough_res)}"

    test("transform hough_circle", test_hough_circle)

    def test_draw_disk():
        import numpy as np
        from skimage.draw import disk
        img = np.zeros((128, 128), dtype=np.uint8)
        rr, cc = disk((64, 64), 20, shape=img.shape)
        img[rr, cc] = 1
        assert img.sum() > 0
        return f"disk pixels drawn: {img.sum()}"

    test("draw disk", test_draw_disk)

    def test_denoise_tv():
        import numpy as np
        from skimage.restoration import denoise_tv_chambolle
        img = np.random.rand(32, 32)
        denoised = denoise_tv_chambolle(img, weight=0.1)
        assert denoised.shape == img.shape
        return f"denoised shape={denoised.shape}"

    test("restoration denoise_tv_chambolle", test_denoise_tv)

    def test_exposure_histogram():
        import numpy as np
        from skimage.exposure import histogram
        img = np.random.rand(64, 64)
        hist, bin_edges = histogram(img, nbins=256)
        assert len(hist) == 256
        return f"histogram bins={len(hist)}"

    test("exposure histogram", test_exposure_histogram)

    # --- Summary ---
    section("SUMMARY")
    passed = sum(1 for _, status, _ in RESULTS if status == "PASS")
    failed = sum(1 for _, status, _ in RESULTS if status == "FAIL")
    total = len(RESULTS)
    print(f"  Total: {total} | Passed: {passed} | Failed: {failed}")
    if failed > 0:
        print(f"\n  Failed tests:")
        for name, status, msg in RESULTS:
            if status == "FAIL":
                print(f"    - {name}: {msg}")
    print(f"\n  {'ALL TESTS PASSED' if failed == 0 else 'SOME TESTS FAILED'}")
    return failed == 0


if __name__ == "__main__":
    ok = test()
    sys.exit(0 if ok else 1)
