"""Device test for PyYAML 6.0.3 (cp312-cp312 android_24 wheel).

Verifies the wheel installs, loads the C (libyaml) extension, and does
dump/load round-trips. Prints a PASS/FAIL/SKIP report and exits non-zero
on any FAIL.

Generated by RIMI
"""
import sys

def banner(name):
    print("\n===== %s =====" % name)

def check(ok, name, detail=""):
    status = "PASS" if ok else "FAIL"
    print("[%-4s] %s %s" % (status, name, detail))
    return 1 if not ok else 0

failures = 0
skips = 0

banner("import")
try:
    import yaml
    print("yaml imported from:", yaml.__file__)
except ImportError as e:
    failures += check(False, "import yaml", "-> %r" % (e,))
    print("\nRESULT: %d FAIL / %d SKIP" % (failures, skips))
    sys.exit(1)

banner("version / libyaml")
try:
    v = yaml.__version__
    print("yaml.__version__:", v)
    failures += check(v == "6.0.3", "version 6.0.3", "got %r" % (v,))
except AttributeError:
    print("yaml.__version__: (absent)")
    failures += check(False, "version 6.0.3", "attribute missing")

with_libyaml = getattr(yaml, "__with_libyaml__", False)
print("yaml.__with_libyaml__:", with_libyaml)
failures += check(bool(with_libyaml), "C extension (libyaml) loaded")

banner("load basic")
basic = """
name: test
version: 1
items:
  - a
  - b
  - 3
enabled: true
"""
try:
    d = yaml.safe_load(basic)
    print("safe_load ->", d)
    failures += check(d["name"] == "test" and d["items"] == ["a", "b", 3] and d["enabled"] is True,
                      "safe_load basic mapping")
except Exception as e:
    failures += check(False, "safe_load basic", "-> %r" % (e,))

banner("dump/load round-trip")
try:
    data = {"app": "PythonSTB", "ports": [8000, 8080], "debug": False,
            "title": "\u4e2d\u6587\u6807\u9898"}  # unicode
    text = yaml.safe_dump(data, allow_unicode=True, default_flow_style=False)
    print("safe_dump ->\n%s" % text)
    back = yaml.safe_load(text)
    failures += check(back == data, "safe_dump/safe_load round-trip", "got %r" % (back,))
except Exception as e:
    failures += check(False, "round-trip", "-> %r" % (e,))

banner("CLoader / CDumper")
try:
    ctext = yaml.dump(data, Dumper=yaml.CDumper, allow_unicode=True)
    cloaded = yaml.load(ctext, Loader=yaml.CSafeLoader)
    failures += check(cloaded == data, "CDumper/CSafeLoader round-trip", "got %r" % (cloaded,))
except Exception as e:
    failures += check(False, "CDumper/CSafeLoader", "-> %r" % (e,))

banner("events")
try:
    evs = list(yaml.parse(basic))
    failures += check(len(evs) >= 2 and evs[-1].end_mark is not None,
                      "yaml.parse produces events", "count=%d" % len(evs))
except Exception as e:
    failures += check(False, "yaml.parse", "-> %r" % (e,))

banner("anchors/aliases")
try:
    anchored = """
base: &base
  url: https://example.com
  port: 443
mirror:
  <<: *base
"""
    d2 = yaml.safe_load(anchored)
    failures += check(d2["mirror"]["url"] == "https://example.com", "anchor/merge",
                      "got %r" % (d2["mirror"],))
except Exception as e:
    failures += check(False, "anchor/merge", "-> %r" % (e,))

banner("CSafeLoader c-level")
try:
    cl2 = yaml.load(basic, Loader=yaml.CSafeLoader)
    failures += check(cl2["name"] == "test", "CSafeLoader load", "got %r" % (cl2,))
except Exception as e:
    failures += check(False, "CSafeLoader", "-> %r" % (e,))

print("\nRESULT: %d FAIL / %d SKIP" % (failures, skips))
sys.exit(0 if failures == 0 else 1)
