"""Device test for regex 2026.7.19 (cp312-cp312 android_24 wheel).

Verifies the wheel installs, loads the C extension (regex._regex), and that
core/fuzzy/unicode features work. Prints PASS/FAIL/SKIP report, exits non-zero
on any FAIL.

Generated by RIMI
"""
import sys

def banner(name):
    print("\n===== %s =====" % name)

def check(ok, name, detail=""):
    status = "PASS" if ok else "FAIL"
    print("[%-4s] %s %s" % (status, name, detail))
    return 1 if not ok else 0

failures = 0
skips = 0

banner("import")
try:
    import regex
    print("regex imported from:", regex.__file__)
    print("regex.__version__:", regex.__version__)
    failures += check(regex.__version__ == "2026.7.19", "version 2026.7.19", "got %r" % (regex.__version__,))
except ImportError as e:
    failures += check(False, "import regex", "-> %r" % (e,))
    print("\nRESULT: %d FAIL / %d SKIP" % (failures, skips))
    sys.exit(1)

banner("C extension loaded")
try:
    import regex._regex
    print("regex._regex:", regex._regex.__file__)
    failures += check(True, "C extension regex._regex importable")
except Exception as e:
    print("direct import failed -> %r" % (e,))
    failures += check(False, "C extension regex._regex importable", "-> %r" % (e,))

banner("basic match")
try:
    m = regex.search(r"(?P<word>\w+)@(?P<domain>\w+\.\w+)", "Contact: user@example.com now")
    print("match groups:", m.groupdict())
    failures += check(m.group("word") == "user" and m.group("domain") == "example.com",
                      "named groups search", "got %r" % (m.groupdict(),))
except Exception as e:
    failures += check(False, "basic match", "-> %r" % (e,))

banner("substitution")
try:
    s = regex.sub(r"(\d+)-(\d+)", r"\2/\1", "IDs 42-17 and 99-3")
    print("sub ->", s)
    failures += check(s == "IDs 17/42 and 3/99", "regex.sub with group refs", "got %r" % (s,))
except Exception as e:
    failures += check(False, "substitution", "-> %r" % (e,))

banner("split / findall / finditer")
try:
    parts = regex.split(r"[,\s]+", "a, b   c")
    failures += check(parts == ["a", "b", "c"], "regex.split", "got %r" % (parts,))
    nums = regex.findall(r"\d+", "x1 y22 z333")
    failures += check(nums == ["1", "22", "333"], "regex.findall", "got %r" % (nums,))
    it = regex.finditer(r"(a)", "ababa")
    cnt = sum(1 for _ in it)
    failures += check(cnt == 3, "regex.finditer count", "got %d" % cnt)
except Exception as e:
    failures += check(False, "split/findall/finditer", "-> %r" % (e,))

banner("unicode")
try:
    m = regex.search(r"\p{Script=Han}+", "abc \u4e2d\u6587 def")
    print("han match:", m.group(0))
    failures += check(m.group(0) == "\u4e2d\u6587", "\\p{Script=Han}", "got %r" % (m.group(0),))
except Exception as e:
    failures += check(False, "unicode", "-> %r" % (e,))

banner("variable-width lookbehind (re cannot do this)")
try:
    m = regex.search(r"(?<=foo|foob)ar", "foobar and foar")
    print("lookbehind:", m.group(0))
    failures += check(m.group(0) == "ar", "variable-width lookbehind", "got %r" % (m.group(0),))
except Exception as e:
    failures += check(False, "lookbehind", "-> %r" % (e,))

banner("fuzzy matching")
try:
    m = regex.search(r"(?:hello){e<=1}", "hallo world")
    print("fuzzy match:", m.group(0))
    failures += check(m.group(0) == "hallo", "fuzzy match {e<=1}", "got %r" % (m.group(0),))
except Exception as e:
    failures += check(False, "fuzzy matching", "-> %r" % (e,))

banner("atomic groups / possessive quantifiers")
try:
    # atomic group prevents backtracking: should NOT match
    m = regex.search(r"(?>a|ab)c", "abc")
    failures += check(m is None, "atomic group blocks backtracking", "got %r" % (m.group(0) if m else None,))
    m2 = regex.search(r"(?>ab|a)c", "abc")
    failures += check(m2 is not None and m2.group(0) == "abc", "atomic group match", "got %r" % (m2.group(0) if m2 else None,))
except Exception as e:
    failures += check(False, "atomic groups", "-> %r" % (e,))

banner("re module compatibility")
try:
    import re
    m = re.search(r"(\d+)-(\d+)", "12-34")
    failures += check(m.group(1) == "12" and m.group(2) == "34", "builtin re still works")
    pat = regex.compile(r"(?i)stb-(\d+)")
    m = pat.search("STB-101")
    failures += check(m.group(1) == "101", "regex.compile + (?i)", "got %r" % (m.group(1) if m else None,))
except Exception as e:
    failures += check(False, "compat", "-> %r" % (e,))

print("\nRESULT: %d FAIL / %d SKIP" % (failures, skips))
sys.exit(0 if failures == 0 else 1)
