#!/usr/bin/env python3
"""Test_ZStandard.py - on-device validation for the zstandard 0.25.0 wheel.

Exercises the C backend (zstandard.backend_c) through the public API.
Exit code 0 = all tests passed.

Generated by RIMI
"""
import os
import sys
import tempfile

import zstandard as zstd

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:  # noqa: BLE001
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


def test_imports():
    check(hasattr(zstd, "backend"), "no backend attr")
    check(zstd.backend == "cext", "backend %r" % zstd.backend)
    check(hasattr(zstd, "ZstdCompressor"), "no ZstdCompressor")
    check(hasattr(zstd, "ZstdDecompressor"), "no ZstdDecompressor")
    check(hasattr(zstd, "compress"), "no compress()")
    check(hasattr(zstd, "decompress"), "no decompress()")
    print("  backend:", zstd.backend)


def test_compress_decompress():
    data = b"hello zstd compress/decompress world " * 10000
    c = zstd.compress(data)
    assert isinstance(c, bytes), "compress result not bytes"
    assert len(c) < len(data), "not compressed: %d" % len(c)
    d = zstd.decompress(c)
    assert d == data, "decompress mismatch"
    print("  compress %d -> %d (%.1f%%)" % (len(data), len(c), 100.0 * len(c) / len(data)))


def test_compressor_object():
    data = os.urandom(50000) + b"repeated payload for compressor object " * 3000
    cctx = zstd.ZstdCompressor(level=3)
    c = cctx.compress(data)
    assert len(c) < len(data), "not compressed"
    dctx = zstd.ZstdDecompressor()
    d = dctx.decompress(c)
    assert d == data, "decompress mismatch"
    print("  ZstdCompressor->ZstdDecompressor roundtrip ok (%d bytes)" % len(c))


def test_compressobj_stream():
    data = b"streaming zstd compress " * 5000 + os.urandom(2000)
    cctx = zstd.ZstdCompressor()
    cobj = cctx.compressobj()
    chunks = [cobj.compress(data[i:i + 7000]) for i in range(0, len(data), 7000)]
    chunks.append(cobj.flush())
    compressed = b"".join(chunks)
    dctx = zstd.ZstdDecompressor()
    dobj = dctx.decompressobj()
    out = b"".join([dobj.decompress(compressed[j:j + 7000]) for j in range(0, len(compressed), 7000)])
    out += dobj.flush()
    assert out == data, "streaming mismatch"
    print("  compressobj/decompressobj stream roundtrip ok")


def test_dict():
    dict_data = b"common prefix and suffix " * 20000
    sample = b"common prefix and suffix " * 20000 + b" unique data " * 100 + b"common prefix and suffix " * 20000
    d = zstd.ZstdCompressionDict(dict_data)
    cctx = zstd.ZstdCompressor(dict_data=d, level=3)
    c = cctx.compress(sample)
    dctx = zstd.ZstdDecompressor(dict_data=d)
    out = dctx.decompress(c)
    assert out == sample, "dict decompress mismatch"
    print("  dict compression ok (%d bytes)" % len(c))


def test_frame_params():
    data = zstd.compress(b"x" * 5000)
    params = zstd.get_frame_parameters(data)
    check(isinstance(params, zstd.FrameParameters), "type %r" % type(params))
    check(params.content_size == 5000, "content_size %r" % params.content_size)
    check(hasattr(params, "has_checksum"), "no has_checksum")
    check(hasattr(params, "window_size"), "no window_size")
    check(hasattr(params, "dict_id"), "no dict_id")
    print("  frame params: content_size=%d window_size=%d" % (params.content_size, params.window_size))


def test_zstd_file_roundtrip():
    data = b"zstd file roundtrip content " * 20000
    with tempfile.NamedTemporaryFile(suffix=".zst", delete=False) as f:
        name = f.name
    try:
        cctx = zstd.ZstdCompressor()
        with open(name, "wb") as fh:
            with cctx.stream_writer(fh) as w:
                w.write(data)
        with open(name, "rb") as fh:
            dctx = zstd.ZstdDecompressor()
            with dctx.stream_reader(fh) as r:
                out = r.read()
        assert out == data, "stream_writer/stream_reader mismatch"
    finally:
        os.unlink(name)
    print("  stream_writer/stream_reader roundtrip ok")


def test_zstd_open():
    data = b"zstd.open roundtrip " * 10000
    with tempfile.NamedTemporaryFile(suffix=".zst", delete=False) as f:
        name = f.name
    try:
        with zstd.open(name, "wb") as fh:
            fh.write(data)
        with zstd.open(name, "rb") as fh:
            out = fh.read()
        assert out == data, "zstd.open mismatch"
    finally:
        os.unlink(name)
    print("  zstd.open roundtrip ok")


def main():
    section("zstandard %s - C backend" % "0.25.0")
    test("import + backend=cext", test_imports)

    section("one-shot")
    test("compress/decompress", test_compress_decompress)
    test("ZstdCompressor/ZstdDecompressor", test_compressor_object)

    section("streaming")
    test("compressobj/decompressobj", test_compressobj_stream)
    test("stream_writer/stream_reader", test_zstd_file_roundtrip)
    test("zstd.open", test_zstd_open)

    section("advanced")
    test("compression dict", test_dict)
    test("get_frame_parameters", test_frame_params)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
