#!/usr/bin/env python3
"""Test_LZ4.py - on-device validation for the lz4 4.4.5 wheel.

Exercises block + frame APIs through the pure-python wrappers backed by the
native extensions. Exit code 0 = all tests passed.

Generated by RIMI
"""
import os
import sys
import tempfile

import lz4
from lz4 import block, frame
import lz4._version

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:  # noqa: BLE001
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


def roundtrip_block(data, mode):
    c = block.compress(data, mode=mode)
    assert isinstance(c, bytes), "compress result not bytes"
    assert c != data, "compress produced identical bytes"
    d = block.decompress(c)
    assert d == data, "decompress mismatch"


def test_version():
    check(lz4.__version__ == "4.4.5", "version %s" % lz4.__version__)
    check(hasattr(lz4, "VERSION"), "no VERSION")
    check(lz4._version.library_version_number() > 10700,
          "liblz4 version %s" % lz4._version.library_version_string())
    print("  liblz4:", lz4._version.library_version_string())


def test_block_default():
    data = b"hello lz4 block world" * 1000
    roundtrip_block(data, mode="default")


def test_block_fast():
    data = b"hello lz4 block world" * 1000
    roundtrip_block(data, mode="fast")


def test_block_high():
    data = b"hello lz4 block world" * 1000
    roundtrip_block(data, mode="high_compression")


def test_block_binary_sizes():
    for n in (0, 1, 63, 64, 65535, 65536, 262144):
        data = os.urandom(n)
        roundtrip_block(data, mode="default")


def test_frame_roundtrip():
    data = b"lz4 frame roundtrip test payload " * 10000
    with tempfile.TemporaryFile() as f:
        with frame.open(f, "wb", block_linked=True) as w:
            w.write(data)
        f.seek(0)
        out = f.read()
    assert out != data, "frame not compressed"
    assert len(out) < len(data) // 2, "frame not compressed enough: %d" % len(out)
    with tempfile.TemporaryFile() as f:
        f.write(out)
        f.seek(0)
        with frame.open(f, "rb") as r:
            got = r.read()
    assert got == data, "frame decompress mismatch"
    print("  frame %d -> %d bytes (%.1f%%)" % (len(data), len(out), 100.0 * len(out) / len(data)))


def test_frame_compress_decompress():
    data = (b"the quick brown fox jumps over the lazy dog " * 5000) + os.urandom(1000)
    c = frame.compress(data)
    assert len(c) < len(data), "not compressed"
    d = frame.decompress(c)
    assert d == data, "frame.decompress mismatch"


def test_frame_info():
    data = b"x" * 5000
    c = frame.compress(data)
    info = frame.get_frame_info(c)
    check(info["content_size"] == 0 or info["content_size"] == len(data),
          "content_size %r" % info)
    check(info["block_size_id"] in (4, 5, 6, 7), "block_size_id %r" % info)
    print("  frame info:", info)


def main():
    section("lz4 %s - native module" % lz4.__version__)
    test("import + version + liblz4", test_version)

    section("block API")
    test("block default roundtrip", test_block_default)
    test("block fast roundtrip", test_block_fast)
    test("block high roundtrip", test_block_high)
    test("block binary sizes 0..262144", test_block_binary_sizes)

    section("frame API")
    test("frame file roundtrip", test_frame_roundtrip)
    test("frame compress/decompress", test_frame_compress_decompress)
    test("get_frame_info", test_frame_info)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
