"""
On-device verification for the cross-compiled bottleneck 1.6.0 wheel.

bottleneck is a collection of fast C reductions for numpy (nan-aware sums,
means, std, medians, moving-window functions, ranks, partitions). Native
extensions: bottleneck/{reduce,move,nonreduce,nonreduce_axis}.cpython-312.so.
Without them the package still imports via the slow pure-Python fallbacks
(bottleneck.slow) but at 10-100x speed penalty - this wheel makes the fast C
paths available.

Runtime dep: numpy (>= 2.0, device has 2.5.2). All 4 .so files are
16KB-page-aligned to match the app's Python runtime.

Usage:
    python Test_bottleneck.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


def near(label, a, b, rtol=1e-7, atol=1e-9):
    import numpy as np
    if not np.isclose(a, b, rtol=rtol, atol=atol):
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


# ---------------------------------------------------------------------------
# 1. import surface + version + native extensions active
# ---------------------------------------------------------------------------
def t_import():
    import bottleneck as bn
    import numpy as np
    section("===== import =====")
    print("bottleneck:", bn.__file__)
    eq("version", bn.__version__, "1.6.0")
    for m in ("reduce", "move", "nonreduce", "nonreduce_axis"):
        mod = __import__("bottleneck." + m, fromlist=[m])
        native = mod.__file__.endswith(".so") or mod.__file__.endswith(".pyd")
        eq("native %s" % m, True, native)
    for name in ("nansum", "nanmean", "nanmedian", "move_mean", "move_median",
                 "replace", "rankdata", "push", "ss", "get_functions"):
        eq("exports %s" % name, True, hasattr(bn, name))
    eq("numpy present", True, np.__version__.startswith("2."))


# ---------------------------------------------------------------------------
# 2. nan-aware reductions vs numpy
# ---------------------------------------------------------------------------
def t_reduce():
    import bottleneck as bn
    import numpy as np
    section("===== nan-aware reduce =====")
    a = np.array([1.0, 2.0, np.nan, 4.0])
    near("nansum", bn.nansum(a), 7.0)
    near("nanmean", bn.nanmean(a), 7.0 / 3.0)
    eq("nanmin", bn.nanmin(a), 1.0)
    eq("nanmax", bn.nanmax(a), 4.0)
    near("nanstd", bn.nanstd(a), np.nanstd(a))
    near("nanvar", bn.nanvar(a), np.nanvar(a))
    eq("nanmedian even", bn.nanmedian(np.array([1.0, np.nan, 3.0, 4.0])), 3.0)
    eq("nanmedian odd", bn.nanmedian(np.array([1.0, 2.0, 3.0])), 2.0)
    eq("median", bn.median(np.array([3, 1, 2])), 2.0)
    eq("nanargmax", bn.nanargmax(a), 3)
    eq("nanargmin", bn.nanargmin(np.array([2.0, np.nan, 1.0])), 2)


# ---------------------------------------------------------------------------
# 3. allnan / anynan / ss
# ---------------------------------------------------------------------------
def t_edges():
    import bottleneck as bn
    import numpy as np
    section("===== allnan / anynan / ss =====")
    eq("allnan yes", bn.allnan(np.array([np.nan, np.nan])), True)
    eq("allnan no", bn.allnan(np.array([1.0, np.nan])), False)
    eq("anynan yes", bn.anynan(np.array([1.0, np.nan])), True)
    eq("anynan no", bn.anynan(np.array([1.0, 2.0])), False)
    near("ss", bn.ss(np.array([1.0, 2.0, 3.0])), 14.0)
    eq("allnan on nan", True, np.isnan(bn.nanmax(np.array([np.nan, np.nan]))))
    eq("nanmean all nan", True, np.isnan(bn.nanmean(np.array([np.nan, np.nan]))))


# ---------------------------------------------------------------------------
# 4. nonreduce / nonreduce_axis (replace, ranks, partition, push)
# ---------------------------------------------------------------------------
def t_nonreduce():
    import bottleneck as bn
    import numpy as np
    section("===== nonreduce / nonreduce_axis =====")
    eq("replace", list(bn.replace(np.array([1.0, 2.0, 3.0]), 2.0, 99.0)),
       [1.0, 99.0, 3.0])
    eq("rankdata", list(bn.rankdata(np.array([3, 1, 2]))), [3.0, 1.0, 2.0])
    r = np.array([3.0, 1.0, np.nan, 2.0])
    v = bn.nanrankdata(r)
    eq("nanrankdata nan kept", True, np.isnan(v[2]))
    eq("nanrankdata", list(v[[0, 1, 3]]), [3.0, 1.0, 2.0])
    eq("partition", list(bn.partition(np.array([3, 1, 2, 4]), 1)), [1, 2, 3, 4])
    eq("argpartition", list(bn.argpartition(np.array([3, 1, 2, 4]), 1)),
       [1, 2, 0, 3])
    eq("push", list(bn.push(np.array([1.0, np.nan, 3.0]))), [1.0, 1.0, 3.0])


# ---------------------------------------------------------------------------
# 5. moving window functions
# ---------------------------------------------------------------------------
def t_move():
    import bottleneck as bn
    import numpy as np
    section("===== move functions =====")
    m = np.arange(10.0)
    eq("move_mean", list(bn.move_mean(m, window=3, min_count=1)),
       [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
    eq("move_sum", list(bn.move_sum(m, window=3, min_count=1)),
       [0.0, 1.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])
    eq("move_max", list(bn.move_max(m, window=3, min_count=1)),
       [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
    eq("move_min", list(bn.move_min(m, window=3, min_count=1)),
       [0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
    std = bn.move_std(m, window=3, min_count=2)
    eq("move_std nan head", True, np.isnan(std[0]))
    near("move_std", float(std[1]), 0.5)
    var = bn.move_var(m, window=3, min_count=2)
    eq("move_var nan head", True, np.isnan(var[0]))
    near("move_var", float(var[1]), 0.25)
    eq("move_median", list(bn.move_median(m, window=3, min_count=1)),
       [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
    eq("move_rank", list(bn.move_rank(m, window=3, min_count=1)),
       [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
    eq("move_argmax", list(bn.move_argmax(m, window=3, min_count=1)),
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
    eq("move_argmin", list(bn.move_argmin(m, window=3, min_count=1)),
       [0.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0])


# ---------------------------------------------------------------------------
# 6. slow fallback parity + get_functions
# ---------------------------------------------------------------------------
def t_slow():
    import bottleneck as bn
    import numpy as np
    section("===== slow fallback / get_functions =====")
    eq("slow median", bn.slow.reduce.median(np.array([3, 1, 2])), 2.0)
    names = [f.__name__ for f in bn.get_functions("reduce")]
    eq("get_functions reduce", True, "nansum" in names)
    move_names = [f.__name__ for f in bn.get_functions("move")]
    eq("get_functions move", True, "move_mean" in move_names)
    non_names = [f.__name__ for f in bn.get_functions("nonreduce")]
    eq("get_functions nonreduce", True, "replace" in non_names)
    eq("bench callable", True, callable(bn.bench))
    eq("test obj", True, hasattr(bn, "test"))


# ---------------------------------------------------------------------------
# 7. stress: large arrays + dtype coverage
# ---------------------------------------------------------------------------
def t_stress():
    import bottleneck as bn
    import numpy as np
    section("===== stress =====")
    rng = np.random.default_rng(42)
    data = rng.random(500000)
    data[::97] = np.nan
    near("big nansum", bn.nansum(data), np.nansum(data))
    near("big nanmean", bn.nanmean(data), np.nanmean(data))
    near("big nanmax", bn.nanmax(data), np.nanmax(data))
    near("big nanstd", bn.nanstd(data), np.nanstd(data))
    eq("big move_mean shape", bn.move_mean(data, window=1000,
                                          min_count=1).shape, data.shape)
    m = bn.move_mean(data, window=1000, min_count=1)
    eq("big move_mean finite", True, np.isfinite(m[100000]))
    # integer dtype support
    i = np.arange(1000, dtype=np.int64) * 2
    eq("int nansum", bn.nansum(i), i.sum())
    eq("int median", bn.median(i), np.median(i))
    # 2D axis support
    d2 = rng.random((200, 300))
    eq("2d nanmean axis0 shape", bn.nanmean(d2, axis=0).shape, (300,))
    near("2d nanmean axis0", bn.nanmean(d2, axis=0)[0], np.nanmean(d2, axis=0)[0])
    near("2d nanmean axis1", bn.nanmean(d2, axis=1)[5], np.nanmean(d2, axis=1)[5])


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import surface", t_import),
        ("nan-aware reductions", t_reduce),
        ("allnan/anynan/ss edge cases", t_edges),
        ("nonreduce + nonreduce_axis", t_nonreduce),
        ("moving window functions", t_move),
        ("slow fallback + get_functions", t_slow),
        ("stress + dtypes + axes", t_stress),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
