#!/usr/bin/env python3
"""Test_CChardet.py - on-device/on-host validation for the cchardet 2.1.7 wheel.

Drives the native _cchardet C++ extension through the cchardet package API.
Exit code 0 = all tests passed (no FAILs).

Generated by RIMI
"""
import sys

import cchardet
from cchardet import _cchardet

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:  # noqa: BLE001
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


def test_imports():
    check(cchardet.__version__ == "2.1.7", "version: %s" % cchardet.__version__)
    check(hasattr(_cchardet, "detect_with_confidence"),
          "no detect_with_confidence")
    check(hasattr(_cchardet, "UniversalDetector"), "no UniversalDetector")


def test_detect_ascii():
    r = cchardet.detect("This is a plain ASCII string with no accents.".encode("ascii"))
    check(isinstance(r, dict) and "encoding" in r and "confidence" in r,
          "bad detect() result %r" % (r,))
    check(r["encoding"].lower() in ("ascii", "utf-8"), "encoding %r" % r["encoding"])
    print("  ascii ->", r)


def test_detect_utf8():
    r = cchardet.detect("héllo wörld — unicode content Ω≈ç√∫".encode("utf-8"))
    check("utf-8" in r["encoding"].lower(), "encoding %r" % r["encoding"])
    print("  utf-8 ->", r)


def test_detect_latin1():
    text = "caf\xe9 \xe0 la mode, gar\xe7on".encode("latin-1")
    r = cchardet.detect(text)
    check(r["confidence"] > 0.0, "zero confidence %r" % r)
    print("  latin-1 ->", r)


def test_detect_russian():
    text = "Привет мир, это тест кириллицы.".encode("utf-8")
    r = cchardet.detect(text)
    check("cyrillic" in r["encoding"].lower() or "koi8" in r["encoding"].lower()
          or "utf-8" in r["encoding"].lower(), "encoding %r" % r["encoding"])
    print("  russian ->", r)


def test_detect_bytes_api():
    # bytes input -> dict with str keys/values
    r = cchardet.detect("test bytes".encode("utf-8"))
    check(isinstance(r["encoding"], str), "encoding not str %r" % (r,))
    check(isinstance(r["confidence"], float), "confidence not float %r" % (r,))


def test_universal_detector():
    d = cchardet.UniversalDetector()
    d.feed("hello world, plain ascii text here".encode("ascii"))
    d.close()
    r = d.result
    check(isinstance(r, dict) and r.get("encoding"), "bad result %r" % r)
    print("  UniversalDetector ->", r)


def test_universal_detector_stream():
    d = cchardet.UniversalDetector()
    text = "Это потоковый тест на русском языке.".encode("utf-8")
    for i in range(0, len(text), 7):
        d.feed(text[i:i + 7])
    d.close()
    r = d.result
    check(r.get("encoding") and r["confidence"] > 0.0,
          "bad stream result %r" % r)
    print("  stream ->", r)


def test_detect_confidence_direct():
    enc, conf = _cchardet.detect_with_confidence("hello".encode("ascii"))
    check(isinstance(enc, (str, bytes)), "bad encoding type %r" % (enc,))
    check(isinstance(conf, float) and conf > 0.0, "bad confidence %r" % (conf,))


def main():
    section("cchardet %s - native module" % cchardet.__version__)
    test("import + version + native API", test_imports)

    section("detect()")
    test("detect ascii", test_detect_ascii)
    test("detect utf-8", test_detect_utf8)
    test("detect latin-1", test_detect_latin1)
    test("detect cyrillic", test_detect_russian)
    test("detect bytes API", test_detect_bytes_api)
    test("detect_with_confidence direct", test_detect_confidence_direct)

    section("UniversalDetector")
    test("single-shot feed", test_universal_detector)
    test("streaming feed", test_universal_detector_stream)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
