#!/usr/bin/env python3
"""
Test_psutil.py - on-device validation for the psutil wheel.

Exercises the C extensions (_psutil_linux, _psutil_posix) through the public API.
Exit code 0 = all tests passed.

Generated by RIMI
"""
import os
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


# ---------------------------------------------------------------------------
# 1. import + version
# ---------------------------------------------------------------------------
def test_import():
    import psutil
    check(hasattr(psutil, "__version__"), "no __version__")
    print("  version:", psutil.__version__)


def test_c_extensions():
    import psutil._psutil_linux as _linux
    import psutil._psutil_posix as _posix
    check(hasattr(_linux, "linux_platform_info"), "no linux_platform_info")
    check(hasattr(_posix, "net_if_addrs"), "no net_if_addrs")


# ---------------------------------------------------------------------------
# 2. CPU
# ---------------------------------------------------------------------------
def test_cpu_count():
    import psutil
    n = psutil.cpu_count(logical=True)
    check(n is not None and n > 0, "cpu_count=%r" % n)
    print("  cpu_count:", n)


def test_cpu_times():
    import psutil
    t = psutil.cpu_times()
    check(hasattr(t, "user"), "no user field")
    check(hasattr(t, "system"), "no system field")
    print("  cpu_times user=%.1f system=%.1f" % (t.user, t.system))


def test_cpu_percent():
    import psutil
    p = psutil.cpu_percent(interval=0.1)
    check(0.0 <= p <= 100.0, "cpu_percent=%r" % p)
    print("  cpu_percent:", p)


# ---------------------------------------------------------------------------
# 3. memory
# ---------------------------------------------------------------------------
def test_virtual_memory():
    import psutil
    m = psutil.virtual_memory()
    check(m.total > 0, "total=%d" % m.total)
    check(0 <= m.percent <= 100, "percent=%r" % m.percent)
    print("  virtual_memory: total=%dMB percent=%.1f%%" % (m.total // (1024 * 1024), m.percent))


def test_swap_memory():
    import psutil
    s = psutil.swap_memory()
    check(hasattr(s, "total"), "no total")
    print("  swap_memory: total=%dMB" % (s.total // (1024 * 1024)))


# ---------------------------------------------------------------------------
# 4. disk
# ---------------------------------------------------------------------------
def test_disk_usage():
    import psutil
    u = psutil.disk_usage("/")
    check(u.total > 0, "total=%d" % u.total)
    check(0 <= u.percent <= 100, "percent=%r" % u.percent)
    print("  disk_usage /: total=%dMB percent=%.1f%%" % (u.total // (1024 * 1024), u.percent))


def test_disk_partitions():
    import psutil
    parts = psutil.disk_partitions(all=False)
    check(isinstance(parts, list), "not list")
    print("  disk_partitions: %d entries" % len(parts))


def test_disk_io():
    import psutil
    io = psutil.disk_io_counters()
    check(io is not None, "None returned")
    check(hasattr(io, "read_bytes"), "no read_bytes")
    print("  disk_io_counters: read=%dMB write=%dMB" % (io.read_bytes // (1024 * 1024), io.write_bytes // (1024 * 1024)))


# ---------------------------------------------------------------------------
# 5. network
# ---------------------------------------------------------------------------
def test_net_io():
    import psutil
    n = psutil.net_io_counters()
    check(hasattr(n, "bytes_sent"), "no bytes_sent")
    check(hasattr(n, "bytes_recv"), "no bytes_recv")
    print("  net_io_counters: sent=%dKB recv=%dKB" % (n.bytes_sent // 1024, n.bytes_recv // 1024))


def test_net_if_addrs():
    import psutil
    addrs = psutil.net_if_addrs()
    check(isinstance(addrs, dict), "not dict")
    check(len(addrs) > 0, "empty")
    print("  net_if_addrs: %d interfaces" % len(addrs))


def test_net_if_stats():
    import psutil
    stats = psutil.net_if_stats()
    check(isinstance(stats, dict), "not dict")
    check(len(stats) > 0, "empty")
    first = list(stats.values())[0]
    check(hasattr(first, "isup"), "no isup")
    print("  net_if_stats: %d interfaces" % len(stats))


# ---------------------------------------------------------------------------
# 6. processes
# ---------------------------------------------------------------------------
def test_pids():
    import psutil
    pids = psutil.pids()
    check(len(pids) > 0, "empty")
    check(isinstance(pids[0], int), "not int")
    print("  pids: %d processes" % len(pids))


def test_process_info():
    import psutil
    pid = os.getpid()
    p = psutil.Process(pid)
    check(p.pid == pid, "pid mismatch")
    check(p.name(), "no name")
    check(p.status(), "no status")
    check(p.create_time() > 0, "create_time=%r" % p.create_time())
    print("  process %d: name=%s status=%s" % (pid, p.name(), p.status()))


def test_process_memory():
    import psutil
    p = psutil.Process(os.getpid())
    m = p.memory_info()
    check(m.rss > 0, "rss=%d" % m.rss)
    check(m.vms > 0, "vms=%d" % m.vms)
    print("  process memory: rss=%dMB vms=%dMB" % (m.rss // (1024 * 1024), m.vms // (1024 * 1024)))


def test_process_cmdline():
    import psutil
    p = psutil.Process(os.getpid())
    cmd = p.cmdline()
    check(len(cmd) > 0, "empty cmdline")
    print("  cmdline: %s" % " ".join(cmd[:3]))


# ---------------------------------------------------------------------------
# 7. sensors / boot time
# ---------------------------------------------------------------------------
def test_boot_time():
    import psutil
    bt = psutil.boot_time()
    check(bt > 0, "boot_time=%r" % bt)
    print("  boot_time:", bt)


# ---------------------------------------------------------------------------
# 8. utilization
# ---------------------------------------------------------------------------
def test_disk_usage_tmpdir():
    import psutil
    import tempfile
    tmp = tempfile.gettempdir()
    u = psutil.disk_usage(tmp)
    check(u.total > 0, "total=%d" % u.total)
    print("  disk_usage %s: %dMB" % (tmp, u.total // (1024 * 1024)))


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    section("1. import + C extensions")
    test("import psutil", test_import)
    test("C extensions loaded", test_c_extensions)

    section("2. CPU")
    test("cpu_count", test_cpu_count)
    test("cpu_times", test_cpu_times)
    test("cpu_percent", test_cpu_percent)

    section("3. memory")
    test("virtual_memory", test_virtual_memory)
    test("swap_memory", test_swap_memory)

    section("4. disk")
    test("disk_usage /", test_disk_usage)
    test("disk_partitions", test_disk_partitions)
    test("disk_io_counters", test_disk_io)

    section("5. network")
    test("net_io_counters", test_net_io)
    test("net_if_addrs", test_net_if_addrs)
    test("net_if_stats", test_net_if_stats)

    section("6. processes")
    test("pids", test_pids)
    test("Process info", test_process_info)
    test("Process memory_info", test_process_memory)
    test("Process cmdline", test_process_cmdline)

    section("7. system")
    test("boot_time", test_boot_time)
    test("disk_usage tmpdir", test_disk_usage_tmpdir)

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
