"""
On-device verification for the cross-compiled wrapt 2.3.0 wheel.

Usage:
    python Test_wrapt.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


# ---------------------------------------------------------------------------
# 1. import surface + version + C extension active
# ---------------------------------------------------------------------------
def t_import():
    import wrapt
    section("===== import =====")
    print("wrapt imported from:", wrapt.__file__)
    eq("version", wrapt.__version__, "2.3.0")
    # The C extension MUST be active (fast path) - the whole point of the
    # wheel is that _wrappers.cpython-312.so loads on-device.
    import wrapt.__wrapt__ as w
    print("using C extension:", w._using_c_extension)
    eq("_using_c_extension", w._using_c_extension, True)
    import wrapt._wrappers as c
    print("C extension module:", c.__file__)
    eq("C ObjectProxy import", True, hasattr(c, "ObjectProxy"))


# ---------------------------------------------------------------------------
# 2. FunctionWrapper: decorator basics, metadata, signature
# ---------------------------------------------------------------------------
def t_function_wrapper():
    section("===== FunctionWrapper =====")
    from wrapt import FunctionWrapper

    log = []

    def wrapper(wrapped, instance, args, kwargs):
        log.append((wrapped.__name__, instance is not None, args, kwargs))
        return wrapped(*args, **kwargs)

    def add(a, b=10):
        """docstring here"""
        return a + b

    addw = FunctionWrapper(add, wrapper)
    eq("calls through", addw(1, b=2), 3)
    eq("default arg", addw(1), 11)
    eq("name preserved", addw.__name__, "add")
    eq("qualname mirrors wrapped", addw.__qualname__, add.__qualname__)
    eq("docstring preserved", addw.__doc__, "docstring here")
    eq("wrapped reachable", addw.__wrapped__ is add, True)
    eq("wrapper saw args", log[-1][2], (1,))


# ---------------------------------------------------------------------------
# 3. ObjectProxy: attribute passthrough + identity/setattr + magic methods
# ---------------------------------------------------------------------------
def t_object_proxy():
    section("===== ObjectProxy =====")
    from wrapt import ObjectProxy

    data = {"k": "v"}
    p = ObjectProxy(data)
    eq("getitem passthrough", p["k"], "v")
    eq("keys passthrough", list(p.keys()), ["k"])
    eq("wrapped attr", p.__wrapped__ is data, True)

    # wrapt semantics: attribute SET on the proxy is forwarded to the wrapped
    # object (verified against _wrappers.c WraptObjectProxy_setattro, line 3103).
    class Box:
        pass

    box = Box()
    pb = ObjectProxy(box)
    pb.extra = 42
    eq("setattr forwarded to wrapped", box.extra, 42)

    class Thing:
        def method(self, x):
            return x * 3

    pt = ObjectProxy(Thing())
    eq("method call passthrough", pt.method(5), 15)

    s = ObjectProxy("hello")
    eq("str methods passthrough", s.upper(), "HELLO")
    eq("len via magic", len(s), 5)

    li = ObjectProxy([1, 2, 3])
    eq("iter passthrough", list(li), [1, 2, 3])


# ---------------------------------------------------------------------------
# 4. decorator(): the functools-style decorator helper
# ---------------------------------------------------------------------------
def t_decorator():
    section("===== decorator() =====")
    from wrapt import decorator

    log = []

    @decorator
    def timed(wrapped, instance, args, kwargs):
        log.append("in")
        return wrapped(*args, **kwargs)

    @timed
    def greet(name):
        """greets a name"""
        return "hi " + name

    eq("decorated call", greet("bob"), "hi bob")
    eq("decorator ran", log, ["in"])
    eq("name preserved", greet.__name__, "greet")
    eq("docstring preserved", greet.__doc__, "greets a name")
    eq("still callable via wrapped", greet.__wrapped__("al"), "hi al")


# ---------------------------------------------------------------------------
# 5. lru_cache from wrapt.caching
# ---------------------------------------------------------------------------
def t_lru_cache():
    section("===== lru_cache =====")
    from wrapt.caching import lru_cache

    calls = []

    @lru_cache(maxsize=2)
    def fib(n):
        calls.append(n)
        return n if n < 2 else fib(n - 1) + fib(n - 2)

    eq("fib(6)", fib(6), 8)
    eq("fib(6) cached", fib(6), 8)
    eq("fib(6) computed once", calls.count(6), 1)
    fib.cache_clear()
    fib(6)
    eq("cache cleared", calls.count(6), 2)


# ---------------------------------------------------------------------------
# 6. synchronized: thread lock wrapper
# ---------------------------------------------------------------------------
def t_synchronized():
    section("===== synchronized =====")
    import threading
    from wrapt import synchronized

    shared = []

    @synchronized
    def push_many(items):
        for it in items:
            shared.append(it)

    threads = [threading.Thread(target=push_many, args=([i],)) for i in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    eq("all items appended", sorted(shared), list(range(8)))
    eq("has __wrapped__", True, hasattr(push_many, "__wrapped__"))


# ---------------------------------------------------------------------------
# 7. wrap_function_wrapper + transient_function_wrapper
# ---------------------------------------------------------------------------
def t_wrap_function():
    section("===== wrap_function_wrapper =====")
    from wrapt import wrap_function_wrapper, transient_function_wrapper
    import wrapt as _w

    # IMPORTANT: interception works via MODULE ATTRIBUTE lookup (wrapt.partial),
    # not via a pre-bound local reference - a name bound before patching keeps
    # pointing at the original function and bypasses the patch.

    # --- transient: patch active ONLY during the decorated call. Canonical
    # usage (verified against tests/core/test_monkey_patching.py):
    # @transient_function_wrapper(target, "attr") -> decorator for the wrapper;
    # apply that to another function and call it.
    calls = []

    @transient_function_wrapper("wrapt", "partial")
    def probe_transient(wrapped, instance, args, kwargs):
        calls.append("t")
        return wrapped(*args, **kwargs)

    @probe_transient
    def use_partial():
        _w.partial(lambda: None)
        return "ok"

    eq("transient call result", use_partial(), "ok")
    eq("transient fired", calls, ["t"])

    calls[:] = []
    _w.partial(lambda: None)
    eq("patch removed after call", calls, [])

    # --- permanent
    perm = []

    def probe(wrapped, instance, args, kwargs):
        perm.append(1)
        return wrapped(*args, **kwargs)

    wrap_function_wrapper("wrapt", "partial", probe)
    _w.partial(lambda: None)
    eq("permanent wrapper called", perm, [1])


# ---------------------------------------------------------------------------
# 8. when_imported / register_post_import_hook
# ---------------------------------------------------------------------------
def t_post_import():
    section("===== post-import hook =====")
    from wrapt import register_post_import_hook, when_imported

    seen = []

    def hook(module):
        seen.append(module.__name__)

    # wrapt is already imported at this point, so the hook fires immediately
    # on registration.
    register_post_import_hook(hook, "wrapt")
    eq("hook fired immediately", seen, ["wrapt"])
    when_imported("wrapt")(lambda m: seen.append("annotated"))
    import wrapt
    eq("annotation fired", "annotated" in seen, True)


# ---------------------------------------------------------------------------
# 9. partial + WeakFunctionProxy
# ---------------------------------------------------------------------------
def t_misc():
    section("===== partial + weakref =====")
    import gc
    from wrapt import partial, WeakFunctionProxy

    def add(a, b):
        return a + b

    p = partial(add, 1)
    eq("partial call", p(2), 3)
    eq("partial kwarg", partial(add, b=5)(1), 6)
    eq("partial wrapped is the function", p.__wrapped__ is add, True)

    class Holder:
        def method(self, x):
            return x + 1

    h = Holder()
    w = WeakFunctionProxy(h.method)
    eq("weak proxy call", w(4), 5)
    # The proxy holds a weakref.proxy to the UNBOUND function (see
    # weakrefs.py) and rebinds it to the instance on call.
    eq("proxy wraps the function", w.__wrapped__ == Holder.method, True)
    del h
    gc.collect()
    try:
        w(4)
        raise AssertionError("should raise ReferenceError after gc")
    except ReferenceError:
        pass


# ---------------------------------------------------------------------------
# 10. ObjectProxy with a class instance binding (BoundFunctionWrapper)
# ---------------------------------------------------------------------------
def t_bind():
    section("===== bound method binding =====")
    from wrapt import FunctionWrapper

    log = []

    def spy(wrapped, instance, args, kwargs):
        log.append((type(instance).__name__ if instance is not None else None,))
        return wrapped(*args, **kwargs)

    class Greeter:
        def hi(self, who):
            return "hi " + who

    Greeter.hi = FunctionWrapper(Greeter.hi, spy)

    g = Greeter()
    eq("bound call", g.hi("sam"), "hi sam")
    eq("instance passed to wrapper", log[-1], ("Greeter",))
    eq("class attr wrapper has __name__", Greeter.hi.__name__, "hi")


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import + C extension", t_import),
        ("FunctionWrapper", t_function_wrapper),
        ("ObjectProxy", t_object_proxy),
        ("decorator()", t_decorator),
        ("lru_cache", t_lru_cache),
        ("synchronized", t_synchronized),
        ("wrap_function_wrapper", t_wrap_function),
        ("post-import hook", t_post_import),
        ("partial + weakref", t_misc),
        ("bound method binding", t_bind),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
