"""
On-device verification for the cross-compiled aiohttp wheel.

Run after installing:
    pip install aiohttp-<ver>-cp312-cp312-android_24_<ABI>.whl
        where <ABI> = arm64_v8a (real device) or x86_64 (emulator)

Usage:
    python Test_aiohttp.py [--quick]

Exit code 0 = everything required PASSed.
Sections marked [SKIP] are optional.

Generated by RIMI
"""
import asyncio
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_aiohttp():
    import aiohttp
    print("    aiohttp", aiohttp.__version__)
    assert isinstance(aiohttp.__version__, str)


def import_submodules():
    import aiohttp
    import aiohttp.client_reqrep
    import aiohttp.formdata
    import aiohttp.multipart
    print("    submodules OK")


# ---------------------------------------------------------------------------
# 2. ClientSession basics
# ---------------------------------------------------------------------------
def session_create():
    import aiohttp
    async def _run():
        async with aiohttp.ClientSession() as session:
            assert session is not None
            assert not session.closed
    asyncio.run(_run())


def session_timeout():
    import aiohttp
    async def _run():
        timeout = aiohttp.ClientTimeout(total=10, connect=5)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            assert session.timeout.total == 10
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 3. URL construction
# ---------------------------------------------------------------------------
def url_building():
    from urllib.parse import urljoin
    base = "http://example.com"
    url = urljoin(base, "/path/to/resource?q=1&v=2")
    assert url.startswith("http://example.com/path")
    assert "q=1" in url


# ---------------------------------------------------------------------------
# 4. Request / response objects
# ---------------------------------------------------------------------------
def request_repr():
    from aiohttp import RequestInfo
    from multidict import CIMultiDict
    ri = RequestInfo(
        url="http://example.com/test",
        method="GET",
        headers=CIMultiDict(),
        real_url="http://example.com/test",
    )
    assert ri.method == "GET"
    assert ri.url == "http://example.com/test"


# ---------------------------------------------------------------------------
# 5. FormData
# ---------------------------------------------------------------------------
def formdata_add():
    import aiohttp
    form = aiohttp.FormData()
    form.add_field("key", "value")
    form.add_field("file", b"binary", filename="test.bin")
    assert form.is_multipart


def formdata_text():
    import aiohttp
    form = aiohttp.FormData()
    form.add_field("text", "hello world", content_type="text/plain")
    assert form.is_multipart


# ---------------------------------------------------------------------------
# 6. Multipart
# ---------------------------------------------------------------------------
def multipart_reader():
    import aiohttp
    import io
    async def _run():
        headers = {"Content-Type": "multipart/form-data; boundary=test"}
        body = io.BytesIO(b"--test\r\nContent-Disposition: form-data; name=\"a\"\r\n\r\nhello\r\n--test--\r\n")
        mp = aiohttp.MultipartReader(headers=headers, content=body)
        assert mp is not None
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 7. TCPConnector / ConnectorOptions
# ---------------------------------------------------------------------------
def connector_create():
    import aiohttp
    async def _run():
        conn = aiohttp.TCPConnector(limit=50, limit_per_host=10)
        assert conn.limit == 50
        assert conn.limit_per_host == 10
        await conn.close()
    asyncio.run(_run())


def connector_dns():
    import aiohttp
    async def _run():
        conn = aiohttp.TCPConnector(use_dns_cache=True)
        assert conn.use_dns_cache is True
        await conn.close()
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 8. CookieJar
# ---------------------------------------------------------------------------
def cookiejar_basics():
    import aiohttp
    async def _run():
        jar = aiohttp.CookieJar()
        assert len(jar) == 0
    asyncio.run(_run())


def cookiejar_clear():
    import aiohttp
    async def _run():
        jar = aiohttp.CookieJar()
        jar.clear()
        assert len(jar) == 0
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 9. BasicAuth
# ---------------------------------------------------------------------------
def basicauth():
    from aiohttp import BasicAuth
    auth = BasicAuth("user", "pass")
    assert auth.login == "user"
    assert auth.password == "pass"


def basicauth_from_header():
    from aiohttp import BasicAuth
    auth = BasicAuth.decode("Basic dXNlcjpwYXNz")
    assert auth.login == "user"
    assert auth.password == "pass"


# ---------------------------------------------------------------------------
# 10. ClientTimeout
# ---------------------------------------------------------------------------
def timeout_defaults():
    import aiohttp
    t = aiohttp.ClientTimeout()
    assert t.total is None
    assert t.connect is None
    assert t.sock_connect is None
    assert t.sock_read is None


def timeout_custom():
    import aiohttp
    t = aiohttp.ClientTimeout(total=30, connect=10, sock_connect=5, sock_read=15)
    assert t.total == 30
    assert t.sock_read == 15


# ---------------------------------------------------------------------------
# 11. WSMsgType
# ---------------------------------------------------------------------------
def wsmsgtype():
    import aiohttp
    from aiohttp import WSMsgType
    assert WSMsgType.TEXT
    assert WSMsgType.BINARY
    assert WSMsgType.CLOSE
    assert WSMsgType.ERROR
    assert WSMsgType.PING
    assert WSMsgType.PONG


# ---------------------------------------------------------------------------
# 12. hdrs constants
# ---------------------------------------------------------------------------
def hdrs_constants():
    from aiohttp import hdrs
    assert hdrs.METH_GET == "GET"
    assert hdrs.METH_POST == "POST"
    assert hdrs.METH_PUT == "PUT"
    assert hdrs.METH_DELETE == "DELETE"
    assert hdrs.CONTENT_TYPE
    assert hdrs.AUTHORIZATION


# ---------------------------------------------------------------------------
# 13. exceptions
# ---------------------------------------------------------------------------
def exceptions_importable():
    from aiohttp import (
        ClientError,
        ClientResponseError,
        ClientConnectorError,
        ClientConnectionError,
        ClientPayloadError,
        ClientOSError,
        ContentTypeError,
        WSServerHandshakeError,
        WSMsgType,
        TCPConnector,
    )
    print("    all exceptions importable")


# ---------------------------------------------------------------------------
# 14. async context manager protocol
# ---------------------------------------------------------------------------
def async_context():
    import aiohttp
    async def _run():
        async with aiohttp.ClientSession() as s:
            assert not s.closed
        assert s.closed
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 15. request method signatures
# ---------------------------------------------------------------------------
def request_methods():
    import aiohttp
    async def _run():
        async with aiohttp.ClientSession() as s:
            assert hasattr(s, "get")
            assert hasattr(s, "post")
            assert hasattr(s, "put")
            assert hasattr(s, "delete")
            assert hasattr(s, "patch")
            assert hasattr(s, "head")
    asyncio.run(_run())


# ---------------------------------------------------------------------------
# 16. multidict integration
# ---------------------------------------------------------------------------
def multidict_integration():
    from multidict import CIMultiDict, CIMultiDictProxy
    d = CIMultiDict({"Content-Type": "text/html", "X-Custom": "val"})
    proxy = CIMultiDictProxy(d)
    assert proxy["Content-Type"] == "text/html"
    assert proxy["X-Custom"] == "val"


# ---------------------------------------------------------------------------
# 17. yarl integration
# ---------------------------------------------------------------------------
def yarl_integration():
    from yarl import URL
    u = URL("http://example.com/path?q=1#frag")
    assert u.host == "example.com"
    assert u.path == "/path"
    assert u.query_string == "q=1"


# ---------------------------------------------------------------------------
# 18. frozenlist integration
# ---------------------------------------------------------------------------
def frozenlist_integration():
    from frozenlist import FrozenList
    fl = FrozenList([1, 2, 3])
    fl.freeze()
    assert fl.frozen
    assert list(fl) == [1, 2, 3]


# ---------------------------------------------------------------------------
# 19. aiosignal integration
# ---------------------------------------------------------------------------
def aiosignal_integration():
    from aiosignal import Signal
    sig = Signal(owner=object())
    assert len(sig) == 0


# ---------------------------------------------------------------------------
# 20. attrs integration
# ---------------------------------------------------------------------------
def attrs_integration():
    import attr
    @attr.s(auto_attribs=True)
    class Point:
        x: float
        y: float
    p = Point(1.0, 2.0)
    assert p.x == 1.0
    assert p.y == 2.0


# ---------------------------------------------------------------------------
# 21. propcache integration
# ---------------------------------------------------------------------------
def propcache_integration():
    from propcache import cached_property
    class Obj:
        @cached_property
        def val(self):
            return 42
    o = Obj()
    assert o.val == 42
    assert o.val == 42  # cached


# ---------------------------------------------------------------------------
# 22. C extensions loaded
# ---------------------------------------------------------------------------
def c_extensions():
    import aiohttp._http_parser
    print("    _http_parser loaded")
    import aiohttp._websocket
    print("    _websocket loaded")
    try:
        import aiohttp._speedups
        print("    _speedups loaded")
    except ImportError:
        print("    _speedups not present (removed in 3.14+)")
    import aiohttp._cookies
    print("    _cookies loaded")


# ---------------------------------------------------------------------------
# 23. aiohttp version info
# ---------------------------------------------------------------------------
def version_info():
    import aiohttp
    parts = aiohttp.__version__.split(".")
    assert len(parts) >= 2
    major = int(parts[0])
    assert major >= 3, "expected aiohttp >= 3.x"


# ---------------------------------------------------------------------------
# 24. payload helpers
# ---------------------------------------------------------------------------
def payload_bytes():
    from aiohttp import payload
    p = payload.BytesPayload(b"hello")
    assert p.size == 5


def payload_str():
    from aiohttp import payload
    p = payload.StringPayload("hello")
    assert p is not None


def payload_json():
    from aiohttp import payload
    p = payload.JsonPayload({"key": "value"})
    assert p is not None


# ---------------------------------------------------------------------------
# 25. run test
# ---------------------------------------------------------------------------
def http_run():
    import aiohttp
    async def _run():
        async with aiohttp.ClientSession() as s:
            async with s.get("http://httpbin.org/get") as resp:
                assert resp.status == 200
    try:
        asyncio.run(asyncio.wait_for(_run(), timeout=15))
    except Exception:
        raise NotImplementedError("network not available on device")


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. aiohttp import / version")
    test("import aiohttp", import_aiohttp)
    test("import submodules", import_submodules)

    section("2. ClientSession")
    test("create and close session", session_create)
    test("custom timeout", session_timeout)

    section("3. URL construction")
    test("url building via urllib", url_building)

    section("4. Request / response objects")
    test("RequestInfo creation", request_repr)

    section("5. FormData")
    test("FormData add fields", formdata_add)
    test("FormData text content_type", formdata_text)

    section("6. Multipart")
    test("MultipartReader creation", multipart_reader)

    section("7. TCPConnector")
    test("connector create + limits", connector_create)
    test("connector DNS cache", connector_dns)

    section("8. CookieJar")
    test("CookieJar basics", cookiejar_basics)
    test("CookieJar clear", cookiejar_clear)

    section("9. BasicAuth")
    test("BasicAuth creation", basicauth)
    test("BasicAuth decode header", basicauth_from_header)

    section("10. ClientTimeout")
    test("timeout defaults", timeout_defaults)
    test("timeout custom", timeout_custom)

    section("11. WSMsgType")
    test("WSMsgType constants", wsmsgtype)

    section("12. hdrs constants")
    test("HTTP method and header constants", hdrs_constants)

    section("13. exceptions")
    test("all exceptions importable", exceptions_importable)

    section("14. async context manager")
    test("session context manager protocol", async_context)

    section("15. request methods")
    test("session request methods available", request_methods)

    section("16. multidict integration")
    test("CIMultiDict / CIMultiDictProxy", multidict_integration)

    section("17. yarl integration")
    test("URL parsing", yarl_integration)

    section("18. frozenlist integration")
    test("FrozenList freeze", frozenlist_integration)

    section("19. aiosignal integration")
    test("Signal creation", aiosignal_integration)

    section("20. attrs integration")
    test("attrs auto_attribs class", attrs_integration)

    section("21. propcache integration")
    test("cached_property", propcache_integration)

    section("22. C extensions")
    test("_http_parser loaded", c_extensions)

    section("23. version info")
    test("aiohttp >= 3.x", version_info)

    section("24. payload helpers")
    test("BytesPayload", payload_bytes)
    test("StringPayload", payload_str)
    test("JsonPayload", payload_json)

    section("25. HTTP run (network)")
    test("GET httpbin.org", http_run)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
