"""
On-device verification for the cross-compiled bcrypt wheel (Rust/PyO3).

Run after installing:
    pip install bcrypt-<ver>-cp312-cp312-android_24_<ABI>.whl
        where <ABI> = arm64_v8a (real device) or x86_64 (emulator)

Usage:
    python Test_bcrypt.py [--quick]

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_bcrypt():
    import bcrypt
    print("    bcrypt", bcrypt.__version__)
    assert isinstance(bcrypt.__version__, str)


def version_tuple():
    import bcrypt
    v = bcrypt.__version_tuple__
    assert isinstance(v, tuple)
    assert len(v) >= 2
    print("    version_tuple:", v)


# ---------------------------------------------------------------------------
# 2. hashpw basic
# ---------------------------------------------------------------------------
def hashpw_basic():
    import bcrypt
    password = b"super secret password"
    hashed = bcrypt.hashpw(password, bcrypt.gensalt())
    assert hashed is not None
    assert len(hashed) > 0
    assert hashed.startswith(b"$2")


# ---------------------------------------------------------------------------
# 3. hashpw with different rounds
# ---------------------------------------------------------------------------
def hashpw_rounds():
    import bcrypt
    for rounds in (4, 6, 8):
        h = bcrypt.hashpw(b"test", bcrypt.gensalt(rounds=rounds))
        assert h is not None
        print("    rounds=%d -> %d bytes" % (rounds, len(h)))


# ---------------------------------------------------------------------------
# 4. checkpw correct
# ---------------------------------------------------------------------------
def checkpw_correct():
    import bcrypt
    password = b"my password"
    hashed = bcrypt.hashpw(password, bcrypt.gensalt())
    assert bcrypt.checkpw(password, hashed) is True


def checkpw_wrong():
    import bcrypt
    password = b"my password"
    hashed = bcrypt.hashpw(password, bcrypt.gensalt())
    assert bcrypt.checkpw(b"wrong password", hashed) is False


# ---------------------------------------------------------------------------
# 5. gensalt
# ---------------------------------------------------------------------------
def gensalt_default():
    import bcrypt
    salt = bcrypt.gensalt()
    assert salt.startswith(b"$2")
    assert len(salt) == 29


def gensalt_rounds_range():
    import bcrypt
    for r in (4, 10, 12):
        s = bcrypt.gensalt(rounds=r)
        assert s is not None


# ---------------------------------------------------------------------------
# 6. kdf
# ---------------------------------------------------------------------------
def kdf_basic():
    import bcrypt
    dk = bcrypt.kdf(
        password=b"password",
        salt=b"salt"*4,
        desired_key_bytes=32,
        rounds=1000,
    )
    assert len(dk) == 32


def kdf_64_bytes():
    import bcrypt
    dk = bcrypt.kdf(
        password=b"pass",
        salt=b"salt"*2,
        desired_key_bytes=64,
        rounds=500,
    )
    assert len(dk) == 64


# ---------------------------------------------------------------------------
# 7. hashpw returns bytes
# ---------------------------------------------------------------------------
def hashpw_returns_bytes():
    import bcrypt
    h = bcrypt.hashpw(b"test", bcrypt.gensalt())
    assert isinstance(h, bytes)


# ---------------------------------------------------------------------------
# 8. hashpw Unicode password
# ---------------------------------------------------------------------------
def hashpw_unicode():
    import bcrypt
    password = "p\u00e4ssw\u00f6rd".encode("utf-8")
    h = bcrypt.hashpw(password, bcrypt.gensalt())
    assert bcrypt.checkpw(password, h)


# ---------------------------------------------------------------------------
# 9. hashpw empty password
# ---------------------------------------------------------------------------
def hashpw_empty():
    import bcrypt
    h = bcrypt.hashpw(b"", bcrypt.gensalt())
    assert h is not None
    assert bcrypt.checkpw(b"", h)


# ---------------------------------------------------------------------------
# 10. hashpw long password
# ---------------------------------------------------------------------------
def hashpw_long():
    import bcrypt
    password = b"x" * 72  # bcrypt truncates at 72 bytes
    h = bcrypt.hashpw(password, bcrypt.gensalt())
    assert h is not None
    h2 = bcrypt.hashpw(b"x" * 100, bcrypt.gensalt())
    # both should produce valid hashes
    assert h2 is not None


# ---------------------------------------------------------------------------
# 11. checkpw type safety
# ---------------------------------------------------------------------------
def checkpw_type():
    import bcrypt
    h = bcrypt.hashpw(b"test", bcrypt.gensalt())
    assert isinstance(bcrypt.checkpw(b"test", h), bool)


# ---------------------------------------------------------------------------
# 12. hashpw invalid salt
# ---------------------------------------------------------------------------
def hashpw_bad_salt():
    import bcrypt
    try:
        bcrypt.hashpw(b"test", b"not-a-valid-salt")
        # should either raise or produce a hash
    except ValueError:
        pass  # expected


# ---------------------------------------------------------------------------
# 13. htpasswd compatibility
# ---------------------------------------------------------------------------
def htpasswd_compat():
    import bcrypt
    h = bcrypt.hashpw(b"admin", bcrypt.gensalt(rounds=4))
    assert h[:3] in (b"$2a", b"$2b", b"$2y")


# ---------------------------------------------------------------------------
# 14. repeated hashing deterministic
# ---------------------------------------------------------------------------
def hash_deterministic():
    import bcrypt
    salt = b"$2b$12$AAAAAAAAAAAAAAAAAAAAAAAA" + b"u" * 8
    h1 = bcrypt.hashpw(b"test", salt)
    h2 = bcrypt.hashpw(b"test", salt)
    assert h1 == h2


# ---------------------------------------------------------------------------
# 15. multiple hashes different
# ---------------------------------------------------------------------------
def hash_unique():
    import bcrypt
    h1 = bcrypt.hashpw(b"test", bcrypt.gensalt())
    h2 = bcrypt.hashpw(b"test", bcrypt.gensalt())
    assert h1 != h2  # different random salts


# ---------------------------------------------------------------------------
# 16. kdf with different sizes
# ---------------------------------------------------------------------------
def kdf_various_sizes():
    import bcrypt
    for size in (16, 32, 48, 64, 128):
        dk = bcrypt.kdf(
            password=b"p", salt=b"s" * 8,
            desired_key_bytes=size, rounds=100,
        )
        assert len(dk) == size


# ---------------------------------------------------------------------------
# 17. base64 utilities
# ---------------------------------------------------------------------------
def base64_util():
    import bcrypt
    b64 = bcrypt._common.b64_encode(b"test data")
    assert isinstance(b64, str)
    decoded = bcrypt._common.b64_decode(b64)
    assert decoded == b"test data"


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. bcrypt import / version")
    test("import bcrypt", import_bcrypt)
    test("version_tuple", version_tuple)

    section("2. hashpw basic")
    test("hashpw returns valid hash", hashpw_basic)

    section("3. hashpw rounds")
    test("hashpw with different rounds", hashpw_rounds)

    section("4. checkpw")
    test("checkpw correct password", checkpw_correct)
    test("checkpw wrong password", checkpw_wrong)

    section("5. gensalt")
    test("gensalt default 29 bytes", gensalt_default)
    test("gensalt rounds range", gensalt_rounds_range)

    section("6. kdf")
    test("kdf 32-byte key", kdf_basic)
    test("kdf 64-byte key", kdf_64_bytes)

    section("7. type checks")
    test("hashpw returns bytes", hashpw_returns_bytes)

    section("8. Unicode password")
    test("hashpw unicode UTF-8", hashpw_unicode)

    section("9. edge cases")
    test("hashpw empty password", hashpw_empty)
    test("hashpw long password (72-byte truncation)", hashpw_long)

    section("10. checkpw type")
    test("checkpw returns bool", checkpw_type)

    section("11. invalid salt")
    test("hashpw with invalid salt", hashpw_bad_salt)

    section("12. htpasswd compatibility")
    test("2a/2b/2y prefix", htpasswd_compat)

    section("13. determinism")
    test("same salt same hash", hash_deterministic)
    test("different random salts", hash_unique)

    section("14. kdf sizes")
    test("kdf various output sizes", kdf_various_sizes)

    section("15. base64 utilities")
    test("b64 encode/decode", base64_util)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
