#!/usr/bin/env python3
"""argon2-cffi-bindings 25.1.0 device test.

Sections:
  1. import + constants surface (types, versions, error codes, min/max)
  2. known-vector hashes (Argon2d/i/id, v1.3 and v1.0, via lib.argon2_hash)
  3. PHC encoded string output + argon2_verify round-trip
  4. argon2_encodedlen
  5. error paths (bad parameters -> non-zero error code + message)
  6. low-level argon2_ctx (struct-based API)
  7. concurrency (thread.c path, parallel hashing)

Reference vectors were generated on the host with the upstream
argon2-cffi-bindings 25.1.0 package (cffi-backed, same libargon2 sources);
the Argon2i v1.3 vector matches the RFC 9106 test vector.

Generated by RIMI
"""
import sys

PASS = FAIL = SKIP = 0


def chk(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print("  PASS  %s %s" % (name, detail))
    else:
        FAIL += 1
        print("  FAIL  %s %s" % (name, detail))


def section(title):
    print("\n=== %s ===" % title)


section("1. import + constants surface")
from _argon2_cffi_bindings import ffi, lib  # noqa: E402

chk("ffi is cffi FFI", hasattr(ffi, "new") and hasattr(ffi, "string") and hasattr(ffi, "NULL"))
chk("lib has argon2_hash", hasattr(lib, "argon2_hash"))
chk("lib has argon2_verify", hasattr(lib, "argon2_verify"))
chk("lib has argon2_ctx", hasattr(lib, "argon2_ctx"))
chk("lib has argon2_encodedlen", hasattr(lib, "argon2_encodedlen"))
chk("lib has argon2_error_message", hasattr(lib, "argon2_error_message"))

chk("type enum Argon2_d=0", lib.Argon2_d == 0)
chk("type enum Argon2_i=1", lib.Argon2_i == 1)
chk("type enum Argon2_id=2", lib.Argon2_id == 2)
chk("version v1.0=16", lib.ARGON2_VERSION_10 == 16)
chk("version v1.3=19", lib.ARGON2_VERSION_13 == 19)
chk("version number=19", lib.ARGON2_VERSION_NUMBER == 19)
chk("ARGON2_OK==0", lib.ARGON2_OK == 0)
chk("ARGON2_VERIFY_MISMATCH<0", lib.ARGON2_VERIFY_MISMATCH < 0)
chk("ARGON2_MEMORY_TOO_LITTLE<0", lib.ARGON2_MEMORY_TOO_LITTLE < 0)
chk("ARGON2_ENCODING_FAIL<0", lib.ARGON2_ENCODING_FAIL < 0)
chk("min/max constants ints", all(
    isinstance(getattr(lib, n), int) for n in (
        "ARGON2_MIN_TIME", "ARGON2_MAX_TIME", "ARGON2_MIN_MEMORY", "ARGON2_MAX_MEMORY",
        "ARGON2_MIN_LANES", "ARGON2_MAX_LANES", "ARGON2_MIN_THREADS", "ARGON2_MAX_THREADS",
        "ARGON2_MIN_OUTLEN", "ARGON2_MAX_OUTLEN", "ARGON2_MIN_PWD_LENGTH", "ARGON2_MAX_PWD_LENGTH",
        "ARGON2_MIN_SALT_LENGTH", "ARGON2_MAX_SALT_LENGTH", "ARGON2_SYNC_POINTS",
        "ARGON2_FLAG_CLEAR_PASSWORD", "ARGON2_FLAG_CLEAR_SECRET", "ARGON2_DEFAULT_FLAGS")))
chk("ARGON2_MIN_MEMORY>=8", lib.ARGON2_MIN_MEMORY >= 8)
chk("ARGON2_SYNC_POINTS==4", lib.ARGON2_SYNC_POINTS == 4)


def raw_hash(pwd, salt, t, m, p, hlen, typ, ver):
    out = ffi.new("uint8_t[]", hlen)
    rc = lib.argon2_hash(t, m, p, pwd, len(pwd), salt, len(salt), out, hlen, ffi.NULL, 0, typ, ver)
    return rc, bytes(ffi.buffer(out, hlen))


def hex_of(rc_hash):
    return rc_hash[1].hex() if rc_hash[0] == 0 else None


section("2. known-vector hashes")
PWD = b"password"
SALT = b"somesalt"
vectors = [
    ("argon2d  v13 t=2 m=65536 p=1", 0, 19, 2, 65536, 1,
     "955e5d5b163a1b60bba35fc36d0496474fba4f6b59ad53628666f07fb2f93eaf"),
    ("argon2i  v13 t=2 m=65536 p=1", 1, 19, 2, 65536, 1,
     "c1628832147d9720c5bd1cfd61367078729f6dfb6f8fea9ff98158e0d7816ed0"),
    ("argon2id v13 t=2 m=65536 p=1", 2, 19, 2, 65536, 1,
     "09316115d5cf24ed5a15a31a3ba326e5cf32edc24702987c02b6566f61913cf7"),
    ("argon2d  v10 t=3 m=4096  p=2", 0, 16, 3, 4096, 2,
     "ca3f6283e132484c5ec83c164a7733d010b8a381d4e7a29a"),
    ("argon2i  v10 t=3 m=4096  p=2", 1, 16, 3, 4096, 2,
     "0ffdda7b4998635c02533d73fcf15a150dace411417d421b"),
    ("argon2id v10 t=3 m=4096  p=2", 2, 16, 3, 4096, 2,
     "cc79b0e5c0c0b59d85037296d2b68e6f13b7b50e1981531b"),
]
for name, typ, ver, t, m, p, expect in vectors:
    rc, h = raw_hash(PWD, SALT, t, m, p, 32 if ver == 19 else 24, typ, ver)
    chk(name, rc == 0 and h.hex() == expect, "rc=%d got=%s" % (rc, h.hex()[:16] + "..."))

rc, h32 = raw_hash(PWD, SALT, 2, 65536, 1, 32, 2, 19)
chk("hash output length honored", rc == 0 and len(h32) == 32)
rc, h16 = raw_hash(PWD, SALT, 2, 65536, 1, 16, 2, 19)
chk("hash output length 16", rc == 0 and len(h16) == 16 and h16 != h32[:16])


section("3. PHC encoded string + verify round-trip")
enc_len = lib.argon2_encodedlen(2, 65536, 1, len(SALT), 32, lib.Argon2_id)
encoded = ffi.new("char[]", enc_len)
out = ffi.new("uint8_t[]", 32)
rc = lib.argon2_hash(2, 65536, 1, PWD, len(PWD), SALT, len(SALT), out, 32,
                     encoded, enc_len, lib.Argon2_id, lib.ARGON2_VERSION_13)
enc_str = ffi.string(encoded).decode("ascii")
chk("encode rc==0", rc == 0, "rc=%d" % rc)
chk("encoded prefix", enc_str.startswith("$argon2id$v=19$m=65536,t=2,p=1$"),
    repr(enc_str[:42]))
chk("encoded length sane", enc_len > 40 and len(enc_str) <= enc_len,
    "len=%d enc_len=%d" % (len(enc_str), enc_len))
rcv = lib.argon2_verify(enc_str.encode("ascii"), PWD, len(PWD), lib.Argon2_id)
chk("verify correct pwd rc==0", rcv == 0, "rc=%d" % rcv)
rcv = lib.argon2_verify(enc_str.encode("ascii"), b"wrongpassword", 13, lib.Argon2_id)
chk("verify wrong pwd -> mismatch", rcv == lib.ARGON2_VERIFY_MISMATCH,
    "rc=%d expected %d" % (rcv, lib.ARGON2_VERIFY_MISMATCH))
rcv = lib.argon2_verify(enc_str.encode("ascii"), PWD, len(PWD), lib.Argon2_i)
chk("verify wrong type rejected", rcv != 0, "rc=%d" % rcv)
rcv = lib.argon2_verify(b"$argon2id$v=19$m=0,t=0,p=0$AAAAAAAA", PWD, len(PWD), lib.Argon2_id)
chk("verify corrupt encoded -> rc!=0", rcv != 0, "rc=%d" % rcv)


section("4. argon2_encodedlen")
chk("encodedlen 65536/2/1 salt16 tag32 id", lib.argon2_encodedlen(2, 65536, 1, 16, 32, 2) == 98)
chk("encodedlen monotonic in saltlen",
    lib.argon2_encodedlen(2, 65536, 1, 16, 32, 2) <
    lib.argon2_encodedlen(2, 65536, 1, 32, 32, 2))
chk("encodedlen monotonic in taglen",
    lib.argon2_encodedlen(2, 65536, 1, 16, 16, 2) <
    lib.argon2_encodedlen(2, 65536, 1, 16, 64, 2))


section("5. error paths")
def err_name(rc):
    return ffi.string(lib.argon2_error_message(rc)).decode("ascii")


chk("error_message(OK)=='OK'", err_name(0) == "OK", repr(err_name(0)))
chk("error_message unknown code non-empty", len(err_name(-999)) > 0)
rc, _ = raw_hash(PWD, SALT, 0, 65536, 1, 32, 2, 19)
chk("t_cost=0 rejected", rc != 0 and err_name(rc) != "", "rc=%d msg=%r" % (rc, err_name(rc)))
rc, _ = raw_hash(PWD, SALT, 2, 0, 1, 32, 2, 19)
chk("m_cost=0 rejected", rc != 0, "rc=%d" % rc)
rc, _ = raw_hash(PWD, SALT, 2, 65536, 0, 32, 2, 19)
chk("parallelism=0 rejected", rc != 0, "rc=%d" % rc)
rc, _ = raw_hash(PWD, SALT, 2, 65536, 1, 0, 2, 19)
chk("hashlen=0 rejected", rc != 0, "rc=%d" % rc)
rc, _ = raw_hash(PWD, b"", 2, 65536, 1, 32, 2, 19)
chk("empty salt rejected", rc == lib.ARGON2_SALT_TOO_SHORT, "rc=%d" % rc)
rc, _ = raw_hash(PWD, SALT, 2, 65536, 1, 32, 99, 19)
chk("invalid type rejected", rc != 0, "rc=%d" % rc)


section("6. low-level argon2_ctx")
ctx = ffi.new("argon2_context *")
pwdb = ffi.new("uint8_t[]", PWD)
saltb = ffi.new("uint8_t[]", SALT)
out = ffi.new("uint8_t[]", 32)
ctx.out = out
ctx.outlen = 32
ctx.pwd = pwdb
ctx.pwdlen = len(PWD)
ctx.salt = saltb
ctx.saltlen = len(SALT)
ctx.secret = ffi.NULL
ctx.secretlen = 0
ctx.ad = ffi.NULL
ctx.adlen = 0
ctx.t_cost = 2
ctx.m_cost = 65536
ctx.lanes = 1
ctx.threads = 1
ctx.version = lib.ARGON2_VERSION_13
ctx.allocate_cbk = ffi.NULL
ctx.free_cbk = ffi.NULL
ctx.flags = lib.ARGON2_DEFAULT_FLAGS
rc = lib.argon2_ctx(ctx, lib.Argon2_id)
h = bytes(ffi.buffer(out, 32))
chk("argon2_ctx rc==0", rc == 0, "rc=%d" % rc)
chk("argon2_ctx output matches reference", h.hex() == vectors[2][6],
    h.hex()[:16] + "...")


section("7. concurrency")
import threading  # noqa: E402

results = {}
lock = threading.Lock()


def work(i):
    rc, h = raw_hash(b"pw%02dxx" % i, b"salt%02dxx" % i, 2, 4096, 2, 24, 2, 19)
    with lock:
        results[i] = (rc, h.hex())


ts = [threading.Thread(target=work, args=(i,)) for i in range(4)]
for t in ts:
    t.start()
for t in ts:
    t.join()
chk("parallel hashing all rc==0", all(results[i][0] == 0 for i in range(4)))
chk("parallel hashing deterministic", len({results[i][1] for i in range(4)}) == 4)

print("\n===== RESULT: PASS=%d FAIL=%d SKIP=%d =====" % (PASS, FAIL, SKIP))
sys.exit(1 if FAIL else 0)
