"""
On-device verification for the cross-compiled ujson 5.13.0 wheel.

ujson is an ultra-fast JSON encoder/decoder (C). The native extension is the
module itself: ujson.cpython-312.so at top level - there is NO pure-Python
fallback; without it `import ujson` fails entirely.

No runtime deps. requires-python >=3.10.

Usage:
    python Test_ujson.py

Exit code 0 = everything required PASSed.

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


def eq(label, a, b):
    if a != b:
        raise AssertionError("%s: %r != %r" % (label, a, b))
    return True


# ---------------------------------------------------------------------------
# 1. import surface + version + native extension active
# ---------------------------------------------------------------------------
def t_import():
    import ujson
    section("===== import =====")
    print("ujson:", ujson.__file__)
    eq("version", ujson.__version__, "5.13.0")
    eq("native ext", True, ujson.__file__.endswith(".so")
       or ujson.__file__.endswith(".pyd"))
    for name in ("dumps", "loads", "encode", "decode", "dump", "load",
                 "JSONDecodeError"):
        eq("exports %s" % name, True, hasattr(ujson, name))


# ---------------------------------------------------------------------------
# 2. dumps / loads round trip (compact output)
# ---------------------------------------------------------------------------
def t_roundtrip():
    import ujson
    section("===== dumps / loads =====")
    obj = {"a": 1, "b": [1, 2, None, True, False], "c": "x"}
    eq("round trip", ujson.loads(ujson.dumps(obj, indent=0)), obj)
    eq("compact", ujson.dumps(obj, indent=0),
       '{"a":1,"b":[1,2,null,true,false],"c":"x"}')
    eq("loads bytes", ujson.loads(b'{"x": 1}'), {"x": 1})
    eq("loads str", ujson.loads('{"x": 1}'), {"x": 1})
    eq("nested", ujson.loads(ujson.dumps({"k": {"l": [1, 2]}}, indent=0)),
       {"k": {"l": [1, 2]}})


# ---------------------------------------------------------------------------
# 3. unicode: ensure_ascii on/off + html escaping
# ---------------------------------------------------------------------------
def t_unicode():
    import ujson
    section("===== unicode =====")
    eq("ensure_ascii on", ujson.dumps({"s": "caf\u00e9 \u00fc"}, indent=0),
       '{"s":"caf\\u00e9 \\u00fc"}')
    eq("ensure_ascii off", ujson.dumps({"s": "caf\u00e9"}, ensure_ascii=False,
                                       indent=0), '{"s":"caf\u00e9"}')
    eq("html chars", ujson.dumps({"s": "<b>&\u2028"}, encode_html_chars=True,
                                 indent=0), '{"s":"\\u003cb\\u003e\\u0026\\u2028"}')


# ---------------------------------------------------------------------------
# 4. sort_keys + slash escaping
# ---------------------------------------------------------------------------
def t_sort_slash():
    import ujson
    section("===== sort_keys / forward slash =====")
    eq("sort_keys", ujson.dumps({"b": 1, "a": 2}, sort_keys=True, indent=0),
       '{"a":2,"b":1}')
    eq("escape slash on", ujson.dumps({"u": "http://x/"}, indent=0),
       '{"u":"http:\\/\\/x\\/"}')
    eq("escape slash off", ujson.dumps({"u": "http://x/"},
                                       escape_forward_slashes=False, indent=0),
       '{"u":"http://x/"}')


# ---------------------------------------------------------------------------
# 5. numeric edge cases
# ---------------------------------------------------------------------------
def t_numeric():
    import ujson
    section("===== numeric =====")
    eq("int", ujson.loads(ujson.dumps(123456789012345678901234567890, indent=0)),
       123456789012345678901234567890)
    eq("float", ujson.loads(ujson.dumps(1.5, indent=0)), 1.5)
    eq("float shortest", ujson.dumps(1.0 / 3.0, indent=0),
       "0.3333333333333333")
    eq("negative zero", ujson.loads(ujson.dumps(-0.0, indent=0)), -0.0)
    eq("nan ok", ujson.loads(ujson.dumps(float("nan"), indent=0)).__class__,
       float)
    try:
        ujson.dumps(float("nan"), allow_nan=False, indent=0)
        raise AssertionError("nan with allow_nan=False did not raise")
    except OverflowError:
        pass


# ---------------------------------------------------------------------------
# 6. reject_bytes (5.x default True) + indentation
# ---------------------------------------------------------------------------
def t_bytes_indent():
    import ujson
    section("===== bytes / indent =====")
    try:
        ujson.dumps({"b": b"\x01\x02"}, indent=0)
        raise AssertionError("bytes value did not raise by default")
    except TypeError:
        pass
    eq("reject_bytes False", ujson.dumps({"b": b"hi"}, reject_bytes=False,
                                         indent=0), '{"b":"hi"}')
    eq("indent 2", ujson.dumps({"a": 1}, indent=2), '{\n  "a": 1\n}')
    eq("indent 2 nested", ujson.dumps({"a": {"b": 2}}, indent=2),
       '{\n  "a": {\n    "b": 2\n  }\n}')


# ---------------------------------------------------------------------------
# 7. encode / decode aliases + tuple -> array
# ---------------------------------------------------------------------------
def t_aliases():
    import ujson
    section("===== aliases / tuple =====")
    eq("encode", ujson.encode({"x": 1}, indent=0), '{"x":1}')
    eq("decode", ujson.decode('{"x": 1}'), {"x": 1})
    eq("tuple -> array", ujson.dumps((1, 2), indent=0), "[1,2]")


# ---------------------------------------------------------------------------
# 8. error handling
# ---------------------------------------------------------------------------
def t_errors():
    import ujson
    section("===== errors =====")
    try:
        ujson.loads('{"a": ')
        raise AssertionError("malformed json did not raise")
    except ujson.JSONDecodeError:
        pass
    try:
        ujson.dumps({"a": object()}, indent=0)
        raise AssertionError("unserializable object did not raise")
    except TypeError:
        pass
    d = {}
    d["self"] = d
    try:
        ujson.dumps(d, indent=0)
        raise AssertionError("cyclic structure did not raise")
    except OverflowError:
        pass


# ---------------------------------------------------------------------------
# 9. large/structured payload stress
# ---------------------------------------------------------------------------
def t_stress():
    import ujson
    section("===== stress =====")
    data = [{"id": i, "name": "item%d" % i, "values": list(range(5)),
             "flag": i % 2 == 0} for i in range(200)]
    blob = ujson.dumps(data, indent=0)
    eq("stress round trip", ujson.loads(blob), data)
    eq("starts with [", True, blob.startswith("[{"))
    eq("ends with ]", True, blob.endswith("]"))
    eq("deep nesting", ujson.loads(ujson.dumps({"a": {"a": {"a": [1]}}},
                                               indent=0)),
       {"a": {"a": {"a": [1]}}})


# ---------------------------------------------------------------------------
# result
# ---------------------------------------------------------------------------
def main():
    tests = [
        ("import surface", t_import),
        ("dumps/loads round trip", t_roundtrip),
        ("unicode + html escaping", t_unicode),
        ("sort_keys + slash escaping", t_sort_slash),
        ("numeric edge cases", t_numeric),
        ("bytes + indent", t_bytes_indent),
        ("encode/decode aliases", t_aliases),
        ("error handling", t_errors),
        ("stress", t_stress),
    ]
    for name, fn in tests:
        test(name, fn)
    print()
    print("===== result =====")
    fails = skips = 0
    for name, status, info in RESULTS:
        print("[%s] %s%s" % (status, name, "  (%s)" % info if info else ""))
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
