"""
Test_PyAES.py - PyAES Test Suite for PythonSTB (Android)
Generated by RIMI
"""
import sys

PASS = 0
FAIL = 0
SKIP = 0
RESULTS = []

def test(name, func):
    global PASS, FAIL, SKIP
    try:
        result = func()
        if result is not False:
            PASS += 1
            RESULTS.append(("PASS", name))
        elif result == "SKIP":
            SKIP += 1
            RESULTS.append(("SKIP", name))
        else:
            FAIL += 1
            RESULTS.append(("FAIL", name))
    except Exception as e:
        FAIL += 1
        RESULTS.append(("FAIL", f"{name} -> {type(e).__name__}: {e}"))

print("=" * 60)
print(" PYAES TEST SUITE")
print(" PythonSTB - Android ARM64/x86_64")
print("=" * 60)
print()

# --- Core Imports ---
test("pyaes import", lambda: __import__("pyaes"))
test("pyaes.AESModeOfOperationECB", lambda: __import__("pyaes").AESModeOfOperationECB)
test("pyaes.AESModeOfOperationCBC", lambda: __import__("pyaes").AESModeOfOperationCBC)
test("pyaes.AESModeOfOperationCFB", lambda: __import__("pyaes").AESModeOfOperationCFB)
test("pyaes.AESModeOfOperationOFB", lambda: __import__("pyaes").AESModeOfOperationOFB)
test("pyaes.AESModeOfOperationCTR", lambda: __import__("pyaes").AESModeOfOperationCTR)

# --- Version ---
def test_version():
    import pyaes
    ver = getattr(pyaes, '__version__', '1.6.1')
    print(f"    PyAES version: {ver}")
    return True
test("version info", test_version)

# --- ECB Encrypt/Decrypt ---
def test_ecb():
    import pyaes
    key = b'sixteen byte key'
    aes = pyaes.AESModeOfOperationECB(key)
    plaintext = b'test message!!!!'
    ciphertext = aes.encrypt(plaintext)
    aes2 = pyaes.AESModeOfOperationECB(key)
    decrypted = aes2.decrypt(ciphertext)
    assert decrypted == plaintext
    print(f"    ECB: {len(plaintext)} bytes encrypted/decrypted")
    return True
test("ECB encrypt/decrypt", test_ecb)

# --- CBC Encrypt/Decrypt ---
def test_cbc():
    import pyaes
    key = b'sixteen byte key'
    iv = b'16 byte IV goin!'
    aes = pyaes.AESModeOfOperationCBC(key, iv=iv)
    plaintext = b'test message!!!!'
    ciphertext = aes.encrypt(plaintext)
    aes2 = pyaes.AESModeOfOperationCBC(key, iv=iv)
    decrypted = aes2.decrypt(ciphertext)
    assert decrypted == plaintext
    print(f"    CBC: {len(plaintext)} bytes encrypted/decrypted")
    return True
test("CBC encrypt/decrypt", test_cbc)

# --- CTR Encrypt/Decrypt ---
def test_ctr():
    import pyaes
    key = b'sixteen byte key'
    ctr = pyaes.Counter(initial_value=0)
    aes = pyaes.AESModeOfOperationCTR(key, ctr)
    plaintext = b'test message!!!!'
    ciphertext = aes.encrypt(plaintext)
    ctr2 = pyaes.Counter(initial_value=0)
    aes2 = pyaes.AESModeOfOperationCTR(key, ctr2)
    decrypted = aes2.decrypt(ciphertext)
    assert decrypted == plaintext
    print(f"    CTR: {len(plaintext)} bytes encrypted/decrypted")
    return True
test("CTR encrypt/decrypt", test_ctr)

# --- Multi-block ---
def test_multiblock():
    import pyaes
    key = b'sixteen byte key'
    aes = pyaes.AESModeOfOperationECB(key)
    plaintext = b'A' * 1024
    ciphertext = b''
    for i in range(0, len(plaintext), 16):
        ciphertext += aes.encrypt(plaintext[i:i+16])
    aes2 = pyaes.AESModeOfOperationECB(key)
    decrypted = b''
    for i in range(0, len(ciphertext), 16):
        decrypted += aes2.decrypt(ciphertext[i:i+16])
    assert decrypted == plaintext
    print(f"    Multi-block: {len(plaintext)} bytes OK")
    return True
test("multi-block encrypt/decrypt", test_multiblock)

# --- Different key sizes ---
def test_key_sizes():
    import pyaes
    for ksize in [16, 24, 32]:
        key = b'A' * ksize
        aes = pyaes.AESModeOfOperationECB(key)
        plaintext = b'test message!!!!'
        ciphertext = aes.encrypt(plaintext)
        aes2 = pyaes.AESModeOfOperationECB(key)
        decrypted = aes2.decrypt(ciphertext)
        assert decrypted == plaintext
    print("    Key sizes: 128/192/256-bit all work")
    return True
test("key sizes (128/192/256)", test_key_sizes)

# --- Print Results ---
print()
print("=" * 60)
print(" RESULTS")
print("=" * 60)
for status, name in RESULTS:
    icon = "PASS" if status == "PASS" else "FAIL" if status == "FAIL" else "SKIP"
    print(f"  [{icon}] {name}")
print()
print(f"  PASS: {PASS} | FAIL: {FAIL} | SKIP: {SKIP}")
print(f"  TOTAL: {PASS + FAIL + SKIP}")
print("=" * 60)

if FAIL > 0:
    print("\nPYAES HAS FAILURES")
    sys.exit(1)
else:
    print("\nPYAES ALL PASSED")
    sys.exit(0)
