#!/usr/bin/env python3
"""Test_Pycares.py - on-device/on-host validation for the pycares 5.x wheel.

Drives the real c-ares resolver through the bundled _cares C extension and
runs the DNS diagnostics (resolv.conf, env, raw UDP probes, per-attempt query
timing). Exit code 0 = all tests passed (no FAILs). The diagnostics section
never fails the run - it is informational.

Generated by RIMI
"""
import os
import socket
import sys
import time

import pycares
from pycares import Channel

RESULTS = []
DNS_SLEEP = 10


def test(name, fn):
    try:
        fn()
        RESULTS.append(("PASS", name))
    except NotImplementedError:
        RESULTS.append(("SKIP", name))
    except Exception as e:  # noqa: BLE001
        RESULTS.append(("FAIL", name, str(e)))


def section(title):
    print("\n===== %s =====" % title)


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


def _can_dns():
    try:
        socket.getaddrinfo("example.com", 80, socket.AF_INET)
        return True
    except Exception:
        return False


def _sync_query(ch, fn, timeout=DNS_SLEEP):
    """Run a callback-based channel op synchronously; return (result, errno)."""
    box = {}

    def cb(result, errno):
        box["result"] = result
        box["errno"] = errno

    fn(cb)
    ch.wait(timeout)
    if "result" not in box:
        raise AssertionError("callback did not fire within %ds" % timeout)
    return box.get("result"), box.get("errno")


def test_imports():
    check(pycares.__version__ == "5.0.1", "version: %s" % pycares.__version__)
    ch = Channel()
    check(ch is not None, "Channel() failed")
    check(hasattr(pycares, "_cares"), "module 'pycares' has no attr '_cares'")


def test_constants():
    for name in ("QUERY_TYPE_A", "QUERY_TYPE_AAAA", "QUERY_TYPE_TXT",
                 "QUERY_TYPE_MX", "QUERY_TYPE_NS", "QUERY_TYPE_PTR",
                 "QUERY_TYPE_CNAME", "QUERY_TYPE_SRV"):
        check(hasattr(pycares, name), "missing %s" % name)
    check(pycares.QUERY_TYPE_A == 1, "QUERY_TYPE_A wrong")
    check(pycares.QUERY_TYPE_AAAA == 28, "QUERY_TYPE_AAAA wrong")
    check(pycares.QUERY_TYPE_TXT == 16, "QUERY_TYPE_TXT wrong")
    check(hasattr(pycares, "AresError"), "AresError missing")
    check(hasattr(pycares, "errno"), "errno module missing")
    check(hasattr(pycares.errno, "ARES_ENOTFOUND"), "errno.ARES_ENOTFOUND missing")
    check(hasattr(pycares, "QUERY_CLASS_IN"), "QUERY_CLASS_IN missing")


def test_channel_params():
    ch = Channel()
    servers = ch.servers
    check(isinstance(servers, list) and servers, "no servers configured")
    for s in servers:
        check(isinstance(s, str) and ":" in s, "bad server entry %r" % s)


def test_ares_query_a():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.query(
        "example.com", pycares.QUERY_TYPE_A, callback=cb))
    check(errno is None, "query A errno %r" % (errno,))
    check(result is not None and getattr(result, "answer", None),
          "no answer records")
    ips = [r.data.addr for r in result.answer
           if getattr(r.data, "addr", None)]
    check(ips, "no A record ip in %r" % (result.answer,))
    print("  A records:", ips)


def test_ares_query_aaaa():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.query(
        "example.com", pycares.QUERY_TYPE_AAAA, callback=cb))
    if errno is not None:
        return  # AAAA may legitimately be absent
    check(result is not None, "AAAA returned None result")
    print("  AAAA records:", result.answer)


def test_ares_query_txt():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.query(
        "example.com", pycares.QUERY_TYPE_TXT, callback=cb))
    check(errno is None, "TXT query errno %r" % (errno,))
    check(result is not None, "TXT returned None result")


def test_ares_query_nxdomain():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.query(
        "nonexistent-domain-zzz-123456.invalid", pycares.QUERY_TYPE_A,
        callback=cb))
    check(errno is not None, "expected NXDOMAIN error, got errno=%r" % (errno,))


def test_getaddrinfo():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.getaddrinfo(
        "example.com", 80, family=socket.AF_INET, type=socket.SOCK_STREAM,
        callback=cb))
    check(errno is None, "getaddrinfo errno %r" % (errno,))
    check(result is not None and getattr(result, "nodes", None),
          "no address nodes")
    first = result.nodes[0]
    check(first.family == socket.AF_INET, "unexpected family %r" % first.family)
    check(isinstance(first.addr, tuple) and len(first.addr) >= 1,
          "bad node addr %r" % (first.addr,))
    print("  getaddrinfo:", first.addr)


def test_getnameinfo():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.getnameinfo(
        ("8.8.8.8", 0), 0, callback=cb))
    if errno is not None:
        raise NotImplementedError("PTR for 8.8.8.8 unavailable (errno %r)" % errno)
    check(result is not None, "getnameinfo returned None")
    node = getattr(result, "node", None)
    check(isinstance(node, str) and node, "bad nameinfo node %r" % node)
    print("  getnameinfo:", node)


def test_gethostbyaddr():
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    result, errno = _sync_query(ch, lambda cb: ch.gethostbyaddr(
        "8.8.8.8", callback=cb))
    if errno is not None:
        raise NotImplementedError("PTR for 8.8.8.8 unavailable (errno %r)" % errno)
    check(result is not None and getattr(result, "name", None),
          "no hostname in %r" % (result,))


def test_timeout_method():
    ch = Channel()
    t = ch.timeout()
    check(isinstance(t, (int, float)) or t is None,
          "timeout() returned %r" % (t,))


def test_async_channel():
    import concurrent.futures
    ch = Channel()
    if not _can_dns():
        raise NotImplementedError("no network")
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
        fut = ex.submit(_sync_query, ch, lambda cb: ch.query(
            "example.com", pycares.QUERY_TYPE_A, callback=cb))
        result, errno = fut.result()
    check(errno is None, "async A errno %r" % (errno,))
    check(result is not None and getattr(result, "answer", None),
          "async query empty")


# ------------------ Diagnostics (merged from Probe_Pycares.py) ------------------
# Informational only - never affects the pass/fail result.

def diag_resolv_conf():
    print("  resolv.conf:")
    for path in ("/data/user/0/com.pythonstb.rimi/files/python/resolv.conf",
                 "/data/local/tmp/resolv.conf"):
        try:
            with open(path) as fh:
                for line in fh:
                    print("    " + line.rstrip())
                return
        except Exception:
            continue
    print("    <not found>")


def diag_env_dns():
    try:
        env_dns = [v for k, v in os.environ.items() if "DNS" in k.upper()]
        print("  DNS env vars:", env_dns or "<none>")
    except Exception:
        print("  DNS env vars: <unreadable>")


def diag_raw_udp(ch):
    print("  raw UDP DNS probes:")
    for srv in ch.servers:
        host, _, port = srv.partition(":")
        port = int(port or 53)
        s = None
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.settimeout(3)
            t0 = time.time()
            s.connect((host, port))
            s.send(b"\x12\x34\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00"
                   b"\x07example\x03com\x00\x00\x01\x00\x01")
            data = s.recv(512)
            print("    %s:%d -> %d bytes in %.1fms"
                  % (host, port, len(data), (time.time() - t0) * 1000))
        except Exception as e:
            print("    %s:%d -> FAIL (%s)" % (host, port, e))
        finally:
            try:
                if s is not None:
                    s.close()
            except Exception:
                pass


def diag_queries():
    print("  pycares queries (3 attempts each):")
    for qname, qtype, label in (
        ("example.com", pycares.QUERY_TYPE_A, "A"),
        ("example.com", pycares.QUERY_TYPE_AAAA, "AAAA"),
        ("example.com", pycares.QUERY_TYPE_TXT, "TXT"),
        ("example.com", pycares.QUERY_TYPE_MX, "MX"),
        ("example.com", pycares.QUERY_TYPE_NS, "NS"),
    ):
        ch = Channel()
        last = None
        for attempt in range(1, 4):
            result, errno = _sync_query(ch, lambda cb, _q=qname, _t=qtype: ch.query(
                _q, _t, callback=cb), timeout=8)
            nans = len(result.answer) if result is not None and getattr(result, "answer", None) else 0
            print("    %-5s attempt %d: errno=%s answers=%d"
                  % (label, attempt, errno, nans))
            if errno is None and nans:
                last = ("OK", nans)
                break
            last = (str(errno), nans)
        print("    %-5s final: %s" % (label, last))


def run_diagnostics():
    section("DNS diagnostics")
    print("  pycares:", pycares.__version__)
    ch = Channel()
    print("  Channel.servers:", ch.servers)
    print("  Channel.timeout:", ch.timeout())
    print("  flags:", getattr(ch, "_flags", "?"))
    diag_resolv_conf()
    diag_env_dns()
    diag_raw_udp(ch)
    diag_queries()


def main():
    section("pycares %s - import/constants" % pycares.__version__)
    test("import + version", test_imports)
    test("constants", test_constants)

    section("Channel")
    test("channel params (servers)", test_channel_params)
    test("timeout()", test_timeout_method)

    section("DNS queries (network)")
    test("query A (example.com)", test_ares_query_a)
    test("query AAAA (example.com)", test_ares_query_aaaa)
    test("query TXT (example.com)", test_ares_query_txt)
    test("query NXDOMAIN error path", test_ares_query_nxdomain)
    test("getaddrinfo (example.com:80)", test_getaddrinfo)
    test("getnameinfo (8.8.8.8)", test_getnameinfo)
    test("gethostbyaddr (8.8.8.8)", test_gethostbyaddr)
    test("query A via thread/async", test_async_channel)

    run_diagnostics()

    section("RESULT")
    n_ok = n_fail = n_skip = 0
    for r in RESULTS:
        status = r[0]
        if status == "PASS":
            n_ok += 1
            print("  OK    %s" % r[1])
        elif status == "SKIP":
            n_skip += 1
            print("  SKIP  %s" % r[1])
        else:
            n_fail += 1
            print("  FAIL  %s: %s" % (r[1], r[2]))
    print("RESULT: %d ok, %d failed, %d skipped" % (n_ok, n_fail, n_skip))
    if "--quick" not in sys.argv[1:]:
        sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
