"""
On-device verification for the cross-compiled curl_cffi wheel (C++ / curl-impersonate).

Run after installing:
    pip install curl_cffi-<ver>-cp312-cp312-android_24_<ABI>.whl
        where <ABI> = arm64_v8a (real device) or x86_64 (emulator)

Usage:
    python Test_curl_cffi.py [--quick]

Exit code 0 = everything required PASSed.
Sections marked [SKIP] are optional (need network).

Generated by RIMI
"""
import sys

RESULTS = []


def test(name, fn):
    try:
        fn()
        RESULTS.append((name, "PASS", None))
    except NotImplementedError as exc:
        RESULTS.append((name, "SKIP", str(exc)))
    except Exception as exc:
        RESULTS.append((name, "FAIL", "%s: %s" % (type(exc).__name__, exc)))
        print("    ! %s -> %s: %s" % (name, type(exc).__name__, exc))


def section(title):
    print("=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------------------
# 1. import / version
# ---------------------------------------------------------------------------
def import_curl_cffi():
    import curl_cffi
    print("    curl_cffi", curl_cffi.__version__)
    assert isinstance(curl_cffi.__version__, str)


def import_requests():
    import curl_cffi.requests
    print("    curl_cffi.requests OK")


# ---------------------------------------------------------------------------
# 2. Session creation
# ---------------------------------------------------------------------------
def session_create():
    from curl_cffi.requests import Session
    s = Session()
    assert s is not None
    s.close()


def session_context_manager():
    from curl_cffi.requests import Session
    with Session() as s:
        assert s is not None


# ---------------------------------------------------------------------------
# 3. Impersonate profiles
# ---------------------------------------------------------------------------
def impersonate_chrome():
    from curl_cffi.requests import Session
    s = Session(impersonate="chrome")
    assert s is not None
    s.close()


def impersonate_safari():
    from curl_cffi.requests import Session
    s = Session(impersonate="safari")
    assert s is not None
    s.close()


def impersonate_edge():
    from curl_cffi.requests import Session
    s = Session(impersonate="edge")
    assert s is not None
    s.close()


def impersonate_firefox():
    from curl_cffi.requests import Session
    s = Session(impersonate="firefox")
    assert s is not None
    s.close()


# ---------------------------------------------------------------------------
# 4. Request methods
# ---------------------------------------------------------------------------
def request_methods():
    from curl_cffi.requests import Session
    with Session() as s:
        assert hasattr(s, "get")
        assert hasattr(s, "post")
        assert hasattr(s, "put")
        assert hasattr(s, "delete")
        assert hasattr(s, "patch")
        assert hasattr(s, "head")


# ---------------------------------------------------------------------------
# 5. Headers
# ---------------------------------------------------------------------------
def custom_headers():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        h = {"X-Custom": "value"}
        try:
            r = s.get("https://httpbin.org/headers", headers=h)
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 6. Cookies
# ---------------------------------------------------------------------------
def cookie_handling():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/cookies/set?name=test&value=123")
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 7. POST data
# ---------------------------------------------------------------------------
def post_form():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.post("https://httpbin.org/post", data={"key": "value"})
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


def post_json():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.post(
                "https://httpbin.org/post",
                json={"key": "value"},
            )
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 8. Response attributes
# ---------------------------------------------------------------------------
def response_attributes():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/get")
            assert hasattr(r, "status_code")
            assert hasattr(r, "text")
            assert hasattr(r, "content")
            assert hasattr(r, "headers")
            assert hasattr(r, "url")
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 9. JSON response
# ---------------------------------------------------------------------------
def response_json():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/json")
            data = r.json()
            assert isinstance(data, dict)
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 10. Timeout
# ---------------------------------------------------------------------------
def timeout_setting():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome", timeout=10) as s:
        assert s is not None


# ---------------------------------------------------------------------------
# 11. proxies
# ---------------------------------------------------------------------------
def proxy_setting():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        assert s is not None


# ---------------------------------------------------------------------------
# 12. verify SSL
# ---------------------------------------------------------------------------
def verify_ssl():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome", verify=False) as s:
        assert s is not None


# ---------------------------------------------------------------------------
# 13. HTTP/2
# ---------------------------------------------------------------------------
def http2_support():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        assert s is not None


# ---------------------------------------------------------------------------
# 14. Binary content
# ---------------------------------------------------------------------------
def binary_content():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/image/png")
            assert isinstance(r.content, bytes)
            assert len(r.content) > 0
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 15. Status codes
# ---------------------------------------------------------------------------
def status_codes():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/status/404")
            assert r.status_code == 404
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 16. Redirects
# ---------------------------------------------------------------------------
def redirect_handling():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/redirect/1", allow_redirects=True)
            assert r.status_code == 200
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 17. Impersonation list
# ---------------------------------------------------------------------------
def impersonate_list():
    from curl_cffi import CurlHttpVersion
    assert CurlHttpVersion.HTTP_1_1
    assert CurlHttpVersion.HTTP_2


# ---------------------------------------------------------------------------
# 18. CurlError
# ---------------------------------------------------------------------------
def curl_error_importable():
    from curl_cffi.requests.errors import CurlError
    assert issubclass(CurlError, Exception)


# ---------------------------------------------------------------------------
# 19. BYTES response
# ---------------------------------------------------------------------------
def response_bytes():
    from curl_cffi.requests import Session
    with Session(impersonate="chrome") as s:
        try:
            r = s.get("https://httpbin.org/bytes/100")
            assert isinstance(r.content, bytes)
            assert len(r.content) == 100
        except Exception:
            raise NotImplementedError("network not available")


# ---------------------------------------------------------------------------
# 20. impersonate with version
# ---------------------------------------------------------------------------
def impersonate_versioned():
    from curl_cffi.requests import Session
    s = Session(impersonate="chrome120")
    assert s is not None
    s.close()


# ---------------------------------------------------------------------------
def main():
    quick = "--quick" in sys.argv

    section("1. curl_cffi import / version")
    test("import curl_cffi", import_curl_cffi)
    test("import curl_cffi.requests", import_requests)

    section("2. Session")
    test("session create + close", session_create)
    test("session context manager", session_context_manager)

    section("3. Impersonate profiles")
    test("impersonate chrome", impersonate_chrome)
    test("impersonate safari", impersonate_safari)
    test("impersonate edge", impersonate_edge)
    test("impersonate firefox", impersonate_firefox)

    section("4. Request methods")
    test("GET/POST/PUT/DELETE/PATCH/HEAD", request_methods)

    section("5. Headers (network)")
    test("custom headers", custom_headers)

    section("6. Cookies (network)")
    test("cookie handling", cookie_handling)

    section("7. POST (network)")
    test("POST form data", post_form)
    test("POST JSON", post_json)

    section("8. Response (network)")
    test("response attributes", response_attributes)
    test("response JSON", response_json)

    section("9. Session options")
    test("timeout setting", timeout_setting)
    test("proxy setting", proxy_setting)
    test("verify SSL False", verify_ssl)
    test("HTTP/2 support", http2_support)

    section("10. Binary / Status / Redirect (network)")
    test("binary content", binary_content)
    test("status codes 404", status_codes)
    test("redirect handling", redirect_handling)

    section("11. HTTP version / Errors")
    test("CurlHttpVersion constants", impersonate_list)
    test("CurlError importable", curl_error_importable)

    section("12. Misc (network)")
    test("BYTES response", response_bytes)
    test("impersonate chrome120", impersonate_versioned)

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    fails = 0
    skips = 0
    for name, status, why in RESULTS:
        mark = "  OK" if status == "PASS" else (" SKIP" if status == "SKIP" else "FAIL")
        print("%s %s" % (mark, name))
        if why:
            print("        -> %s" % why)
        if status == "FAIL":
            fails += 1
        elif status == "SKIP":
            skips += 1
    print()
    passed = len(RESULTS) - fails - skips
    print("passed=%d skipped=%d failed=%d" % (passed, skips, fails))
    if fails:
        print("RESULT: FAILED")
    elif skips and not quick:
        print("RESULT: PASSED (with informational skips)")
    else:
        print("RESULT: PASSED")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
